
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using QD.ERP.Web.DAL.Entities;
using Microsoft.Identity.Client;
using System.Xml.Linq;
using System.Linq;
using System.Data;



namespace QD.ERP.Web.Areas.Finance.Controllers
{
	[Route("api/[controller]")]
	[ApiController]
	public class AccountLedgerMasterController : Controller
	{
		private ERPMasterWtDataContext _context;

		public AccountLedgerMasterController(ERPMasterWtDataContext context)
		{
			this._context = context;

			//int _AutoGeneratedAccountId = _context.Tbl201ChartOfAccounts.Max(a=>a.AccountId + 1)
		}


		[HttpGet("getAccountingLedger")]
		public async Task<IActionResult> getAccountingLedger(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var qryListOfAccountlists = _context.Tbl201AccountGroups.Select(i => new
				{
					AccountGroupUnder = i.AccountGroupUnder,
					AccountGroupId = i.AccountGroupId,
					AccountGroup = i.AccountGroup
				});

				var result = await DataSourceLoader.LoadAsync(qryListOfAccountlists, loadOptions);

				// Manually iterate over the filter to find the AccountGroupId
				if (loadOptions.Filter != null)
				{
					foreach (var filterItem in loadOptions.Filter)
					{
						var filterArray = filterItem as IList<object>;
						if (filterArray != null && filterArray.Count >= 2)
						{
							if (filterArray[0].ToString() == "AccountGroupId")
							{
								var accountGroupId = filterArray[1].ToString();
								qryListOfAccountlists = qryListOfAccountlists.Where(x => x.AccountGroupId == accountGroupId);
							}
						}
					}
				}

				return Json(result);
			}
			catch (Exception ex)
			{
				// Handle exception as needed
			}

			return Json(loadOptions);
		}


		[HttpGet("getCreditDebit")]
		public async Task<IActionResult> getCreditDebit(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var qryListOfOpeningBalanceDrCr = _context.Tbl201ChartOfAccounts
												  .Where(i => i.OpeningBalanceDrCr != null)  // Exclude null values
												  .Select(i => new { OpeningBalanceDrCr = i.OpeningBalanceDrCr })  // Alias for OpeningBalanceDrCr
												  .Distinct();

				return Json(await DataSourceLoader.LoadAsync(qryListOfOpeningBalanceDrCr, loadOptions));
			}
			catch (Exception ex)
			{
				//throw ex.Message.ToString();
			}

			return Json(loadOptions);
		}

		[HttpGet("getAccountBranch")]
		public async Task<IActionResult> getAccountBranch(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var accountbranchdetailsList = _context.Tbl20115CompanyBranches
													.Select(i => new {
														BranchCode = i.BranchCode,
														BranchName = i.BranchName
													});

				return Json(await DataSourceLoader.LoadAsync(accountbranchdetailsList, loadOptions));
			}
			catch (Exception ex)
			{
				//throw ex.Message.ToString();
			}

			return Json(loadOptions);
		}

		[HttpGet("getSubGroup")]
		public async Task<IActionResult> getSubGroup(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var subgroupdetailsList = _context.Tbl20123LedgerSubGroups
													.Select(i => new {
														LedgerSubGroupCode = i.LedgerSubGroupCode,
														SubGroupName = i.SubGroupName
													});

				return Json(await DataSourceLoader.LoadAsync(subgroupdetailsList, loadOptions));
			}
			catch (Exception ex)
			{
				//throw ex.Message.ToString();
			}

			return Json(loadOptions);
		}

		[HttpGet("getSalesPersonList")]
		public async Task<IActionResult> getSalesPersonList(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var salesdetailsList = _context.Tbl20101SalesPersonMasters
													.Select(i => new {
														SalesPersonCode = i.SalesPersonCode,
														SalesPersonName = i.SalesPersonName
													});

				return Json(await DataSourceLoader.LoadAsync(salesdetailsList, loadOptions));
			}
			catch (Exception ex)
			{
				//throw ex.Message.ToString();
			}

			return Json(loadOptions);
		}

		[HttpGet("getOtherIDTypes")]
		public async Task<IActionResult> getOtherIDTypes(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var buyerdetailsList = _context.Tbl00105BuyerIdtypes
													.Select(i => new {
														BuyerOtherIDType = i.BuyerOtherIdtype,
														BuyerIDTypeName = i.BuyerIdtypeName
													});

				return Json(await DataSourceLoader.LoadAsync(buyerdetailsList, loadOptions));
			}
			catch (Exception ex)
			{
				//throw ex.Message.ToString();
			}

			return Json(loadOptions);
		}

		[HttpGet("getBillingPayments")]
		public async Task<IActionResult> getBillingPayments(DataSourceLoadOptions loadOptions)
		{
			try
			{
				var buyerdetailsList = _context.Qry20152BankAccounts
													.Select(i => new {
														BillingAccountID = i.AccountId,
														BillingAccountHead = i.AccountHead
													});

				return Json(await DataSourceLoader.LoadAsync(buyerdetailsList, loadOptions));
			}
			catch (Exception ex)
			{
				//throw ex.Message.ToString();
			}

			return Json(loadOptions);
		}

		[HttpGet("GetLedgerAccounts")]
		public async Task<ActionResult> GetLedgerAccounts(DataSourceLoadOptions loadOptions)
		{
			var qryListOfAccountlists = _context.Qry201ListOfAccounts.Where(p => p.AccountId != null).Select(i => new
			{
				i.MasterGroupId,
				i.MasterGroup,
				i.AccountGroup,
				i.AccountGroupId,
				i.AccountId,
				i.AccountHead,
				i.AccountHeadArabic,
				i.ReferenceNo,
				i.IsLedgerObselete
			});

			return Json(await DataSourceLoader.LoadAsync(qryListOfAccountlists, loadOptions));
		}

		[HttpGet("GetMaxLedgerAccountID")]
		public async Task<ActionResult> GetMaxLedgerAccountID()
		{
			try
			{
				var nextAccountId = (from account in _context.Tbl201ChartOfAccounts
									 where account.AccountId.StartsWith("L0")
									 orderby account.AccountId descending
									 select account.AccountId)
						.Take(1)
						.Select(accountId => "L" + (int.Parse(accountId.Substring(1)) + 1).ToString().PadLeft(accountId.Substring(1).Length, '0')).FirstOrDefault();

				return Json(new { nextAccountId });
			}
			catch (Exception ex)
			{
				throw ex;
			}
		}

		[HttpGet("FindDuplicatesOnAccountHead")]
		public async Task<ActionResult> FindDuplicatesOnAccountHead(string stAccountHeadValue)
		{
			var result = (from c in _context.Tbl201ChartOfAccounts
						  where c.AccountHead.ToUpper() == stAccountHeadValue.ToUpper()  // Case-insensitive comparison
						  group c by c.AccountHead into g
						  select new
						  {
							  MaxAccountId = g.Max(x => x.AccountId),  // Get the max AccountId for each AccountHead
							  IsValid = g.Count() > 0 ? true : false,
							  AccountHead = g.Key  // Grouped AccountHead
						  }).ToList();

			return Json(result);
		}

		[HttpGet("GetAttachments")]
		public async Task<ActionResult> GetAttachments()
		{
			string LedgerNo = "L00506";
			var query = from a in _context.Tbl20116LedgerDocuments
						join b in _context.Tbl101DocumentTypes on a.DocumentType equals b.DocumentTypeId
						join c in _context.Tbl201ChartOfAccounts on a.LedgerNo equals c.AccountId
						where c.AccountId == LedgerNo
						select new
						{
							DocumentType = b.DocumentType,
							DocumentRefNo = a.DocumentRefNo,
							DocumentExpDate = a.DocumentExpDate,
							DocumentNotificationDate = a.DocumentNotificationDate
						};

			return Json(query);
		}



		#region "CRUD Operation"

		[HttpPost("InsertLedgerAccount")]
		public async Task<ActionResult> InsertLedgerAccount(string AccountID, string RefNo)
		{

			var LedgerAccuntEntry = new Tbl201ChartOfAccount
			{
				AccountId = AccountID,
				AccountGroupId = RefNo
			};

			return Json(new { success = true, message = "Ledger account inserted successfully." });
		}

		//[HttpPost("Insert")]
		//public IActionResult Insert([FromBody] Tbl201ChartOfAccount chartAccount)
		//{
		//	if (chartAccount == null)
		//	{
		//		return BadRequest("Invalid data.");
		//	}

		//	//var LedgerAccountEntries = _context.Tbl201ChartOfAccounts.Add(chartAccount);

		//	//_context.SaveChanges();

		//	var LedgerAccuntEntry = new Tbl201ChartOfAccount
		//	{
		//		AccountId = chartAccount.AccountId,
		//		ReferenceNo = chartAccount.ReferenceNo,
		//		AccountHead = chartAccount.AccountHead,
		//		AccountGroupId = chartAccount.AccountGroupId,
		//		OpeningBalance = chartAccount.OpeningBalance,
		//		OpeningBalanceDrCr = chartAccount.OpeningBalanceDrCr,
		//		IsDefaultForCash = chartAccount.IsDefaultForCash,
		//		VoucherAbbr = chartAccount.VoucherAbbr,
		//		IsMaintainBillByBill = chartAccount.IsMaintainBillByBill,
		//		NoOfDaysCreditPeriod = chartAccount.NoOfDaysCreditPeriod,
		//		IsEmployeeAllocated = chartAccount.IsEmployeeAllocated,
		//		IsPropertyAllocated = chartAccount.IsPropertyAllocated,
		//		IsEmployeePaymentAc = chartAccount.IsEmployeePaymentAc,
		//		IsLedgerObselete = chartAccount.IsLedgerObselete,
		//		//ContactDetails
		//		AccountBranch = chartAccount.AccountBranch,
		//		AccountSubGroup = chartAccount.AccountSubGroup,
		//		SalesPersonCode = chartAccount.SalesPersonCode,
		//		AccountsContactName = chartAccount.AccountsContactName,
		//		AccountsContactTitle = chartAccount.AccountsContactTitle,
		//		AccountsContactMobile = chartAccount.AccountsContactMobile,
		//		EmailAddress = chartAccount.EmailAddress,
		//		LedgerRemarks = chartAccount.LedgerRemarks,
		//		//BankDetails
		//		BankAccountName = chartAccount.BankAccountName,
		//		BankName = chartAccount.BankName,
		//		BankBranch = chartAccount.BankBranch,
		//		BankAccountNo = chartAccount.BankAccountNo,
		//		BankIban = chartAccount.BankIban,
		//		BankSwiftCode = chartAccount.BankSwiftCode,
		//		//ClientDetails
		//		BillingName = chartAccount.BillingName,
		//		VatregistrationNo = chartAccount.VatregistrationNo,
		//		ClientGroupVatnumber = chartAccount.ClientGroupVatnumber,
		//		ClientOtherIdtype = chartAccount.ClientOtherIdtype,
		//		ClientOtherId = chartAccount.ClientOtherId,
		//		ClientAddressStreet = chartAccount.ClientAddressStreet,
		//		ClientAdditionalStreet = chartAccount.ClientAdditionalStreet,
		//		ClientBuildingNumber = chartAccount.ClientBuildingNumber,
		//		ClientCity = chartAccount.ClientCity,
		//		ClientProvince = chartAccount.ClientProvince,
		//		ClientPostalCode = chartAccount.ClientPostalCode,
		//		ClientNeighborhood = chartAccount.ClientNeighborhood,
		//		//ClientCountryCode = chartAccount.ClientCountryCode,
		//		//Supplier Details
		//		SupplierName = chartAccount.SupplierName,
		//		SupplierVatno = chartAccount.SupplierVatno,
		//		SupplierGroupVatnumber = chartAccount.SupplierGroupVatnumber,
		//		//SupplierOtherIdtype = chartAccount.SupplierOtherIdtype,
		//		//SupplierOtherId = chartAccount.SupplierOtherId,
		//		SupplierAddressStreet = chartAccount.SupplierAddressStreet,
		//		SupplierAdditionalStreet = chartAccount.SupplierAdditionalStreet,
		//		SupplierBuildingNumber = chartAccount.SupplierBuildingNumber,
		//		SupplierCity = chartAccount.SupplierCity,
		//		SupplierProvince = chartAccount.SupplierProvince,
		//		SupplierPostalCode = chartAccount.SupplierPostalCode,
		//		SupplierNeighborhood = chartAccount.SupplierNeighborhood,
		//		//SupplierCountryCode = chartAccount.SupplierCountryCode,
		//		//Billing Details
		//		//BillingName = chartAccount.BillingNameAr
		//		BillingAddress = chartAccount.BillingAddress,
		//		ClientTin = chartAccount.ClientTin,
		//		BillingContactPerson = chartAccount.BillingContactPerson,
		//		BillingPhoneNo = chartAccount.BillingPhoneNo,
		//		BillingFaxNo = chartAccount.BillingFaxNo,
		//		ClientVendorNo = chartAccount.ClientVendorNo,
		//		BillingContactPersonTitle = chartAccount.BillingContactPersonTitle,
		//		BillingBankAccount = chartAccount.BillingBankAccount,
		//		//Obselete details
		//		SupplierAddress = chartAccount.SupplierAddress
		//	};

		//	var LedgerAccountEntries = _context.Tbl201ChartOfAccounts.Add(LedgerAccuntEntry);

		//	_context.SaveChanges();

		//	// You can now work with the 'person' object, which is deserialized from the JSON.
		//	// For example, log or return the data:
		//	return Json(new { success = true, message = "Ledger account inserted successfully" });
		//}

		[HttpPost("InsertOrUpdate")]
		public IActionResult InsertOrUpdate([FromBody] Tbl201ChartOfAccount chartAccount, string AccountGroupID)
		{
			if (chartAccount == null)
			{
				return BadRequest("Invalid data.");
			}

			// Check if the AccountId exists in the database
			var existingAccount = _context.Tbl201ChartOfAccounts
										  .FirstOrDefault(a => a.AccountId == chartAccount.AccountId);



			if (existingAccount != null)
			{
				// Update the existing record
				existingAccount.ReferenceNo = chartAccount.ReferenceNo;
				existingAccount.AccountHead = chartAccount.AccountHead;
				existingAccount.AccountGroupId = AccountGroupID;
				existingAccount.OpeningBalance = chartAccount.OpeningBalance;
				existingAccount.OpeningBalanceDrCr = chartAccount.OpeningBalanceDrCr;
				existingAccount.IsDefaultForCash = chartAccount.IsDefaultForCash;
				existingAccount.VoucherAbbr = chartAccount.VoucherAbbr;
				existingAccount.IsMaintainBillByBill = chartAccount.IsMaintainBillByBill;
				existingAccount.NoOfDaysCreditPeriod = chartAccount.NoOfDaysCreditPeriod;
				existingAccount.IsEmployeeAllocated = chartAccount.IsEmployeeAllocated;
				existingAccount.IsPropertyAllocated = chartAccount.IsPropertyAllocated;
				existingAccount.IsEmployeePaymentAc = chartAccount.IsEmployeePaymentAc;
				existingAccount.IsLedgerObselete = chartAccount.IsLedgerObselete;
				existingAccount.AccountBranch = chartAccount.AccountBranch;
				existingAccount.AccountSubGroup = chartAccount.AccountSubGroup;
				existingAccount.SalesPersonCode = chartAccount.SalesPersonCode;
				existingAccount.AccountsContactName = chartAccount.AccountsContactName;
				existingAccount.AccountsContactTitle = chartAccount.AccountsContactTitle;
				existingAccount.AccountsContactMobile = chartAccount.AccountsContactMobile;
				existingAccount.EmailAddress = chartAccount.EmailAddress;
				existingAccount.LedgerRemarks = chartAccount.LedgerRemarks;
				existingAccount.BankAccountName = chartAccount.BankAccountName;
				existingAccount.AccountHeadArabic = chartAccount.AccountHeadArabic;
				existingAccount.BankName = chartAccount.BankName;
				existingAccount.BankNameAr = chartAccount.BankNameAr;
				existingAccount.BankAccountNameAr = chartAccount.BankAccountNameAr;
				existingAccount.BankBranch = chartAccount.BankBranch;
				existingAccount.BankBranchAr = chartAccount.BankBranchAr;
				existingAccount.BankAccountNo = chartAccount.BankAccountNo;
				existingAccount.BankIban = chartAccount.BankIban;
				existingAccount.BankSwiftCode = chartAccount.BankSwiftCode;
				existingAccount.BillingName = chartAccount.BillingName;
				existingAccount.BillingNameAr = chartAccount.BillingNameAr;
				existingAccount.VatregistrationNo = chartAccount.VatregistrationNo;
				existingAccount.ClientGroupVatnumber = chartAccount.ClientGroupVatnumber;
				existingAccount.ClientOtherIdtype = chartAccount.ClientOtherIdtype;
				existingAccount.ClientOtherId = chartAccount.ClientOtherId;
				existingAccount.ClientAddressStreet = chartAccount.ClientAddressStreet;
				existingAccount.ClientAddressStreetAr = chartAccount.ClientAddressStreetAr;
				existingAccount.ClientAdditionalStreet = chartAccount.ClientAdditionalStreet;
				existingAccount.ClientAdditionalStreetAr = chartAccount.ClientAdditionalStreetAr;
				existingAccount.ClientBuildingNumber = chartAccount.ClientBuildingNumber;
				existingAccount.ClientCity = chartAccount.ClientCity;
				existingAccount.ClientCityAr = chartAccount.ClientCityAr;
				existingAccount.ClientAdditionalNumber = chartAccount.ClientAdditionalNumber;
				existingAccount.ClientProvince = chartAccount.ClientProvince;
				existingAccount.ClientProvinceAr = chartAccount.ClientProvinceAr;

				existingAccount.ClientPostalCode = chartAccount.ClientPostalCode;
				existingAccount.ClientNeighborhood = chartAccount.ClientNeighborhood;
				existingAccount.SupplierName = chartAccount.SupplierName;
				existingAccount.SupplierNameAr = chartAccount.SupplierNameAr;
				existingAccount.SupplierVatno = chartAccount.SupplierVatno;
				existingAccount.SupplierGroupVatnumber = chartAccount.SupplierGroupVatnumber;
				existingAccount.SupplierAddressStreet = chartAccount.SupplierAddressStreet;
				existingAccount.SupplierAddressStreetAr = chartAccount.SupplierAddressStreetAr;
				existingAccount.SupplierAdditionalStreet = chartAccount.SupplierAdditionalStreet;
				existingAccount.SupplierAdditionalStreetAr = chartAccount.SupplierAdditionalStreetAr;
				existingAccount.SupplierBuildingNumber = chartAccount.SupplierBuildingNumber;
				existingAccount.SupplierCity = chartAccount.SupplierCity;
				existingAccount.SupplierCityAr = chartAccount.SupplierCityAr;
				existingAccount.SupplierAdditionalNumber = chartAccount.SupplierAdditionalNumber;

				existingAccount.SupplierProvince = chartAccount.SupplierProvince;
				existingAccount.SupplierProvinceAr = chartAccount.SupplierProvinceAr;
				existingAccount.SupplierPostalCode = chartAccount.SupplierPostalCode;
				existingAccount.SupplierNeighborhood = chartAccount.SupplierNeighborhood;
				existingAccount.SupplierNeighborhoodAr = chartAccount.SupplierNeighborhoodAr;
				existingAccount.BillingAddress = chartAccount.BillingAddress;
				existingAccount.BillingAddressAr = chartAccount.BillingAddressAr;
				existingAccount.ClientTin = chartAccount.ClientTin;
				existingAccount.BillingContactPerson = chartAccount.BillingContactPerson;
				existingAccount.BillingPhoneNo = chartAccount.BillingPhoneNo;
				existingAccount.BillingFaxNo = chartAccount.BillingFaxNo;
				existingAccount.ClientVendorNo = chartAccount.ClientVendorNo;
				existingAccount.BillingContactPersonTitle = chartAccount.BillingContactPersonTitle;
				existingAccount.BillingBankAccount = chartAccount.BillingBankAccount;
				existingAccount.SupplierAddress = chartAccount.SupplierAddress;

				_context.Tbl201ChartOfAccounts.UpdateRange(existingAccount);
				_context.SaveChanges();
				return Json(new { success = true, message = "Ledger account updated successfully" });
			}
			else
			{
				// Insert a new record
				var newAccount = new Tbl201ChartOfAccount
				{
					AccountId = chartAccount.AccountId,
					ReferenceNo = chartAccount.ReferenceNo,
					AccountHead = chartAccount.AccountHead,
					AccountGroupId = chartAccount.AccountGroupId,
					OpeningBalance = chartAccount.OpeningBalance,
					OpeningBalanceDrCr = chartAccount.OpeningBalanceDrCr,
					IsDefaultForCash = chartAccount.IsDefaultForCash,
					VoucherAbbr = chartAccount.VoucherAbbr,
					IsMaintainBillByBill = chartAccount.IsMaintainBillByBill,
					NoOfDaysCreditPeriod = chartAccount.NoOfDaysCreditPeriod,
					IsEmployeeAllocated = chartAccount.IsEmployeeAllocated,
					IsPropertyAllocated = chartAccount.IsPropertyAllocated,
					IsEmployeePaymentAc = chartAccount.IsEmployeePaymentAc,
					IsLedgerObselete = chartAccount.IsLedgerObselete,
					AccountBranch = chartAccount.AccountBranch,
					AccountSubGroup = chartAccount.AccountSubGroup,
					SalesPersonCode = chartAccount.SalesPersonCode,
					AccountsContactName = chartAccount.AccountsContactName,
					AccountsContactTitle = chartAccount.AccountsContactTitle,
					AccountsContactMobile = chartAccount.AccountsContactMobile,
					EmailAddress = chartAccount.EmailAddress,
					LedgerRemarks = chartAccount.LedgerRemarks,
					BankAccountName = chartAccount.BankAccountName,
					BankAccountNameAr = chartAccount.BankAccountNameAr,
					AccountHeadArabic = chartAccount.AccountHeadArabic,
					BankName = chartAccount.BankName,
					BankNameAr = chartAccount.BankNameAr,
					BankBranch = chartAccount.BankBranch,
					BankBranchAr = chartAccount.BankBranchAr,
					BankAccountNo = chartAccount.BankAccountNo,
					BankIban = chartAccount.BankIban,
					BankSwiftCode = chartAccount.BankSwiftCode,
					BillingName = chartAccount.BillingName,
					BillingNameAr = chartAccount.BillingNameAr,
					VatregistrationNo = chartAccount.VatregistrationNo,
					ClientGroupVatnumber = chartAccount.ClientGroupVatnumber,
					ClientOtherIdtype = chartAccount.ClientOtherIdtype,
					ClientOtherId = chartAccount.ClientOtherId,
					ClientAddressStreet = chartAccount.ClientAddressStreet,
					ClientAddressStreetAr = chartAccount.ClientAddressStreetAr,
					ClientAdditionalStreet = chartAccount.ClientAdditionalStreet,
					ClientAdditionalStreetAr = chartAccount.ClientAdditionalStreetAr,
					ClientBuildingNumber = chartAccount.ClientBuildingNumber,
					ClientCity = chartAccount.ClientCity,
					ClientCityAr = chartAccount.ClientCityAr,
					ClientAdditionalNumber = chartAccount.ClientAdditionalNumber,
					ClientProvince = chartAccount.ClientProvince,
					ClientProvinceAr = chartAccount.ClientProvinceAr,
					ClientPostalCode = chartAccount.ClientPostalCode,
					ClientNeighborhood = chartAccount.ClientNeighborhood,
					SupplierName = chartAccount.SupplierName,
					SupplierNameAr = chartAccount.SupplierNameAr,
					SupplierVatno = chartAccount.SupplierVatno,
					SupplierGroupVatnumber = chartAccount.SupplierGroupVatnumber,
					SupplierAddressStreet = chartAccount.SupplierAddressStreet,
					SupplierAddressStreetAr = chartAccount.SupplierAddressStreetAr,
					SupplierAdditionalStreet = chartAccount.SupplierAdditionalStreet,
					SupplierAdditionalStreetAr = chartAccount.SupplierAdditionalStreetAr,
					SupplierBuildingNumber = chartAccount.SupplierBuildingNumber,
					SupplierCity = chartAccount.SupplierCity,
					SupplierCityAr = chartAccount.SupplierCityAr,
					SupplierAdditionalNumber = chartAccount.SupplierAdditionalNumber,
					SupplierProvince = chartAccount.SupplierProvince,
					SupplierProvinceAr = chartAccount.SupplierProvinceAr,

					SupplierPostalCode = chartAccount.SupplierPostalCode,
					SupplierNeighborhood = chartAccount.SupplierNeighborhood,
					SupplierNeighborhoodAr = chartAccount.SupplierNeighborhoodAr,
					BillingAddress = chartAccount.BillingAddress,
					BillingAddressAr = chartAccount.BillingAddressAr,
					ClientTin = chartAccount.ClientTin,
					BillingContactPerson = chartAccount.BillingContactPerson,
					BillingPhoneNo = chartAccount.BillingPhoneNo,
					BillingFaxNo = chartAccount.BillingFaxNo,
					ClientVendorNo = chartAccount.ClientVendorNo,
					BillingContactPersonTitle = chartAccount.BillingContactPersonTitle,
					BillingBankAccount = chartAccount.BillingBankAccount,
					SupplierAddress = chartAccount.SupplierAddress
				};

				_context.Tbl201ChartOfAccounts.Add(newAccount);
				_context.SaveChanges();
				return Json(new { success = true, message = "Ledger account inserted successfully" });
			}
		}

		[HttpGet("GetAccountDetails")]
		public async Task<ActionResult> GetAccountDetails(string accountID)
		{
			try
			{
				// Validate the input
				if (string.IsNullOrEmpty(accountID))
				{
					return BadRequest(new { Message = "AccountID cannot be null or empty." });
				}

				// Fetch account details
				var accountDetails = await _context.Tbl201ChartOfAccounts
					.Where(p => p.AccountId == accountID) // Fixed the incorrect condition
					.Select(i => new
					{
						i.AccountId,
						i.ReferenceNo,
						i.AccountHead,
						i.AccountGroupId,
						i.OpeningBalance,
						i.OpeningBalanceDrCr,
						i.IsDefaultForCash,
						i.VoucherAbbr,
						i.IsMaintainBillByBill,
						i.NoOfDaysCreditPeriod,
						i.IsEmployeeAllocated,
						i.IsPropertyAllocated,
						i.IsEmployeePaymentAc,
						i.IsLedgerObselete,
						i.AccountBranch,
						i.AccountSubGroup,
						i.SalesPersonCode,
						i.AccountsContactName,
						i.AccountsContactTitle,
						i.AccountsContactMobile,
						i.EmailAddress,
						i.LedgerRemarks,
						i.BankAccountName,
						i.BankAccountNameAr,
						i.AccountHeadArabic,
						i.BankName,
						i.BankNameAr,
						i.BankBranch,
						i.BankBranchAr,
						i.BankAccountNo,
						i.BankIban,
						i.BankSwiftCode,
						i.BillingName,
						i.BillingNameAr,
						i.VatregistrationNo,
						i.ClientGroupVatnumber,
						i.ClientOtherIdtype,
						i.ClientOtherId,
						i.ClientAddressStreet,
						i.ClientAddressStreetAr,
						i.ClientAdditionalStreet,
						i.ClientAdditionalStreetAr,
						i.ClientBuildingNumber,
						i.ClientCity,
						i.ClientCityAr,
						i.ClientAdditionalNumber,
						i.ClientProvince,
						i.ClientProvinceAr,
						i.ClientPostalCode,
						i.ClientNeighborhood,
						i.SupplierName,
						i.SupplierNameAr,
						i.SupplierVatno,
						i.SupplierGroupVatnumber,
						i.SupplierAddressStreet,
						i.SupplierAddressStreetAr,
						i.SupplierAdditionalStreet,
						i.SupplierAdditionalStreetAr,
						i.SupplierBuildingNumber,
						i.SupplierCity,
						i.SupplierCityAr,
						i.SupplierAdditionalNumber,
						i.SupplierProvince,
						i.SupplierProvinceAr,
						i.SupplierPostalCode,
						i.SupplierNeighborhood,
						i.SupplierNeighborhoodAr,
						i.BillingAddress,
						i.BillingAddressAr,
						i.ClientTin,
						i.BillingContactPerson,
						i.BillingPhoneNo,
						i.BillingFaxNo,
						i.ClientVendorNo,
						i.BillingContactPersonTitle,
						i.BillingBankAccount,
						i.SupplierAddress
					})
					.ToListAsync(); // Use async to improve performance

				// Check if no data was found
				if (!accountDetails.Any())
				{
					return NotFound(new { Message = "No account details found for the provided AccountID." });
				}

				return Json(new { accountDetails });

			}
			catch (Exception ex)
			{
				// Log the error for debugging (if logging is configured)
				// Example: _logger.LogError(ex, "Error occurred while fetching account details.");

				return StatusCode(500, new { Message = "An unexpected error occurred.", Error = ex.Message });
			}
		}



		#endregion


	}
}
