// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class AllAccountEntriesJoined
{
    public long VoucherEntryNo { get; set; }

    public string AccountHead { get; set; }

    public string AccountHead2 { get; set; }

    public string DrCr { get; set; }

    public string SysRemarks { get; set; }

    public string Expr1 { get; set; }

    public long NoToUpdate { get; set; }
}