// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class AuditingQryStockBalance
{
    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public double OpeningBalance { get; set; }

    public int TotalQtyPurchased { get; set; }

    public decimal AvgCostOfPurchase { get; set; }

    public decimal? CostOfPurchase { get; set; }

    public int TotalQtySold { get; set; }

    public decimal AvgCostOfSales { get; set; }

    public decimal? CostOfSales { get; set; }

    public double BalanceInStock { get; set; }

    public double CostPrice { get; set; }

    public double? CostPrice1 { get; set; }

    public double? TotalCostBalance { get; set; }
}