// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class DqryReceiptRentedStocksNotReturned
{
    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public int BalanceRentedToGetBack { get; set; }

    public string IssueNo { get; set; }

    public string QuotationNo { get; set; }

    public string Unit { get; set; }

    public int? PackOf { get; set; }

    public int? IssueChildSlNo { get; set; }

    public decimal? RentPerDay { get; set; }
}