// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class DqryIssuesSalesMaster2
{
    public string IssueNo { get; set; }

    public DateTime IssueDate { get; set; }

    public byte ModeOfIssueId { get; set; }

    public short? ClientId { get; set; }

    public string ClientName { get; set; }

    public string IssueRemarks { get; set; }

    public string StockNo { get; set; }

    public int? QtyIssued { get; set; }

    public string Unit { get; set; }

    public decimal? PricePerUnit { get; set; }

    public string DetailedDescription { get; set; }

    public int? PackOf { get; set; }

    public string Remarks { get; set; }

    public string StockDescription { get; set; }
}