// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class DqryReceiptHiredMasterBase
{
    public string ReceiptNo { get; set; }

    public DateTime ReceiptDate { get; set; }

    public byte ModeOfReceiptId { get; set; }

    public short? SupplierId { get; set; }

    public string ReceiveRemarks { get; set; }

    public short? IfHiredGivenTo { get; set; }

    public string StockNo { get; set; }

    public int? QtyReceived { get; set; }

    public string Unit { get; set; }

    public decimal? RentPerDay { get; set; }

    public string SupplierName { get; set; }

    public string ClientName { get; set; }

    public string StockDescription { get; set; }
}