// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class Obselete_stpro401_13GetNightShiftOprtDataForUpdatingTSResult
    {
        [StringLength(15)]
        public string EmployeeID { get; set; }
        [StringLength(2147483647)]
        public string OperatorName { get; set; }
        [StringLength(25)]
        public string EquipmentNo { get; set; }
        public DateTime? WorkStartDate { get; set; }
        public DateTime? WorkEndDate { get; set; }
        [StringLength(50)]
        public string WorkingShift { get; set; }
        public decimal? OperatorRegHourlyRate { get; set; }
        public decimal? OperatorOTHourlyRate { get; set; }
        [StringLength(11)]
        public string CurrentStatus { get; set; }
        public DateTime DemobilizedDate { get; set; }
        [StringLength(57)]
        public string BillingDescription { get; set; }
        public int? BillingDescriptionCode { get; set; }
    }
}
