// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10173EmployeeLedgerReceivable
{
    public string EmployeeNo { get; set; }

    public string EmployeeName { get; set; }

    public decimal? Amount { get; set; }

    public string DrCr { get; set; }

    public string VoucherNo { get; set; }

    public string LedgerAccountNo { get; set; }

    public long VoucherEntryId { get; set; }
}