// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101TimeSheetTotalSalaryToMassUpdate
{
    public string EmpId { get; set; }

    public decimal? TotalSalary { get; set; }

    public decimal? OverTimeSalary { get; set; }

    public int? PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public bool IsApproved { get; set; }
}