// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101LoanScheduleToBeDeductedMaster
{
    public string EmpId { get; set; }

    public byte? DeductionMode { get; set; }

    public DateTime? ToBeDeductedOn { get; set; }

    public decimal? AmountScheduled { get; set; }

    public int PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public bool IsApproved { get; set; }
}