// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101150eInvoiceWtEmployeeAmount
{
    public string InvoiceNo { get; set; }

    public DateTime? InvoiceEffectiveDate { get; set; }

    public string EmployeeNo { get; set; }

    public decimal? CalcLineAmount { get; set; }
}