// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10168InvoicedPayrollMaster
{
    public string EmployeeNo { get; set; }

    public string InvoiceNo { get; set; }

    public int? PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public decimal? BillingAmount { get; set; }

    public decimal? HourlyRate { get; set; }

    public decimal? OvertimeRate { get; set; }

    public decimal? BillingRate { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }

    public decimal? InvoicedTotalRegHours { get; set; }

    public decimal? InvoicedTotalOvertimeHours { get; set; }

    public decimal? InvoicedTotalPayableHours { get; set; }
}