// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101Tswednesday
{
    public byte TimeSheetGenTempId { get; set; }

    public string TimeSheetDay { get; set; }

    public decimal? WorkHoursWednesday { get; set; }

    public short? Shift1StartWednesday { get; set; }

    public short? Shift1EndWednesday { get; set; }

    public short? Shift2StartWednesday { get; set; }

    public short? Shift2EndWednesday { get; set; }

    public byte? DaystatusWednesday { get; set; }
}