// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10144InvoiceTotalMaster
{
    public string InvoiceNo { get; set; }

    public decimal? TotalRegHours { get; set; }

    public decimal? TotalOvertimeHours { get; set; }

    public decimal? SplOvertimeHours { get; set; }

    public decimal? BillingRate { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }

    public decimal? AllHoursWithBillingRate { get; set; }

    public decimal? AllHoursWithBiilingAndOtrate { get; set; }

    public decimal? AllHoursWithBiilingAndSplOtrate { get; set; }

    public decimal? TotalRegAndOthours { get; set; }

    public decimal? TotalRegOtandSplOthours { get; set; }
}