// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101000EndOfServiceBenefitCalc
{
    public string EmpId { get; set; }

    public string EmpName { get; set; }

    public decimal? TotalSalary { get; set; }

    public DateTime? JoinDate { get; set; }
}