// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10148PayrollDeductionsWithPosting2
{
    public int PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string EmpId { get; set; }

    public decimal DeductionAmount { get; set; }

    public byte PayrollDeductions { get; set; }

    public string LedgerAccountNo { get; set; }

    public byte? SalaryPostingGroupNo { get; set; }

    public string GroupPayableLedgerNo { get; set; }
}