// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10114EmployeeTimeSheetWithSponsor
{
    public string EmpId { get; set; }

    public DateTime? TimeSheetDate { get; set; }

    public decimal? BasicWorkHours { get; set; }

    public string DayCode { get; set; }

    public string TotalWorkedHours { get; set; }

    public string BonusHours { get; set; }

    public string TotalPayableHours { get; set; }

    public string BasicWorkHours2 { get; set; }

    public DateTime? StartTimeShift1 { get; set; }

    public DateTime? EndTimeShift1 { get; set; }

    public DateTime? StartTimeShift2 { get; set; }

    public DateTime? EndTimeShift2 { get; set; }

    public int? TotalWorkedMinutes { get; set; }

    public string TotalWorkedHours2 { get; set; }

    public decimal? TotalSalary { get; set; }

    public string OvertimeHours { get; set; }

    public short? BasicWorkMinutes { get; set; }

    public int? PayableMinutes2 { get; set; }

    public string PayableHours2 { get; set; }

    public decimal? OverTimeSalary { get; set; }

    public short? BonusMinutes { get; set; }

    public string SponsorId { get; set; }

    public string SponsorName { get; set; }

    public string EmployeeName { get; set; }

    public string VisaPositionTitle { get; set; }
}