// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101154employeeAssignedByDateWtStatus
{
    public string EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string ProjectAssignment { get; set; }

    public string ProjectName { get; set; }

    public int? NoOfDaysAssignedInThisProject { get; set; }

    public string LeaveStatus { get; set; }

    public string TypeOfLeave { get; set; }

    public int? LastAssignedProjectId { get; set; }

    public DateTime? LastAssignedDemobDate { get; set; }

    public string LastAssignedProjectName { get; set; }

    public DateTime? ReportDateInLastAssigned { get; set; }

    public int? NoOfDaysInStandBy { get; set; }

    public bool? IsDiscontinued { get; set; }

    public DateTime? DiscountinuedOn { get; set; }
}