// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101Tstuesday
{
    public byte TimeSheetGenTempId { get; set; }

    public string TimeSheetDay { get; set; }

    public decimal? WorkHoursTuesday { get; set; }

    public short? Shift1StartTuesday { get; set; }

    public short? Shift1EndTuesday { get; set; }

    public short? Shift2StartTuesday { get; set; }

    public short? Shift2EndTuesday { get; set; }

    public byte? DaystatusTuesday { get; set; }
}