// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101TimeSheetMasterTotal2
{
    public string EmpId { get; set; }

    public int? MonthlyTotalHours { get; set; }

    public string TimeSheetMonth { get; set; }

    public string TimeSheetYear { get; set; }

    public string TimeSheetMonthAndYear { get; set; }
}