// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry1018802EmployeesWithContract
{
    public string EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public bool IsCurrentContract { get; set; }

    public bool IsNoTimeSheet { get; set; }

    public decimal HourlyRate { get; set; }

    public decimal OvertimeRate { get; set; }

    public decimal SplOvertimeRate { get; set; }
}