// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101EmployeeViewMaster
{
    public string EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string EmployeeNameAr { get; set; }

    public string CategoryTitle { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public DateTime? EmploymentDate { get; set; }

    public string NationalityEn { get; set; }

    public string VisaPositionTitle { get; set; }

    public string WorkSite { get; set; }

    public string SponsorName { get; set; }

    public string SponsorContactAddress { get; set; }

    public string SponsorMobileNo { get; set; }

    public string SponsorMobileNo2 { get; set; }

    public string ContactPhone { get; set; }

    public string ContactMobile { get; set; }

    public string ContactMobile2 { get; set; }

    public string HomeAddress { get; set; }

    public string HomeCity { get; set; }

    public string HomeCountry { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPersonMobile { get; set; }

    public string ContactPersonKsa { get; set; }

    public string ContactPersonKsamobile { get; set; }

    public string PassportNo { get; set; }

    public string PassportIssuedAt { get; set; }

    public DateTime? PassportIssuedOn { get; set; }

    public DateTime? PassportExpiryDate { get; set; }

    public string NationalId { get; set; }

    public string NationalIdissuedAt { get; set; }

    public DateTime? NationalIdissuedOn { get; set; }

    public DateTime? NationalIdexpiryDate { get; set; }

    public string NationalIdexpiryDateAr { get; set; }

    public byte[] EmployeePicture { get; set; }

    public string DrivingLicenceNo { get; set; }

    public DateTime? DrivingLicenceExpDate { get; set; }

    public string ProfessionalLicenceNo { get; set; }

    public DateTime? ProfessionalLicenceExpDat { get; set; }

    public string EmployeeEmail { get; set; }

    public short? RecordAddedBy { get; set; }

    public DateTime? RecordAddedOn { get; set; }

    public short? RecordModifiedBy { get; set; }

    public DateTime? RecordModifiedOn { get; set; }

    public string AgencyName { get; set; }

    public string AgencyAddress { get; set; }

    public string AgencyCountry { get; set; }

    public string AgencyPhoneNo { get; set; }

    public string Religion { get; set; }

    public bool IsDiscontinued { get; set; }

    public DateTime? DiscountinuedOn { get; set; }

    public string ReasonForDiscontinued { get; set; }

    public string VisaPositionTitleAr { get; set; }

    public string NationalityAr { get; set; }

    public string BloodGroup { get; set; }

    public short? CategoryId { get; set; }

    public string SponsorId { get; set; }

    public short? AgencyId { get; set; }

    public string BankAccountNo { get; set; }

    public string BankName { get; set; }

    public string EmployeeGroup { get; set; }

    public string JobTitle { get; set; }

    public short? CostCentreCode { get; set; }

    public string CostCentreTitle { get; set; }

    public short? DepartmentCode { get; set; }

    public string Department { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public decimal? HiringRate { get; set; }

    public decimal HiringOtrate { get; set; }

    public decimal BillingRate { get; set; }

    public decimal BillingOtrate { get; set; }

    public string Pono { get; set; }

    public string CordinatorName { get; set; }

    public string EmployeeNotes { get; set; }

    public string BankCode { get; set; }

    public string EmployeeReferenceId { get; set; }

    public decimal? GosiSalary { get; set; }

    public byte? HrlevelCode { get; set; }

    public string MedInsuranceNo { get; set; }

    public string MedInsuranceCompany { get; set; }

    public string MedInsuranceScheme { get; set; }

    public string Gosino { get; set; }

    public DateTime? MedInsuranceExpDate { get; set; }

    public short? NationalityId { get; set; }

    public decimal? ContractBasicSalary { get; set; }

    public decimal? ContractHousingAllowance { get; set; }

    public decimal? ContractTransportAllowance { get; set; }

    public decimal? ContractMobileAllowance { get; set; }

    public decimal? ContractFoodAllowance { get; set; }

    public decimal? ContractEducationAllowance { get; set; }

    public decimal? ContractBonusAllowance { get; set; }

    public decimal? ContractOtherAllowance { get; set; }

    public string ProjectName { get; set; }

    public string ProjectId { get; set; }

    public string MobilizedDate { get; set; }

    public byte? SalaryPostingGroupNo { get; set; }

    public byte? EmpJournalPostingGroup { get; set; }

    public string SupervisorName { get; set; }

    public string SupervisorContactNo { get; set; }

    public string SupervisorMobileNo { get; set; }

    public string Competencies { get; set; }

    public string SalaryPostingGroup { get; set; }

    public decimal? ContractTotalRenumerations { get; set; }

    public bool? IsDeductHouseAllowance { get; set; }

    public bool? IsDeductTransAllowance { get; set; }

    public bool? IsDeductMobileAllowance { get; set; }

    public bool? IsDeductOtherAllowance { get; set; }

    public bool? IsDeductSpecialAllowance { get; set; }

    public int? AnnualLeave { get; set; }

    public bool? IsOvertimeAllowed { get; set; }

    public byte? ContractWorkHours { get; set; }

    public bool? IsHourlyRate { get; set; }

    public decimal? HourlyRate { get; set; }

    public decimal? ContractSpecialAllowance { get; set; }

    public decimal? ContractFixedSpecialOvertime { get; set; }

    public string CurrentProjectName { get; set; }

    public string CurrentProjectAssignedOn { get; set; }

    public string CurrentProjectClientName { get; set; }

    public string CurrentProjectSupplierName { get; set; }

    public decimal? CurrentProjectClientRegRate { get; set; }

    public decimal? CurrentProjectClientOtrate { get; set; }

    public decimal? CurrentProjectSupplierRegRate { get; set; }

    public decimal? CurrentProjectSupplierOtrate { get; set; }

    public string CurrentProjectCoordinatorName { get; set; }

    public string CurrentProjectJobTitle { get; set; }

    public int? ProjectGroupId { get; set; }

    public string ProjectGroupName { get; set; }

    public DateTime? QiwaContractStartDate { get; set; }

    public DateTime? QiwaContractEndDate { get; set; }

    public DateTime? HoldDate { get; set; }

    public string HoldingNotes { get; set; }

    public string EmployeeVisaNo { get; set; }

    public DateTime? EmployeeEntryDate { get; set; }

    public string EmployeeEntryPlace { get; set; }

    public string ContractRemarks { get; set; }
}