// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101108voucherEntryWithCostDistributionForBasicSalary
{
    public long VoucherEntryNo { get; set; }

    public string VoucherNo { get; set; }

    public decimal? VoucherAmount { get; set; }

    public decimal? PercOfDistribution { get; set; }

    public string CostAllocationId { get; set; }

    public int? PayrollId { get; set; }

    public string VoucherRefNo { get; set; }

    public decimal? CostAmountOfOt { get; set; }

    public string DrCr { get; set; }

    public DateTime VoucherDate { get; set; }

    public string EntryNarration { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public byte PayrollAdditionId { get; set; }

    public decimal? TotalSalary { get; set; }
}