// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10109935UpdateFoodAllowanceToPayrollAddition
{
    public string EmployeeId { get; set; }

    public int PayrollTemplateAdditions { get; set; }

    public decimal FoodAllowance { get; set; }
}