// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10179LoansGiveBeforeAdateWithDedAmt2
{
    public int LoanId { get; set; }

    public string EmpId { get; set; }

    public string EmployeeName { get; set; }

    public DateTime? LoanAppliedOn { get; set; }

    public DateTime? DeductionsStartFrom { get; set; }

    public decimal? LoanSanctionedAmount { get; set; }

    public decimal? MonthlyDeductionAmount { get; set; }

    public int? DeductedPayrollId { get; set; }

    public DateTime? PayrollMonth { get; set; }
}