// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101102leaveSummaryWtDetail
{
    public string EmpId { get; set; }

    public string EmployeeName { get; set; }

    public short? ContractNo { get; set; }

    public byte? LeaveType { get; set; }

    public string LeaveTypeId { get; set; }

    public int? PaidLeaves { get; set; }

    public int? UnPaidLeaves { get; set; }

    public int? AnnualAllotedLeave { get; set; }
}