// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10101PaySlipTesting
{
    public string EmpId { get; set; }

    public string WorkedMinutes { get; set; }

    public int? D1 { get; set; }

    public int? D2 { get; set; }

    public int? D3 { get; set; }

    public int? D4 { get; set; }

    public int? D5 { get; set; }

    public int? D6 { get; set; }

    public int? D7 { get; set; }

    public int? D8 { get; set; }

    public int? D9 { get; set; }

    public int? D10 { get; set; }

    public int? D11 { get; set; }

    public int? D12 { get; set; }

    public int? D13 { get; set; }

    public int? D14 { get; set; }

    public int? D15 { get; set; }

    public int? D16 { get; set; }

    public int? D17 { get; set; }

    public int? D18 { get; set; }

    public int? D19 { get; set; }

    public int? D20 { get; set; }

    public int? D21 { get; set; }

    public int? D22 { get; set; }

    public int? D23 { get; set; }

    public int? D24 { get; set; }

    public int? D25 { get; set; }

    public int? D26 { get; set; }

    public int? D27 { get; set; }

    public int? D28 { get; set; }

    public int? D29 { get; set; }

    public int? D30 { get; set; }

    public int? D31 { get; set; }

    public decimal? T1 { get; set; }

    public decimal? T2 { get; set; }

    public decimal? T3 { get; set; }

    public decimal? T4 { get; set; }

    public decimal? T5 { get; set; }

    public decimal? T6 { get; set; }

    public decimal? T7 { get; set; }

    public decimal? T8 { get; set; }

    public decimal? T9 { get; set; }

    public decimal? T10 { get; set; }

    public decimal? T11 { get; set; }

    public decimal? T12 { get; set; }

    public decimal? T13 { get; set; }

    public decimal? T14 { get; set; }

    public decimal? T15 { get; set; }

    public decimal? T16 { get; set; }

    public decimal? T17 { get; set; }

    public decimal? T18 { get; set; }

    public decimal? T19 { get; set; }

    public decimal? T20 { get; set; }

    public decimal? T21 { get; set; }

    public decimal? T22 { get; set; }

    public decimal? T23 { get; set; }

    public decimal? T24 { get; set; }

    public decimal? T25 { get; set; }

    public decimal? T26 { get; set; }

    public decimal? T27 { get; set; }

    public decimal? T28 { get; set; }

    public decimal? T29 { get; set; }

    public decimal? T30 { get; set; }

    public decimal? T31 { get; set; }
}