// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10126PayrollCombined
{
    public string EmployeeNo { get; set; }

    public string EmployeeName { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string Type { get; set; }

    public decimal? Amount { get; set; }

    public string Mode { get; set; }

    public string TypeFull { get; set; }

    public short? CategoryId { get; set; }

    public string Sponsor { get; set; }

    public short? AgencyHired { get; set; }

    public string BankAcNo { get; set; }

    public string BankCode { get; set; }

    public decimal? GosiSalary { get; set; }

    public string TransactionRef { get; set; }

    public string IdissuedAt { get; set; }

    public string Idno { get; set; }

    public bool? IsHourlyEmployee { get; set; }

    public decimal? HourlyRate { get; set; }

    public bool? IsBilled { get; set; }

    public decimal? BillingRate { get; set; }

    public string Pono { get; set; }

    public string JobTitle { get; set; }

    public string CostCentreTitle { get; set; }

    public string Department { get; set; }

    public byte Id { get; set; }

    public string CordinatorName { get; set; }

    public short? CordinatorIncharge { get; set; }

    public byte? HrlevelCode { get; set; }

    public decimal ContractMonthlyRenumerations { get; set; }

    public string EmployeeNameAr { get; set; }

    public string CategoryTitle { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public DateTime? EmploymentDate { get; set; }

    public string NationalityEn { get; set; }

    public string VisaPositionTitle { get; set; }

    public string WorkSite { get; set; }

    public string SponsorName { get; set; }

    public string AgencyName { get; set; }

    public string BankName { get; set; }

    public string EmployeeGroup { get; set; }

    public string Gosino { get; set; }

    public string SalaryPostingGroup { get; set; }

    public string ProjectName { get; set; }

    public string ProjectId { get; set; }

    public string MobilizedDate { get; set; }

    public decimal? TotalPayableHours { get; set; }

    public decimal? TotalOvertimeHours { get; set; }

    public decimal? TotalRegHours { get; set; }

    public string ProjectsAssigned { get; set; }
}