// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10146PayrollAdditionsWithPositing
{
    public int PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string EmpId { get; set; }

    public decimal? AdditionAmount { get; set; }

    public byte? PayrollAdditions { get; set; }

    public byte? SalaryPostingGroupNo { get; set; }
}