// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10120EmployeePayrollFoodAllowanceLeaveWoallow
{
    public int? PayrollMasterId { get; set; }

    public string EmpId { get; set; }

    public decimal ThisMonthFoodAllowance { get; set; }
}