// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101104timeSheetWithDetail
{
    public string EmpId { get; set; }

    public string EmployeeName { get; set; }

    public string CategoryTitle { get; set; }

    public string NationalId { get; set; }

    public string EmployeeGroup { get; set; }

    public string JobTitle { get; set; }

    public short? CostCentreCode { get; set; }

    public string CostCentreTitle { get; set; }

    public string Department { get; set; }

    public string ProjectName { get; set; }

    public string ProjectCode { get; set; }

    public DateTime? TimeSheetDate { get; set; }

    public int? RegularMinutes { get; set; }

    public decimal? RegularHours { get; set; }

    public int? OvertimeMinutes { get; set; }

    public decimal? OvertimeHours { get; set; }

    public int? TotalMinutes { get; set; }

    public decimal? TotalHours { get; set; }

    public bool IsHourlyEmployee { get; set; }

    public decimal HourlyRate { get; set; }

    public decimal? RegularSalary { get; set; }

    public decimal? OverTimeSalary { get; set; }

    public decimal? RegAndOtTotal { get; set; }

    public byte? WorkStatus { get; set; }

    public int? PayrollMasterId { get; set; }

    public string TsweekDay { get; set; }

    public int? ProjectId { get; set; }

    public decimal? BillingRate { get; set; }

    public DateTime? PayrollMonth { get; set; }
}