// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry101143payrollInvoicesWtProjectCodeAssigned
{
    public string PayrollInvoiceNo { get; set; }

    public int? ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string ProjectCode { get; set; }
}