// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry10134EmpReimburseBalanceForCostReport
{
    public string LedgerAccountNo { get; set; }

    public string AccountHead { get; set; }

    public string EmployeeNo { get; set; }

    public string EmployeeName { get; set; }

    public string NationalId { get; set; }

    public decimal? TotalPaid { get; set; }

    public decimal? TotalReceived { get; set; }

    public decimal? Balance { get; set; }

    public string AccountGroupId { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }

    public string ReferenceNo { get; set; }

    public string MainGroup { get; set; }

    public string GroupClassification { get; set; }

    public string EmployeeNameWithNo { get; set; }

    public string CategoryTitle { get; set; }

    public string NationalityEn { get; set; }

    public string VisaPositionTitle { get; set; }

    public string WorkSite { get; set; }

    public string EmployeeGroup { get; set; }

    public string JobTitle { get; set; }

    public string CostCentreTitle { get; set; }

    public string Department { get; set; }
}