// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201631EInvoiceToXmlchild01
{
    public string InvoiceNo { get; set; }

    public int? InvoiceChildSlNo { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public decimal? CalcLineAmountBeforeDiscount { get; set; }

    public decimal Discount { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? CalcLineTotalWithTax { get; set; }

    public string CurrencyCode { get; set; }

    public decimal? TaxRateIn100 { get; set; }

    public string TaxCodeInZatca { get; set; }

    public decimal? LineAmountWt10Dec { get; set; }

    public decimal? TaxAmountWt10Dec { get; set; }
}