// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201733vatdifferenceInVoucher
{
    public string ClaimRefNo { get; set; }

    public DateTime? ClaimDate { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TaxAmountInVoucher { get; set; }

    public decimal? Difference { get; set; }
}