// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201RptVoucherWithCost
{
    public long CostAllocationId { get; set; }

    public long VoucherEntryId { get; set; }

    public string CostAllocationUnit { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocDrCr { get; set; }

    public decimal? AmountAllocated { get; set; }

    public string CostAllocRemarks { get; set; }

    public string AccountHeadName { get; set; }

    public string VoucherNo { get; set; }

    public decimal? VoucherAmountFormatted { get; set; }
}