// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201725vatpurchaseChildTotalForEmployeeCost
{
    public string PurchaseVoucherNo { get; set; }

    public decimal? TotalCalcLineAmount { get; set; }

    public string EmployeeNo { get; set; }

    public DateTime? PurchaseEffectiveDate { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string PurchaseLedgerAccountNo { get; set; }
}