// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201639eInvoiceLineItemsValidation
{
    public string InvoiceNo { get; set; }

    public string ItemCode { get; set; }

    public string ItemDescription { get; set; }

    public string ItemDescriptionAr { get; set; }

    public string UnitDesc { get; set; }

    public string UnitDescAr { get; set; }

    public string TaxExemptionReasonCode { get; set; }

    public string TaxCodeInZatca { get; set; }
}