// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry20164SalaryPayableLedgerMaster
{
    public long SalaryPayableId { get; set; }

    public string ReferenceType { get; set; }

    public long? VoucherEntryNo { get; set; }

    public string ReferenceNo { get; set; }

    public string EmployeeNo { get; set; }

    public string EmployeeName { get; set; }

    public decimal? Amount { get; set; }

    public string DrCr { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string VoucherNo { get; set; }

    public DateTime? VoucherDate { get; set; }

    public DateTime? VoucherEffectiveDate { get; set; }

    public decimal? DrAmount { get; set; }

    public decimal? CrAmount { get; set; }

    public decimal? VoucherAmountFormatted { get; set; }

    public string EntryNarration { get; set; }

    public string SalaryPayableLedgerNo { get; set; }

    public string AccountHead { get; set; }

    public string VoucherNoFromVoucherMaster { get; set; }
}