// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201634EInvoiceToXmlchildLineItemsVatbreakDown02
{
    public string InvoiceNo { get; set; }

    public string TaxCodeInZatca { get; set; }

    public decimal? TaxRateIn100 { get; set; }

    public decimal? TotalExclusiveAmount { get; set; }

    public decimal? TaxAmountByTaxRate { get; set; }

    public decimal? TotalExtentionAmount { get; set; }

    public decimal? TotalAllowanceCharges { get; set; }

    public decimal? TotalExclusiveAmountOc { get; set; }

    public decimal? TaxAmountByTaxRateOc { get; set; }

    public decimal? TotalExtentionAmountOc { get; set; }

    public decimal? TotalAllowanceChargesOc { get; set; }

    public string TaxExemptionReasonCode { get; set; }

    public string TaxExemptionReason { get; set; }
}