// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201999vatfinalReturn
{
    public string Vatgroup { get; set; }

    public string DocumentNo { get; set; }

    public DateTime? DocumentDate { get; set; }

    public decimal? DssRevenue { get; set; }

    public decimal? DzrRevenue { get; set; }

    public decimal? DexRevenue { get; set; }

    public decimal? GccRevenue { get; set; }

    public decimal? ExpRevenue { get; set; }

    public decimal? DssSalesTax { get; set; }

    public decimal? DssPurchases { get; set; }

    public decimal? DzrPurchases { get; set; }

    public decimal? DexPurchases { get; set; }

    public decimal? IpcPurchases { get; set; }

    public decimal? RcmPurchases { get; set; }

    public decimal? DssPurTax { get; set; }

    public decimal? IpcPurTax { get; set; }

    public decimal? RcmPurTax { get; set; }

    public decimal? DssCreditNote { get; set; }

    public decimal? DzrCreditNote { get; set; }

    public decimal? DexCreditNote { get; set; }

    public decimal? GccCreditNote { get; set; }

    public decimal? ExpCreditNote { get; set; }

    public decimal? DssTaxCreditNote { get; set; }

    public decimal? DssDebitNote { get; set; }

    public decimal? DzrDebitNote { get; set; }

    public decimal? DexDebitNote { get; set; }

    public decimal? IpcDebitNote { get; set; }

    public decimal? RcmDebitNote { get; set; }

    public decimal? DssDebitTax { get; set; }

    public decimal? IpcDebitTax { get; set; }

    public decimal? RcmDebitTax { get; set; }

    public decimal? Dss15Revenue { get; set; }

    public decimal? Dss15SalesTax { get; set; }

    public decimal? Dss15CreditNote { get; set; }

    public decimal? DssTax15CreditNote { get; set; }

    public decimal? DssPurchases15Perc { get; set; }

    public decimal? IpcPurchases15Perc { get; set; }

    public decimal? RcmPurchases15Perc { get; set; }

    public decimal? DssPurTax15Perc { get; set; }

    public decimal? IpcPurTax15Perc { get; set; }

    public decimal? RcmPurTax15Perc { get; set; }

    public decimal? Dss15perDebitNote { get; set; }

    public decimal? Ipc15perDebitNote { get; set; }

    public decimal? Rcm15perDebitNote { get; set; }

    public decimal? Dss15perDebitTax { get; set; }

    public decimal? Ipc15perDebitTax { get; set; }

    public decimal? Rcm15perDebitTax { get; set; }

    public decimal? Dss10Revenue { get; set; }

    public decimal? Dss10SalesTax { get; set; }

    public decimal? Dss10CreditNote { get; set; }

    public decimal? DssTax10CreditNote { get; set; }

    public decimal? DssPurchases10Perc { get; set; }

    public decimal? IpcPurchases10Perc { get; set; }

    public decimal? RcmPurchases10Perc { get; set; }

    public decimal? DssPurTax10Perc { get; set; }

    public decimal? IpcPurTax10Perc { get; set; }

    public decimal? RcmPurTax10Perc { get; set; }

    public decimal? Dss10perDebitNote { get; set; }

    public decimal? Ipc10perDebitNote { get; set; }

    public decimal? Rcm10perDebitNote { get; set; }

    public decimal? Dss10perDebitTax { get; set; }

    public decimal? Ipc10perDebitTax { get; set; }

    public decimal? Rcm10perDebitTax { get; set; }
}