// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201608vatcreditNoteToCnchild
{
    public string CreditNoteNo { get; set; }

    public decimal? TotalCreditNoteAmount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public string ClientCode { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string RevenueAccount { get; set; }

    public string VatledgerAccount { get; set; }

    public string CostCenterCode { get; set; }

    public string RevenueAccountName { get; set; }

    public string ClientName { get; set; }

    public string CostAllocatedFor { get; set; }

    public string CreditNoteRemarks { get; set; }

    public DateTime? CreditNoteEffectiveDate { get; set; }

    public string InvoiceNo { get; set; }

    public decimal? TotalCreditNoteAmountBhd { get; set; }

    public decimal? TotalTaxAmountBhd { get; set; }

    public decimal? TotalWithTaxBhd { get; set; }
}