// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201652proformaInvoiceReport
{
    public string ProformaInvoiceNo { get; set; }

    public DateTime? ProformaInvoiceDate { get; set; }

    public DateTime? InvoiceEffectiveDate { get; set; }

    public string InvoiceDateAr { get; set; }

    public DateTime? InvoiceDeliveryDate { get; set; }

    public string InvoiceDeliveryDateAr { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string BankAccountNo { get; set; }

    public string BankIban { get; set; }

    public string BankName { get; set; }

    public string BankBranch { get; set; }

    public string BankSwiftCode { get; set; }

    public string BankAccountName { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public string GsdescriptionAr { get; set; }

    public string UoM { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public decimal? UnitsToBill { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public decimal? UnitRate { get; set; }

    public string DetailedDescription { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public string TaxSlab { get; set; }

    public string TaxSlabAr { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TotalInvoiceAmount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public string Pono { get; set; }

    public DateTime? Podate { get; set; }

    public string PodateAr { get; set; }

    public string BillingNameAr { get; set; }

    public string BillingAddressAr { get; set; }

    public string VatregistrationNo { get; set; }

    public decimal? CalcLineTotalWithTax { get; set; }

    public string QuotationNo { get; set; }

    public string DeliveryNoteNos { get; set; }

    public string ReferenceNo { get; set; }

    public string SosreferenceNo { get; set; }

    public string RemarksInEn { get; set; }

    public string RemarksInAr { get; set; }

    public string ClientVatnoAr { get; set; }

    public string CompanyVatno { get; set; }

    public string OurVatnoAr { get; set; }

    public string InvoiceNoAr { get; set; }

    public string BankNameAr { get; set; }

    public string BankAccountNameAr { get; set; }

    public string BankAccountNoAr { get; set; }

    public string ClientVendorNo { get; set; }

    public decimal AdvanceAmount { get; set; }

    public decimal RetentionAmount { get; set; }

    public decimal? BalanceDueAmount { get; set; }

    public string AdvanceText { get; set; }

    public string RetentionText { get; set; }

    public string AdvanceTextAr { get; set; }

    public string RetentionTextAr { get; set; }

    public decimal Discount { get; set; }

    public decimal? CalcLineAmountBeforeDiscount { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalInvoiceAmountBeforeDiscount { get; set; }

    public DateTime? InvoiceStartDate { get; set; }

    public DateTime? InvoiceEndDate { get; set; }

    public DateTime? InvoiceDueDate { get; set; }

    public byte? Currency { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? CalcLineAmountOc { get; set; }

    public decimal? CalcTaxAmountOc { get; set; }

    public decimal? CalcLineAmtB4discOc { get; set; }

    public decimal? UnitRateInOc { get; set; }

    public decimal? DiscountInOc { get; set; }

    public decimal? CalcLineTotalWithTaxInOc { get; set; }

    public decimal? BalanceDueAmountInOc { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencyCodeAr { get; set; }

    public string CurrencyNameAr { get; set; }

    public decimal? TotalInvoiceAmountInOc { get; set; }

    public decimal? TotalTaxAmountInOc { get; set; }

    public decimal? TotalWithTaxInOc { get; set; }

    public decimal? TotalDiscountInOc { get; set; }

    public decimal? TotalInvAmtB4discOc { get; set; }

    public string UnitsToBillInAr { get; set; }

    public string QtyInAr { get; set; }

    public string UnitRateAr { get; set; }

    public string CalcLineAmountAr { get; set; }

    public string CalcTaxAmountAr { get; set; }

    public string CalcLineTotalWithTaxAr { get; set; }

    public string TotalInvoiceAmountAr { get; set; }

    public string TotalTaxAmountAr { get; set; }

    public string TotalWithTaxAr { get; set; }

    public string BalanceDueAmountAr { get; set; }

    public string AdvanceAmountAr { get; set; }

    public string RetentionAmountAr { get; set; }

    public string TaxRateAr { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress1 { get; set; }

    public string CompanyNameAr { get; set; }

    public string CompanyAddress1Ar { get; set; }

    public string CompanyFullAddress { get; set; }

    public string CompanyFullAddressAr { get; set; }

    public string BankBranchAr { get; set; }

    public string InvoicePreparedBy { get; set; }

    public string InvoiceCheckedBy { get; set; }

    public string InvoiceApprovedBy { get; set; }

    public byte[] InvoicePreparedBySign { get; set; }

    public byte[] InvoiceCheckedBySign { get; set; }

    public byte[] InvoiceApprovedBySign { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string UnitDescAr { get; set; }

    public string InvoiceAbbrv { get; set; }

    public string InvoiceNoWtAbbr { get; set; }

    public string AccountId { get; set; }

    public string InvoicePreparedByAr { get; set; }

    public string InvoicePreparedByPosAr { get; set; }

    public string InvoiceCheckedByAr { get; set; }

    public string InvoiceCheckedByPosAr { get; set; }

    public string InvoiceApprovedByAr { get; set; }

    public string InvoiceApprovedByPosAr { get; set; }

    public string InvoicePreparedByPos { get; set; }

    public string InvoiceCheckedByPos { get; set; }

    public string InvoiceApprovedByPos { get; set; }

    public string ProformaInvDateAr { get; set; }

    public string ProformaInvDeliveryDateAr { get; set; }

    public string ProformaInvDueDateAr { get; set; }

    public string PonoAr { get; set; }

    public string ReferenceNoAr { get; set; }

    public string SosReferenceNoAr { get; set; }

    public string ClientVendorNoAr { get; set; }

    public string ProformaInvoiceNoAr { get; set; }

    public string BankIbanar { get; set; }

    public string TaxCodeToDisplay { get; set; }
}