// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201620CreditNotesForSalesReporting
{
    public string CreditNoteNo { get; set; }

    public string CreditNoteDate { get; set; }

    public string InvoiceNo { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? TotalCreditNoteAmount { get; set; }
}