// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry202111costAllocationDescriptionByJournalChildNo
{
    public long JournalChildNo { get; set; }

    public string CostAllocationDescription { get; set; }
}