// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry20105BillsReceivableAgeingView
{
    public string AccountHeadNo { get; set; }

    public string AccountHead { get; set; }

    public string ReferenceNo { get; set; }

    public DateTime? VoucherDate { get; set; }

    public string VoucherRefNo { get; set; }

    public string VoucherNarration { get; set; }

    public decimal ReceivableAmount { get; set; }

    public decimal Received { get; set; }

    public decimal? Balance { get; set; }

    public string AccountGroup { get; set; }

    public DateTime? InvoiceDueDate { get; set; }

    public int OverdueDays { get; set; }

    public decimal? NotOverdue { get; set; }

    public decimal? Less30 { get; set; }

    public decimal? Less30to60 { get; set; }

    public decimal? Less60to90 { get; set; }

    public decimal? Less90to180 { get; set; }

    public decimal? More180 { get; set; }

    public decimal? Less180to365 { get; set; }

    public decimal? More365 { get; set; }

    public string SalesPersonName { get; set; }

    public string InvSalesMan { get; set; }

    public string CostAllocationUnit { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocationMasterGroup { get; set; }

    public string CompanyBranch { get; set; }

    public string DivisionName { get; set; }

    public string SubGroupName { get; set; }

    public string LedgerSubGroupCode { get; set; }

    public string AccountHeadArabic { get; set; }

    public string VatregistrationNo { get; set; }

    public string ClientOtherId { get; set; }

    public short? NoOfDaysCreditPeriod { get; set; }

    public string AccountsContactName { get; set; }

    public string AccountsContactMobile { get; set; }

    public string AccountsContactTitle { get; set; }

    public decimal? ConvertedReceivableAmount { get; set; }
    public decimal? ConvertedReceived { get; set; }
    public decimal? ConvertedBalance { get; set; }
    public string CurrencyName { get; set; }
    public string TransactionCurrencySymbol { get; set; }
    public string CurrencyImage { get; set; }
    

}