// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201SubLedgerReceivablesMaster
{
    public string AccountHeadNo { get; set; }

    public string AccountHead { get; set; }

    public string ReferenceNo { get; set; }

    public DateTime? VoucherDate { get; set; }

    public string VoucherRefNo { get; set; }

    public string VoucherNarration { get; set; }

    public decimal ReceivableAmount { get; set; }

    public decimal Received { get; set; }

    public decimal? Balance { get; set; }

    public string AccountGroup { get; set; }

    public DateTime? InvoiceDueDate { get; set; }

    public string SalesPersonCode { get; set; }

    public string SalesPersonName { get; set; }

    public short? NoOfDaysCreditPeriod { get; set; }

    public int? OverdueDays { get; set; }

    public string VoucherType { get; set; }

    public string AccountGroupId { get; set; }

    public DateTime? VoucherEffectiveDate { get; set; }

    public string AccountBranch { get; set; }

    public string CostAllocationUnit { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocationMasterGroup { get; set; }

    public string VatregistrationNo { get; set; }

    public string BillingName { get; set; }

    public string CompanyBranch { get; set; }

    public DateTime? TransactionDateCr { get; set; }

    public string DivisionName { get; set; }

    public string InvSalesMan { get; set; }

    public string SubGroupName { get; set; }

    public string LedgerSubGroupCode { get; set; }

    public DateTime? VoucherEffectiveMonth { get; set; }

    public string BranchCode { get; set; }

    public string BranchName { get; set; }

    public decimal? InvoiceAmountBeforeRetention { get; set; }

    public decimal? TotalReceivableAmount { get; set; }

    public decimal? BalanceDueWithOutRetention { get; set; }

    public decimal? RetentionReceivable { get; set; }

    public decimal? BalanceDueWithRetention { get; set; }

    public decimal RetentionAmount { get; set; }

    public string SesreferenceNo { get; set; }

    public string ProjectOrContractNo { get; set; }
    public decimal? ConvertedReceivableAmount { get; set; }
    public decimal? ConvertedReceived { get; set; }
    public decimal? ConvertedBalance { get; set; }
}