// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201819creditItemsWtInvoiceCostPrice
{
    public string CreditNoteNo { get; set; }

    public string InvoiceNo { get; set; }

    public string ItemCode { get; set; }

    public decimal? QuantityCredited { get; set; }

    public decimal? UnitsToCredited { get; set; }

    public string UnitDesc { get; set; }

    public decimal? UnitRate { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CreditNoteCostPrice { get; set; }

    public decimal? InvoiceCostPrice { get; set; }

    public string PonoAr { get; set; }

    public byte? UnitRateMethod { get; set; }

    public bool? IsCogsPosted { get; set; }

    public string IsCogsPostedBy { get; set; }

    public DateTime? IsCogsPostedOn { get; set; }

    public string CogsVoucherNo { get; set; }

    public string CostCenterCode { get; set; }

    public bool IsServicesGroup { get; set; }
}