// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry210004purchaseCostPriceInAllUnitsConvertion
{
    public string PurchaseVoucherNo { get; set; }

    public DateTime? PurchaseVoucherDate { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public byte? PurchasedUnitCode { get; set; }

    public string PurchasedUnitType { get; set; }

    public byte? ConvertedUnitCode { get; set; }

    public decimal? UnitConverted { get; set; }

    public decimal? UnitsToBill { get; set; }

    public decimal? QtyPurchased { get; set; }

    public decimal? PurchaseUnitRate { get; set; }

    public decimal? PurchaseLineDiscount { get; set; }

    public decimal? PurchaseLineAmountAfterDiscount { get; set; }

    public decimal? PurchaseCostPrice { get; set; }
}