// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry2019908CustListWithAcc3
{
    public string ClientName { get; set; }

    public string AccountNo { get; set; }

    public long? Sequence { get; set; }

    public long? NewAccountNo { get; set; }

    public string LedgerNo { get; set; }
}