// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201104salaryPaidList
{
    public string ReferenceNo { get; set; }

    public string DrCr { get; set; }

    public decimal? DrAmount { get; set; }

    public string VoucherNo { get; set; }
}