// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201621debtorsWithCollectionReport
{
    public string ReferenceNo { get; set; }

    public string AccountNo { get; set; }

    public string AccountHead { get; set; }

    public decimal? Amount { get; set; }

    public string DrCr { get; set; }

    public decimal? DrAmount { get; set; }

    public decimal? CrAmount { get; set; }

    public decimal? VoucherAmountFormatted { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroup { get; set; }

    public string AccountHeadNo { get; set; }

    public string EntryNarration { get; set; }

    public string SysRemarks { get; set; }

    public DateTime? VoucherDate { get; set; }

    public DateTime? VoucherMonth { get; set; }

    public DateTime? VoucherEffectiveDate { get; set; }

    public DateTime? EffectiveMonth { get; set; }

    public string InvoiceSalesPersonCode { get; set; }

    public string InvoiceSalesPersonName { get; set; }

    public string VoucherNo { get; set; }
}