// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry20139SearchPropertyAllocatedAmount
{
    public long VoucherEntryId { get; set; }

    public decimal? TotalAllocatedAmount { get; set; }
}