// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201710vatsundryDebtorsAndCashAcc
{
    public string AccountId { get; set; }

    public string AccountHead { get; set; }

    public string AccountGroup { get; set; }

    public string AccountsContactName { get; set; }

    public string AccountsContactMobile { get; set; }

    public string AccountsContactTitle { get; set; }

    public string BillingContactPerson { get; set; }

    public string BillingContactPersonTitle { get; set; }

    public string EmailAddress { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string BankAccountNo { get; set; }

    public string BankIban { get; set; }

    public string BankName { get; set; }

    public string BankBranch { get; set; }

    public string BankSwiftCode { get; set; }

    public string BankAccountName { get; set; }

    public string AccountHeadArabic { get; set; }

    public string BillingNameAr { get; set; }

    public string BillingAddressAr { get; set; }

    public string VatregistrationNo { get; set; }

    public string BankNameAr { get; set; }

    public string BankAccountNameAr { get; set; }

    public string ClientVendorNo { get; set; }

    public string BankBranchAr { get; set; }

    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }

    public string ClientGroupVatnumber { get; set; }

    public string ClientOtherIdtype { get; set; }

    public string ClientOtherId { get; set; }

    public string ClientAddressStreet { get; set; }

    public string ClientAddressStreetAr { get; set; }

    public string ClientAdditionalStreet { get; set; }

    public string ClientAdditionalStreetAr { get; set; }

    public string ClientBuildingNumber { get; set; }

    public string ClientAdditionalNumber { get; set; }

    public string ClientCity { get; set; }

    public string ClientCityAr { get; set; }

    public string ClientPostalCode { get; set; }

    public string ClientProvince { get; set; }

    public string ClientProvinceAr { get; set; }

    public string ClientNeighborhood { get; set; }

    public string ClientNeighborhoodAr { get; set; }

    public string ClientCountryCode { get; set; }

    public string ReferenceNo { get; set; }

    public bool? IsLedgerObselete { get; set; }

    public string ClientTin { get; set; }
}