// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry20171SubledgerMatching2
{
    public long? VoucherEntryNo { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? VoucherAmount { get; set; }

    public string Mapping { get; set; }

    public string AccountHead { get; set; }

    public string VoucherNo { get; set; }
}