// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201807vatcreditNoteRegisterMainView
{
    public string CreditNoteNo { get; set; }

    public DateTime? CreditNoteDate { get; set; }

    public string InvoiceNo { get; set; }

    public string ClientCode { get; set; }

    public string ReferenceNo { get; set; }

    public bool? IsSubmitted { get; set; }

    public string SubmittedBy { get; set; }

    public string SubmittedByAr { get; set; }

    public DateTime? SubmittedOn { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedBy { get; set; }

    public string VerifiedByAr { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public string ApprovedByAr { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public string AddedByAr { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string ModifiedByAr { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsPosted { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedOn { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? DomesticStandartRatedRevenue { get; set; }

    public decimal? DomesticZeroRatedRevenue { get; set; }

    public decimal? DomesticExemptedRevenue { get; set; }

    public decimal? GccstandardRatedRevenue { get; set; }

    public decimal? ExportsRevenue { get; set; }

    public decimal? DomesticStandartRatedTax { get; set; }

    public decimal? DomesticZeroRatedTax { get; set; }

    public decimal? DomesticExemptedTax { get; set; }

    public decimal? GccstandardRatedTax { get; set; }

    public decimal? ExportsTax { get; set; }

    public decimal? TotalCreditNoteAmount { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string VatregistrationNo { get; set; }

    public string AccountHead { get; set; }

    public string InvoiceStatus { get; set; }

    public string BranchName { get; set; }

    public string CreditNoteRemarks { get; set; }

    public DateTime? CreditStartDate { get; set; }

    public DateTime? CreditEndDate { get; set; }

    public DateTime? CreditNoteEffectiveDate { get; set; }

    public string RevenueAccount { get; set; }

    public string CostAllocationUnit { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocationMasterGroup { get; set; }

    public decimal? TotalRevenueOf15Perc { get; set; }

    public decimal? TotalTaxOf15Perc { get; set; }

    public string InvoiceUuid { get; set; }

    public short? InvoiceTypeCode { get; set; }

    public string InvoiceTransactionCode { get; set; }

    public string InvoiceTypeCodeSubType { get; set; }

    public bool? IsThirdParty { get; set; }

    public bool? IsNominal { get; set; }

    public bool? IsExport { get; set; }

    public bool? IsSummary { get; set; }

    public bool? IsSelfBilled { get; set; }

    public long? InvoiceCounterValue { get; set; }

    public string InvoiceCurrencyCode { get; set; }

    public string TaxCurrencyCode { get; set; }

    public string SellerGroupVatnumber { get; set; }

    public string SellerOtherIdtype { get; set; }

    public string SellerOtherSellerId { get; set; }

    public string SellerAddressStreet { get; set; }

    public string SellerAddressStreetAr { get; set; }

    public string SellerAdditionalStreet { get; set; }

    public string SellerAdditionalStreetAr { get; set; }

    public string SellerBuildingNumber { get; set; }

    public string SellerAdditionalNumber { get; set; }

    public string SellerCity { get; set; }

    public string SellerCityAr { get; set; }

    public string SellerPostalCode { get; set; }

    public string SellerProvince { get; set; }

    public string SellerProvinceAr { get; set; }

    public string SellerNeighborhood { get; set; }

    public string SellerNeighborhoodAr { get; set; }

    public string SellerCountryCode { get; set; }

    public string SellerVatnumber { get; set; }

    public string SellerName { get; set; }

    public string SellerNameAr { get; set; }

    public string BuyerGroupVatnumber { get; set; }

    public string BuyerOtherIdtype { get; set; }

    public string BuyerOtherId { get; set; }

    public string BuyerAddressStreet { get; set; }

    public string BuyerAddressStreetAr { get; set; }

    public string BuyerAdditionalStreet { get; set; }

    public string BuyerAdditionalStreetAr { get; set; }

    public string BuyerBuildingNumber { get; set; }

    public string BuyerAdditionalNumber { get; set; }

    public string BuyerCity { get; set; }

    public string BuyerCityAr { get; set; }

    public string BuyerPostalCode { get; set; }

    public string BuyerProvince { get; set; }

    public string BuyerProvinceAr { get; set; }

    public string BuyerNeighborhood { get; set; }

    public string BuyerNeighborhoodAr { get; set; }

    public string BuyerCountryCode { get; set; }

    public string BuyerVatnumber { get; set; }

    public string BuyerName { get; set; }

    public string BuyerNameAr { get; set; }

    public byte? PaymentMeansTypeCode { get; set; }

    public string ReasonforIssuanceOfCrn { get; set; }

    public string ReasonforIssuanceOfCrnar { get; set; }

    public string PaymentTerms1 { get; set; }

    public string PaymentTermsAr { get; set; }

    public string BranchCode { get; set; }

    public string BranchName02 { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public DateTime? InvoiceSupplyDate { get; set; }

    public string InvoiceZatcaStatus { get; set; }

    public string EInvoiceSubmittedToZatcaBy { get; set; }

    public DateTime? EInvoiceSubmittedToZatcaOn { get; set; }

    public byte? Currency { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public decimal? RetentionAmount { get; set; }

    public decimal? OtherDeductionAmount { get; set; }

    public byte? CompanyId { get; set; }

    public string ReasonforCreditNote { get; set; }

    public decimal? TotalRevenueOf10Perc { get; set; }

    public decimal? TotalTaxOf10Perc { get; set; }
}