// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry210008itemsWithSalesWithUnitsConverted
{
    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public byte? UnitCode { get; set; }

    public string UnitType { get; set; }

    public decimal? UnitsToBill { get; set; }

    public decimal? SellingLineQty { get; set; }

    public decimal? SellingRate { get; set; }

    public decimal? SellingLineAmountBeforeDiscount { get; set; }

    public decimal SellingLineDiscount { get; set; }

    public decimal? SellingLineAmountAfterDiscount { get; set; }

    public decimal? SellingLineTaxAmount { get; set; }

    public decimal? SellingLineTotalWithTax { get; set; }

    public string TransactionType { get; set; }

    public byte? UnitCodeOfConversion { get; set; }

    public decimal? UnitConverted { get; set; }

    public decimal? SellingPricePerUnit { get; set; }
}