// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry202106journalRegisterReport
{
    public long JournalChildNo { get; set; }

    public string JournalRefNo { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string AccountId { get; set; }

    public string DrCr { get; set; }

    public string EntryNarration { get; set; }

    public decimal? DrAmount { get; set; }

    public decimal? CrAmount { get; set; }

    public string AccountHead { get; set; }

    public string CostAllocationDescription { get; set; }

    public string EmployeeCostDescription { get; set; }

    public string PropertyCostDescription { get; set; }

    public decimal? FormattedAmount { get; set; }

    public decimal? TotalCostAllocated { get; set; }

    public decimal? TotalEmpAllocated { get; set; }

    public decimal? TotalEqpAllocted { get; set; }

    public DateTime? JournalEntryDate { get; set; }

    public string JournalVoucherNarration { get; set; }

    public string JournalCreatedBy { get; set; }

    public DateTime? JournalCreatedOn { get; set; }

    public string JournalModifiedBy { get; set; }

    public DateTime? JournalModifiedOn { get; set; }

    public bool? IsSubmittedToFinance { get; set; }

    public string SubmittedBy { get; set; }

    public DateTime? SubmittedOn { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedBy { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public bool? IsPosted { get; set; }

    public string PostedVoucherNo { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedOn { get; set; }

    public DateTime? JournalEffectiveDate { get; set; }

    public byte? RequesterId { get; set; }

    public decimal? DrAmountTotal { get; set; }

    public decimal? CrAmountTotal { get; set; }

    public decimal? Difference { get; set; }
}