// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201801vatcreditNoteChild
{
    public long CreditNoteChildSlNo { get; set; }

    public string CreditNoteNo { get; set; }

    public string ItemCode { get; set; }

    public string UoM { get; set; }

    public decimal? QuantityCredited { get; set; }

    public decimal? UnitsToCredited { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? UnitRate { get; set; }

    public string DetailedDescription { get; set; }

    public byte? TaxSlabCode { get; set; }

    public decimal? TaxAmount { get; set; }

    public byte? Currency { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? UnitRateInOc { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string BatchNo { get; set; }

    public string DetailedDescriptionAr { get; set; }

    public decimal? LineOrderNo { get; set; }

    public decimal? LineTotal { get; set; }

    public decimal? Discount { get; set; }

    public decimal? IssuedInvoiceCostPrice { get; set; }

    public decimal? CalcLineAmountBeforeDiscount { get; set; }

    public DateTime? ItemServiceStartDate { get; set; }

    public DateTime? ItemServiceEndDate { get; set; }

    public string EmployeeNo { get; set; }

    public string PropertyNo { get; set; }

    public decimal? DiscountInOc { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencyNameAr { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyCodeAr { get; set; }

    public decimal? CalcLineAmountOc { get; set; }

    public decimal? CalcTaxAmountOc { get; set; }

    public decimal? CalcLineAmtB4discOc { get; set; }

    public string TaxExemptionReasonCode { get; set; }

    public string CreditNoteCurrencyNote { get; set; }

    public string CreditNoteCurrencyPoints { get; set; }
}