// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry205015ageingBillsPayable
{
    public string AccountHeadNo { get; set; }

    public string AccountHead { get; set; }

    public string ReferenceNo { get; set; }

    public decimal BillAmount { get; set; }

    public decimal PaidAmount { get; set; }

    public string DrCr { get; set; }

    public decimal? BalanceAmount { get; set; }
}