// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry20111ListOfPandLitem
{
    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }

    public string AccountGroupId { get; set; }

    public string AccountGroup { get; set; }

    public string AccountId { get; set; }

    public string AccountHead { get; set; }

    public bool IsRestricted { get; set; }

    public bool? IsUseInSales { get; set; }

    public bool? IsUsedInPurchase { get; set; }

    public bool? IsProfitLossAccount { get; set; }

    public bool? IsBalanceSheetAccount { get; set; }

    public bool? IsMaintainBillByBill { get; set; }
}