// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry202103journalRegisterTotal
{
    public string JournalRefNo { get; set; }

    public decimal? DrAmountTotal { get; set; }

    public decimal? CrAmountTotal { get; set; }

    public decimal? Difference { get; set; }
}