// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201830ECreditNoteToXmlmaster01
{
    public string CreditNoteNo { get; set; }

    public string InvoiceUuid { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public short? InvoiceTypeCode { get; set; }

    public string InvoiceTransactionCode { get; set; }

    public string RemarksInEn { get; set; }

    public string InvoiceCurrencyCode { get; set; }

    public string TaxCurrencyCode { get; set; }

    public string PurchaseOrderId { get; set; }

    public string ContractId { get; set; }

    public long? InvoiceCounterValue { get; set; }

    public string SellerOtherIdtype { get; set; }

    public string SellerOtherSellerId { get; set; }

    public string SellerAddressStreet { get; set; }

    public string SellerAdditionalStreet { get; set; }

    public string SellerBuildingNumber { get; set; }

    public string SellerAdditionalNumber { get; set; }

    public string SellerCity { get; set; }

    public string SellerPostalCode { get; set; }

    public string SellerProvince { get; set; }

    public string SellerNeighborhood { get; set; }

    public string SellerCountryCode { get; set; }

    public string SellerVatnumber { get; set; }

    public string SellerName { get; set; }

    public string BuyerOtherIdtype { get; set; }

    public string BuyerOtherId { get; set; }

    public string BuyerAddressStreet { get; set; }

    public string BuyerAdditionalStreet { get; set; }

    public string BuyerBuildingNumber { get; set; }

    public string BuyerAdditionalNumber { get; set; }

    public string BuyerCity { get; set; }

    public string BuyerPostalCode { get; set; }

    public string BuyerProvince { get; set; }

    public string BuyerNeighborhood { get; set; }

    public string BuyerCountryCode { get; set; }

    public string BuyerVatnumber { get; set; }

    public string BuyerName { get; set; }

    public DateTime? SupplyDate { get; set; }

    public DateTime? SupplyEndDate { get; set; }

    public byte? PaymentMeansTypeCode { get; set; }

    public string PaymentTerms { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public decimal? RetentionAmount { get; set; }

    public decimal? OtherDeductionAmount { get; set; }

    public byte? CompanyId { get; set; }

    public string CreditNoteInvoiceReferenceNo { get; set; }

    public string CreditNoteReason { get; set; }

    public decimal? TotalAllDeductionsAmount { get; set; }

    public string SellerNameAr { get; set; }

    public string SellerNeighborhoodAr { get; set; }

    public string SellerCityAr { get; set; }

    public string SellerAddressStreetAr { get; set; }

    public string BuyerNameAr { get; set; }

    public string BuyerNeighborhoodAr { get; set; }

    public string BuyerCityAr { get; set; }

    public string BuyerAddressStreetAr { get; set; }
}