// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry201SubLedgerReceivablesWtRetention
{
    public string AccountHeadNo { get; set; }

    public string AccountHead { get; set; }

    public string ReferenceNo { get; set; }

    public decimal? InvoiceAmountBeforeRetention { get; set; }

    public decimal RetentionAmount { get; set; }

    public decimal TotalReceivableAmount { get; set; }

    public decimal Received { get; set; }

    public decimal? BalanceDueWithOutRetention { get; set; }

    public decimal? RetentionReceivable { get; set; }

    public decimal? BalanceDueWithRetention { get; set; }
}