// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry20134VoucherEntriesOfBalanceSheetItem
{
    public long VoucherEntryNo { get; set; }

    public string VoucherNo { get; set; }

    public DateTime VoucherDate { get; set; }

    public string AccountHead { get; set; }

    public string AccountHeadName { get; set; }

    public decimal? VoucherAmount { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroup { get; set; }

    public bool? IsBalanceSheetAccount { get; set; }
}