// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry2019909InvoiceTrans01
{
    public int SlNo { get; set; }

    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public DateTime? DueDate { get; set; }

    public string LedgerNo { get; set; }

    public string ClientName { get; set; }

    public string Remarks { get; set; }

    public decimal? InvoiceAmount { get; set; }
}