// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry209001goodsCombinedMaster
{
    public string DocumentNo { get; set; }

    public DateTime? DocumentDate { get; set; }

    public string Gscode { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? DocumentQty { get; set; }

    public decimal? DocumentLineUnitPrice { get; set; }

    public decimal Discount { get; set; }

    public decimal? DocumentLineTotalAmount { get; set; }

    public string TransactionType { get; set; }

    public decimal? FormattedQty { get; set; }
}