// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40603equipmentRequestChildWtTotal
{
    public string EquipmentRequestNo { get; set; }

    public decimal? TotalRequestCost { get; set; }

    public int? NoOfItems { get; set; }
}