// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40301equipmentTsmaster
{
    public int TimeSheetMasterId { get; set; }

    public DateTime? TimeSheetMonth { get; set; }

    public string PropertyNo { get; set; }

    public int? TimeSheetMonthId { get; set; }

    public string PropertyType { get; set; }

    public string PropertyGroup { get; set; }

    public string PropertySuppliedBy { get; set; }

    public string OperatorName { get; set; }

    public decimal? OperatorRate { get; set; }

    public DateTime? HiredOn { get; set; }

    public string PropertyDescription { get; set; }

    public string PropertyCategoryName { get; set; }

    public string Brand { get; set; }

    public string PlateNo { get; set; }

    public bool? IsNoTimeSheet { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public decimal? BuyingRatePerHour { get; set; }

    public string InvoiceSummNo { get; set; }

    public string SupplierCode { get; set; }

    public string SupplierName { get; set; }

    public string SupplierPono { get; set; }

    public string SupplierRefNo { get; set; }

    public string SupplierTssummaryNo { get; set; }

    public bool? IsSupplierTimeSheetApproved { get; set; }

    public string SuppTimesheetApprovedBy { get; set; }

    public DateTime? SuppTimesheetApprovedOn { get; set; }

    public bool? IsSupplierTimesheetSubmitted { get; set; }

    public string SuppTimesheetSubmittedBy { get; set; }

    public DateTime? SuppTimesheetSubmittedOn { get; set; }

    public decimal? BuyingRatePerDay { get; set; }

    public decimal? BuyingRatePerMonth { get; set; }

    public string ProjectMasterCode { get; set; }

    public string ProjectDescription { get; set; }

    public string SupplierAccountLedgerNo { get; set; }

    public string GatePassNo { get; set; }

    public string ClientSite { get; set; }

    public decimal? Deductions { get; set; }
}