// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40002propertyMaintenance
{
    public string ServiceSheetNo { get; set; }

    public DateTime? ServiceDate { get; set; }

    public string PropertyNo { get; set; }

    public string ServicedBy { get; set; }

    public string Complaint { get; set; }

    public string PropertyBroughtBy { get; set; }

    public string Location { get; set; }

    public string OperatorName { get; set; }

    public string ServiceStatus { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string OperatorContactNo { get; set; }

    public string Project { get; set; }

    public string ServiceOrderType { get; set; }
}