// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40302equipmentTswtClientRate
{
    public string PropertyNo { get; set; }

    public int? TimeSheetMasterId { get; set; }

    public int? TotalMinutesWorked { get; set; }

    public decimal? TotalHoursWorked { get; set; }

    public decimal ClientRatePerHour { get; set; }

    public string ClientCode { get; set; }

    public string PropertyIssueNo { get; set; }

    public decimal? TotalClientRegHours { get; set; }

    public decimal? TotalClientOthours { get; set; }

    public decimal ClientOtratePerHour { get; set; }
}