// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40702propertyTimesheetSummary
{
    public string PropertyNo { get; set; }

    public DateTime? TimeSheetDate { get; set; }

    public string ClientCode { get; set; }

    public string ClientName { get; set; }

    public string PropertySummInvoiceNo { get; set; }

    public decimal? ClientRatePerHour { get; set; }

    public decimal? ClientOtratePerHour { get; set; }

    public byte? WorkStatus { get; set; }

    public string DayCode { get; set; }

    public string DayDescription { get; set; }

    public decimal? ClientRegHoursPerDay { get; set; }

    public decimal? ClientRegAmountPerDay { get; set; }

    public decimal? ClientOthoursPerDay { get; set; }

    public decimal? ClientOtamountPerDay { get; set; }

    public decimal? ClientAmountPerDay { get; set; }

    public decimal? SuppRegHoursPerDay { get; set; }

    public decimal? SuppRegAmountPerDay { get; set; }

    public decimal? SuppOthoursPerDay { get; set; }

    public decimal? SuppOtamountPerDay { get; set; }

    public decimal? SuppTotalPerDay { get; set; }

    public decimal? SuppRatePerHour { get; set; }

    public decimal? SuppOtratePerHour { get; set; }
}