// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40303equipmentTswtSupplierTotalAmt
{
    public string PropertyNo { get; set; }

    public int? TimeSheetMasterId { get; set; }

    public decimal TotalHoursWorked { get; set; }

    public decimal SupplierRatePerHour { get; set; }

    public decimal? TotalAmount { get; set; }

    public string SupplierCode { get; set; }

    public decimal TotalSupplierRegHours { get; set; }

    public decimal TotalSupplierOthours { get; set; }

    public decimal? TotalSupplierRegAmount { get; set; }

    public decimal? TotalSupplierOtamount { get; set; }

    public decimal SuppOtratePerHour { get; set; }
}