// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40140PropertyHireNoteReport
{
    public string DeliveryNoteNo { get; set; }

    public DateTime? MobilizedDate { get; set; }

    public DateTime? DemobilizedDate { get; set; }

    public string PropertyNo { get; set; }

    public decimal? QuantityIssued { get; set; }

    public decimal? UnitRate { get; set; }

    public string UoM { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public byte? UnitRateMethod { get; set; }

    public string PropertyDetailedDescription { get; set; }

    public string IssueNotes { get; set; }

    public string ClientCode { get; set; }

    public string QuotationNo { get; set; }

    public string OrderNo { get; set; }

    public string ClientPono { get; set; }

    public DateTime? ClientPodate { get; set; }

    public string PropertyIssueRemarks { get; set; }

    public string Salesman { get; set; }

    public string TransportedBy { get; set; }

    public string DriversName { get; set; }

    public string DriversId { get; set; }

    public string VehicleNo { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public byte? DeliverySignatory { get; set; }

    public string Attention { get; set; }

    public string ClientContactNo { get; set; }

    public string ClientContactEmail { get; set; }

    public string Operator { get; set; }

    public string MeterReading { get; set; }

    public string MeterReadingHours { get; set; }

    public string ClientName { get; set; }

    public string ClientNameAr { get; set; }

    public string ClientAddress { get; set; }

    public string ClientSite { get; set; }

    public string PropertyDescription { get; set; }

    public string ModelType { get; set; }

    public string Weight { get; set; }

    public string OperatorName { get; set; }

    public string Specifications { get; set; }

    public string Brand { get; set; }

    public string PlateNo { get; set; }

    public string DoorNo { get; set; }

    public string ChassisNo { get; set; }

    public string Color { get; set; }

    public string Capacity { get; set; }

    public string Model { get; set; }

    public string Year { get; set; }

    public long? PropertyIssueChildSlNo { get; set; }

    public byte? CompanyBranch { get; set; }

    public string GatePassNo { get; set; }

    public string ProjectId { get; set; }

    public byte? DeliveryType { get; set; }

    public string OffHireNoteRefNo { get; set; }

    public string ReasonOffHire { get; set; }

    public bool? IsReturnOfHire { get; set; }

    public string ReasonofReturnOfHire { get; set; }

    public bool? IsDemoblizationChargedToClient { get; set; }

    public decimal? DemobilizationCharges { get; set; }

    public string DemobilizationRemarks { get; set; }

    public bool? IsEquipmentReplaced { get; set; }

    public string ReplacementPropertyNo { get; set; }

    public string ReplacementDeliveryNoteNo { get; set; }

    public bool? IsReplacementChargedToClient { get; set; }

    public decimal? ReplacementCharges { get; set; }

    public string ReplacementRemarks { get; set; }

    public bool? IsEquipmentReturnedWithDamage { get; set; }

    public bool? IsDamageChargedToClient { get; set; }

    public decimal? EquipmentDamageCharges { get; set; }

    public string EquipmentDamageRemarks { get; set; }

    public string TransportingBackVehicleNo { get; set; }

    public string TransportingBackVehicleDriverName { get; set; }

    public string TransportingBackVehicleDriverId { get; set; }

    public string OffhireMeterReading { get; set; }

    public string OffhireMeterReadingHours { get; set; }

    public string OffhireDetailsAddedBy { get; set; }

    public DateTime? OffhireDetailsAddedOn { get; set; }

    public string OffhireDetailsModifiedBy { get; set; }

    public DateTime? OffhireDetailsModifiedOn { get; set; }

    public string ReasonOfReplacement { get; set; }

    public string OffHireNoteNo { get; set; }

    public string TransportationBackBy { get; set; }
}