// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40115PropertyInvoiceReportWtOtlineSeperated
{
    public string InvoiceNo { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string PropertyNo { get; set; }

    public string PropertyDescriptionWithOperator { get; set; }

    public decimal? UnitToBill { get; set; }

    public int? UnitRateMethod { get; set; }

    public decimal? UnitRate { get; set; }

    public string UoM { get; set; }
}