// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry40001propertyOperator
{
    public long PropertyOperatorCode { get; set; }

    public string EquipmentNo { get; set; }

    public byte? PropertyOperatorTypeId { get; set; }

    public string OperatorType { get; set; }

    public string EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string OperatorName { get; set; }

    public string OperatorName2 { get; set; }

    public DateTime? WorkStartDate { get; set; }

    public DateTime? WorkEndDate { get; set; }

    public string WorkingShift { get; set; }

    public string OperatorRemarks { get; set; }

    public string EnteredBy { get; set; }

    public DateTime? EnteredOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public decimal? OperatorRegHourlyRate { get; set; }

    public decimal? OperatorOthourlyRate { get; set; }
}