// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry671001stockTransactionsMasterForReport
{
    public string DocumentNo { get; set; }

    public long? DocumentSlNo { get; set; }

    public string Gscode { get; set; }

    public decimal? DocumentQty { get; set; }

    public string DocumentUnitType { get; set; }

    public byte? DocumentUnitRateMethod { get; set; }

    public decimal? DocumentUnitPrice { get; set; }

    public string ConvertedUnitType { get; set; }

    public byte? ConvertedUnitRateMethod { get; set; }

    public decimal UnitsConverted { get; set; }

    public decimal? ConvertedQty { get; set; }

    public decimal? ConvertedUnitPrice { get; set; }

    public string Transactions { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string TypeOfEntry { get; set; }

    public decimal? TransactionTotal { get; set; }

    public DateTime? InventoryEffectiveDate { get; set; }
}