// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry661StockMasterAvgCost
{
    public string ReferenceNo { get; set; }

    public DateTime? TransactionDate { get; set; }

    public string Gscode { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? StockReceivedQty { get; set; }

    public decimal? StockReceivedUnitPrice { get; set; }

    public string Transactions { get; set; }

    public decimal? TransactionTotal { get; set; }

    public int TransactionOrderNo { get; set; }

    public long? ReceiptChildSlNo { get; set; }
}