// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60107quotationIssuedByMprno
{
    public string Mprno { get; set; }

    public int? NoOfQuotations { get; set; }

    public decimal? NetQuotedAmount { get; set; }

    public decimal? NetQuotedWithTax { get; set; }
}