// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60513materialReceiptsByMprno
{
    public string MprnoClubbed02 { get; set; }

    public string ReceiptNo { get; set; }

    public string ReceiptDate { get; set; }
}