// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60510balanceToBillByPurchaseOrder
{
    public string Pono { get; set; }

    public string Gscode { get; set; }

    public decimal OrderedQty { get; set; }

    public decimal BilledQty { get; set; }

    public decimal? BalanceToBill { get; set; }
}