// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry664MtlStockMasterAvgCost03WtDetail
{
    public string StockCode { get; set; }

    public string StockDescription { get; set; }

    public string StockGroup { get; set; }

    public string TransactionType { get; set; }

    public DateTime? TransactionDate { get; set; }

    public decimal? Quantity { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? Total { get; set; }

    public string DocumentNo { get; set; }

    public bool IsServicesGroup { get; set; }
}