// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60315deliveryNoteToJournalDebitEntry
{
    public string DeliveryNoteNo { get; set; }

    public string ExpensesLedgerNo { get; set; }

    public decimal? CostPriceTotal { get; set; }

    public string GsgroupName { get; set; }

    public string CostAllocationUnitId { get; set; }
}