// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60512materialReceiptWtMprno
{
    public string ReceiptNo { get; set; }

    public string Mprno { get; set; }

    public string Rfqno { get; set; }

    public string OurPurchaseOrderNo { get; set; }

    public string MprnoClubbed { get; set; }

    public string MprnoClubbed02 { get; set; }
}