// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry671001stockInvoiceEntries01
{
    public string InvoiceNo { get; set; }

    public int? InvoiceChildSlNo { get; set; }

    public string Gscode { get; set; }

    public decimal QuantityInvoiced { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal IssuedInvoiceCostPrice { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public decimal ItemDiscount { get; set; }

    public DateTime? InventoryEffectiveDate { get; set; }
}