// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60610purchaseRequestQuotedQty
{
    public string Mprno { get; set; }

    public string Gscode { get; set; }

    public decimal? TotalQuotedQty { get; set; }
}