// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry60005inventoryUploadsUomWtSlNo
{
    public long? Sequence { get; set; }

    public string GsuomDesc { get; set; }
}