// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry70004projectVisit
{
    public long SiteVisitId { get; set; }

    public string ProjectId { get; set; }

    public string VisitType { get; set; }

    public byte? SiteVisitedBy { get; set; }

    public DateTime? SiteVisitOn { get; set; }

    public DateTime? ReminderOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ProjectDescription { get; set; }

    public string SiteVisitBy { get; set; }
}