// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry70009aProjectEquipmentPo
{
    public string Pono { get; set; }

    public DateTime? Podate { get; set; }

    public string SupplierRefNo { get; set; }

    public string SupplierCode { get; set; }

    public string SupplierName { get; set; }

    public int? NoOfItems { get; set; }

    public decimal? TotalAmount { get; set; }

    public string ProjectMasterCode { get; set; }

    public string ProjectDescription { get; set; }
}