// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry70003projectsEmployee
{
    public long EmpSiteAssignmentId { get; set; }

    public string EmpId { get; set; }

    public int? ProjectId { get; set; }

    public string EnteredBy { get; set; }

    public DateTime? EnteredOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public DateTime? MobilizedDate { get; set; }

    public DateTime? DemobilizedDate { get; set; }

    public string ProjectDescription { get; set; }

    public string ProjectMasterNo { get; set; }

    public string EmployeeName { get; set; }

    public string NationalId { get; set; }

    public string ContactMobile { get; set; }

    public string EmployeeGroup { get; set; }

    public string JobTitle { get; set; }

    public string CostCentreTitle { get; set; }

    public string Department { get; set; }

    public decimal? HiringRate { get; set; }

    public string ProjectCode { get; set; }
}