// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Qry70005projectEquipment
{
    public string PropertyIssueNo { get; set; }

    public string PropertyNo { get; set; }

    public decimal? QuantityIssued { get; set; }

    public string Operator { get; set; }

    public string PropertyDetailedDescription { get; set; }

    public DateTime? PropertyIssuedDate { get; set; }

    public DateTime? DemobilizedDate { get; set; }

    public string OrderNo { get; set; }

    public string ClientPono { get; set; }

    public string ProjectId { get; set; }

    public string PropertyDescription { get; set; }
}