// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class RqryOpeningBalance
{
    public string ReceiptNo { get; set; }

    public int ReceiveChildSlNo { get; set; }

    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public int? QtyReceived { get; set; }

    public string Unit { get; set; }

    public int? PackOf { get; set; }
}