// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class RqryContractDatabase
{
    public int ContractId { get; set; }

    public string ContractName { get; set; }

    public string ContractIncharges { get; set; }

    public string ContractSite { get; set; }

    public string ContractDuration { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public bool? IsContractCompleted { get; set; }
}