// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20101TrialBalanceResult
    {
        public string AccountHead { get; set; }
        public string AccountHeadName { get; set; }
        public decimal? VoucherAmountFormatted { get; set; }
        public string AccountGroup { get; set; }
        public string MasterGroup { get; set; }
        public string TransactionsFull { get; set; }
        public string AccountHeadArabic { get; set; }
        public string AccountGroupAr { get; set; }
        public string MasterGroupAr { get; set; }
    }
}
