// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20106GetExpenseClaimDifferenceResult
    {
        [StringLength(20)]
        public string ClaimRefNo { get; set; }
        public decimal? DifferenceInPosting { get; set; }
    }
}
