// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20108ExpensesInfoGraphResult
    {
        public decimal? Amount { get; set; }
        public string AccountGroup { get; set; }
        [StringLength(15)]
        public string MasterGroup { get; set; }
        [StringLength(50)]
        public string MasterGroupID { get; set; }
    }
}
