// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20113BalanceSheet_ByGroupResult
    {
        [StringLength(50)]
        public string MasterGroupCategory { get; set; }
        [StringLength(50)]
        public string MasterGroupID { get; set; }
        [StringLength(200)]
        public string MasterGroup { get; set; }
        [StringLength(10)]
        public string AccountGroupID { get; set; }
        [StringLength(200)]
        public string AccountGroup { get; set; }
        public decimal? AccountBalance { get; set; }
        [StringLength(10)]
        public string AccountHead { get; set; }
        [StringLength(200)]
        public string AccountHeadName { get; set; }
        [Column("MasterOrderNo", TypeName = "decimal(18,0)")]
        public decimal? MasterOrderNo { get; set; }
        [StringLength(2147483647)]
        public string AccountHeadArabic { get; set; }
        [StringLength(200)]
        public string AccountGroupAr { get; set; }
        [StringLength(200)]
        public string MasterGroupAr { get; set; }
        [StringLength(50)]
        public string MasterGroupCategoryAr { get; set; }
        [Column("AccountGroupOrderNo", TypeName = "decimal(18,0)")]
        public decimal? AccountGroupOrderNo { get; set; }
    }
}
