// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20102GetAccountBalanceResult
    {
        [StringLength(10)]
        public string AccountHead { get; set; }
        public decimal? Amount { get; set; }
    }
}
