// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20123AssetsDepreciationMasterReportResult
    {
        [StringLength(2147483647)]
        public string AccountHead { get; set; }
        [StringLength(2147483647)]
        public string AccountName { get; set; }
        [StringLength(2147483647)]
        public string AccountGroup { get; set; }
        [StringLength(2147483647)]
        public string MasterGroup { get; set; }
        public decimal? BalanceAmount { get; set; }
        [StringLength(2147483647)]
        public string AccountHeadArabic { get; set; }
        [StringLength(2147483647)]
        public string AccountGroupAr { get; set; }
        [StringLength(2147483647)]
        public string MasterGroupAr { get; set; }
        public DateTime? VoucherDate { get; set; }
        [StringLength(2147483647)]
        public string TransactionFull { get; set; }
        public int? NoOfDaysForDep { get; set; }
        public int? NoOfDaysThisYear { get; set; }
        public byte LifeSpanInYears { get; set; }
        [Column("DepreciationPercentage", TypeName = "decimal(12,7)")]
        public decimal? DepreciationPercentage { get; set; }
        [Column("DepreciationAmount", TypeName = "decimal(38,6)")]
        public decimal? DepreciationAmount { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public DateTime? AssetFinalDate { get; set; }
        public int? FinalYearDays { get; set; }
        public int? NoOfDaysForDepreciationActual { get; set; }
        public decimal? ValueOfProperty { get; set; }
    }
}
