// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20102GetAccountDetailsResult
    {
        [StringLength(50)]
        public string MasterGroupID { get; set; }
        [StringLength(10)]
        public string AccountGroupID { get; set; }
        public bool IsUseInReconciliation { get; set; }
        public bool IsUseInSales { get; set; }
        public bool IsUsedInPurchase { get; set; }
        public bool IsProfitLossAccount { get; set; }
        public bool IsBalanceSheetAccount { get; set; }
        public bool IsMaintainBillByBill { get; set; }
    }
}
