// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp20101TrialBalanceReportArResult
    {
        [StringLength(2147483647)]
        public string AccountHead { get; set; }
        [StringLength(2147483647)]
        public string AccountName { get; set; }
        [StringLength(2147483647)]
        public string AccountGroup { get; set; }
        [StringLength(2147483647)]
        public string MasterGroup { get; set; }
        public decimal? Op_Bal { get; set; }
        public decimal? TransDebit { get; set; }
        public decimal? TransCredit { get; set; }
        [StringLength(2147483647)]
        public string AccountHeadArabic { get; set; }
        [StringLength(2147483647)]
        public string AccountGroupAr { get; set; }
        [StringLength(2147483647)]
        public string MasterGroupAr { get; set; }
        [Column("ChartOfAccountsOrder", TypeName = "decimal(18,0)")]
        public decimal? ChartOfAccountsOrder { get; set; }
        [Column("AccountGroupOrderNo", TypeName = "decimal(18,0)")]
        public decimal? AccountGroupOrderNo { get; set; }
    }
}
