// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp30101GetQuoteGrossAmountResult
    {
        public string QuoteNo { get; set; }
        public decimal? GrossAmount { get; set; }
    }
}
