// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp40109Eqp_Cost_ClientTimesheetResult
    {
        [StringLength(25)]
        public string PropertyNo { get; set; }
        [StringLength(50)]
        public string ClientCode { get; set; }
        [StringLength(2147483647)]
        public string ClientName { get; set; }
        [StringLength(100)]
        public string PropertySummInvoiceNo { get; set; }
        public decimal? ClientRatePerHour { get; set; }
        public decimal? ClientOTRatePerHour { get; set; }
        [StringLength(50)]
        public string DayDescription { get; set; }
        [Column("ClientRegHoursTotal", TypeName = "decimal(38,2)")]
        public decimal? ClientRegHoursTotal { get; set; }
        [Column("ClientRegAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? ClientRegAmountTotal { get; set; }
        [Column("ClientOTHoursTotal", TypeName = "decimal(38,2)")]
        public decimal? ClientOTHoursTotal { get; set; }
        [Column("ClientOTAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? ClientOTAmountTotal { get; set; }
        [Column("ClientAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? ClientAmountTotal { get; set; }
        public int? NoOfDays { get; set; }
    }
}
