// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp40111Eqp_Cost_RevenueAllocatedResult
    {
        [StringLength(50)]
        public string PropertyNo { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public decimal? RevenueAllocated { get; set; }
        [StringLength(10)]
        public string PropertyAllocDrCr { get; set; }
        [StringLength(50)]
        public string VoucherNo { get; set; }
        [StringLength(10)]
        public string AccountHead { get; set; }
        public DateTime? VoucherDate { get; set; }
        [StringLength(200)]
        public string AccountHeadName { get; set; }
        [StringLength(2147483647)]
        public string VoucherNarration { get; set; }
    }
}
