// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class sp40108EquipmentRevenueCostReportResult
    {
        [StringLength(50)]
        public string PropertyNo { get; set; }
        [Column("ClientRegHoursTotal", TypeName = "decimal(38,2)")]
        public decimal? ClientRegHoursTotal { get; set; }
        [Column("ClientRegAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? ClientRegAmountTotal { get; set; }
        [Column("ClientOTHoursTotal", TypeName = "decimal(38,2)")]
        public decimal? ClientOTHoursTotal { get; set; }
        [Column("ClientOTAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? ClientOTAmountTotal { get; set; }
        [Column("ClientAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? ClientAmountTotal { get; set; }
        [Column("SuppRegHoursTotal", TypeName = "decimal(38,2)")]
        public decimal? SuppRegHoursTotal { get; set; }
        [Column("SuppRegAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? SuppRegAmountTotal { get; set; }
        [Column("SuppOTHoursTotal", TypeName = "decimal(38,2)")]
        public decimal? SuppOTHoursTotal { get; set; }
        [Column("SuppOTAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? SuppOTAmountTotal { get; set; }
        [Column("SuppAmountTotal", TypeName = "decimal(38,6)")]
        public decimal? SuppAmountTotal { get; set; }
        [Column("InvoicedAmountTotal", TypeName = "decimal(38,7)")]
        public decimal? InvoicedAmountTotal { get; set; }
        public decimal? RevenueAllocTotal { get; set; }
        public decimal? ExpensesAllocTotal { get; set; }
        public byte? PropertyCategory { get; set; }
        [StringLength(50)]
        public string PlateNo { get; set; }
        [StringLength(50)]
        public string DoorNo { get; set; }
        [StringLength(50)]
        public string ChassisNo { get; set; }
        [StringLength(2147483647)]
        public string PropertyDescription { get; set; }
        [StringLength(2147483647)]
        public string PropertyType { get; set; }
    }
}
