// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class stpro101_13GetDataForUpdatingEmployeeTimeSheetResult
    {
        [StringLength(20)]
        public string EmpID { get; set; }
        public int? ProjectID { get; set; }
        public DateTime? MobilizedDate { get; set; }
        public DateTime DemobilizedDate { get; set; }
        [StringLength(11)]
        public string CurrentStatus { get; set; }
        [StringLength(57)]
        public string BillingDescription { get; set; }
        public int? BillingDescriptionCode { get; set; }
    }
}
