// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class StPro804_CheckWorkDayStatusResult
    {
        [StringLength(4)]
        public string DayCode2 { get; set; }
        [StringLength(5)]
        public string DayCode { get; set; }
    }
}
