// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class StProAccountLedgerResult
    {
        [StringLength(50)]
        public string VoucherNo { get; set; }
        public DateTime? VoucherDate { get; set; }
        [StringLength(2147483647)]
        public string VoucherRefNo { get; set; }
        [StringLength(2147483647)]
        public string VoucherNarration { get; set; }
        [StringLength(2147483647)]
        public string VoucherEnteredBy { get; set; }
        public DateTime? VoucherEnteredOn { get; set; }
        [StringLength(2147483647)]
        public string VoucherVerifiedBy { get; set; }
        public DateTime? VoucherVerifiedOn { get; set; }
        [StringLength(2147483647)]
        public string VoucherApprovedBy { get; set; }
        public DateTime? VoucherApprovedOn { get; set; }
        public long? VoucherEntryNo { get; set; }
        [StringLength(10)]
        public string AccountHead { get; set; }
        [StringLength(200)]
        public string AccountHeadName { get; set; }
        [StringLength(50)]
        public string DrCr { get; set; }
        public decimal? DrAmount { get; set; }
        public decimal? CrAmount { get; set; }
        public decimal? VoucherAmountFormatted { get; set; }
        [StringLength(2147483647)]
        public string EntryNarration { get; set; }
        [StringLength(200)]
        public string AccountGroup { get; set; }
        [StringLength(200)]
        public string MasterGroup { get; set; }
        [StringLength(50)]
        public string VoucherType { get; set; }
        [StringLength(2147483647)]
        public string SysRemarks { get; set; }
        [StringLength(2147483647)]
        public string VoucherModifiedBy { get; set; }
        public DateTime? VoucherModifiedOn { get; set; }
        [StringLength(2147483647)]
        public string BillNo { get; set; }
        public DateTime? BillDate { get; set; }
        [StringLength(2147483647)]
        public string BillPaidTo { get; set; }
        [StringLength(2147483647)]
        public string BillRemarks { get; set; }
        public DateTime? VoucherEffectiveDate { get; set; }
        [StringLength(2147483647)]
        public string AccountHeadArabic { get; set; }
        [StringLength(2147483647)]
        public string ReferenceNote { get; set; }
    }
}
