// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class StProTrialBalanceResult
    {
        public string VoucherNo { get; set; }
        public DateTime? VoucherDate { get; set; }
        public long? VoucherEntryNo { get; set; }
        public string AccountHead { get; set; }
        public string AccountHeadName { get; set; }
        public string DrCr { get; set; }
        public decimal? DrAmount { get; set; }
        public decimal? CrAmount { get; set; }
        public decimal? VoucherAmountFormatted { get; set; }
        public string AccountGroup { get; set; }
        public string MasterGroup { get; set; }
        public string VoucherType { get; set; }
        public string Transactions { get; set; }
        public string MonthYear { get; set; }
        public int? MonthNumber { get; set; }
        public string Category { get; set; }
        public string VoucherRefNo { get; set; }
        public string VoucherNarration { get; set; }
        public string EntryNarration { get; set; }
        public string SysRemarks { get; set; }
    }
}
