// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class stpro401_26GetEquipTodaySalesResult
    {
        [Column("TodaySales", TypeName = "decimal(38,7)")]
        public decimal? TodaySales { get; set; }
        [StringLength(15)]
        public string BalanceText { get; set; }
    }
}
