// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class stproStockCardResultsResult
    {
        [StringLength(6)]
        public string StockNo { get; set; }
        public DateTime TransactionDate { get; set; }
        [StringLength(13)]
        public string Particulars { get; set; }
        public int? Quantity { get; set; }
        [StringLength(50)]
        public string ModeOfTransaction { get; set; }
        [StringLength(8)]
        public string TransactionDescription { get; set; }
    }
}
