// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities
{
    public partial class StProPaySlipEmployeesTimeSheetSubOnlyOTResult
    {
        public string EmpID { get; set; }
        public string BonusMinutes { get; set; }
        [Column("D1", TypeName = "decimal(18,2)")]
        public decimal? D1 { get; set; }
        [Column("D2", TypeName = "decimal(18,2)")]
        public decimal? D2 { get; set; }
        [Column("D3", TypeName = "decimal(18,2)")]
        public decimal? D3 { get; set; }
        [Column("D4", TypeName = "decimal(18,2)")]
        public decimal? D4 { get; set; }
        [Column("D5", TypeName = "decimal(18,2)")]
        public decimal? D5 { get; set; }
        [Column("D6", TypeName = "decimal(18,2)")]
        public decimal? D6 { get; set; }
        [Column("D7", TypeName = "decimal(18,2)")]
        public decimal? D7 { get; set; }
        [Column("D8", TypeName = "decimal(18,2)")]
        public decimal? D8 { get; set; }
        [Column("D9", TypeName = "decimal(18,2)")]
        public decimal? D9 { get; set; }
        [Column("D10", TypeName = "decimal(18,2)")]
        public decimal? D10 { get; set; }
        [Column("D11", TypeName = "decimal(18,2)")]
        public decimal? D11 { get; set; }
        [Column("D12", TypeName = "decimal(18,2)")]
        public decimal? D12 { get; set; }
        [Column("D13", TypeName = "decimal(18,2)")]
        public decimal? D13 { get; set; }
        [Column("D14", TypeName = "decimal(18,2)")]
        public decimal? D14 { get; set; }
        [Column("D15", TypeName = "decimal(18,2)")]
        public decimal? D15 { get; set; }
        [Column("D16", TypeName = "decimal(18,2)")]
        public decimal? D16 { get; set; }
        [Column("D17", TypeName = "decimal(18,2)")]
        public decimal? D17 { get; set; }
        [Column("D18", TypeName = "decimal(18,2)")]
        public decimal? D18 { get; set; }
        [Column("D19", TypeName = "decimal(18,2)")]
        public decimal? D19 { get; set; }
        [Column("D20", TypeName = "decimal(18,2)")]
        public decimal? D20 { get; set; }
        [Column("D21", TypeName = "decimal(18,2)")]
        public decimal? D21 { get; set; }
        [Column("D22", TypeName = "decimal(18,2)")]
        public decimal? D22 { get; set; }
        [Column("D23", TypeName = "decimal(18,2)")]
        public decimal? D23 { get; set; }
        [Column("D24", TypeName = "decimal(18,2)")]
        public decimal? D24 { get; set; }
        [Column("D25", TypeName = "decimal(18,2)")]
        public decimal? D25 { get; set; }
        [Column("D26", TypeName = "decimal(18,2)")]
        public decimal? D26 { get; set; }
        [Column("D27", TypeName = "decimal(18,2)")]
        public decimal? D27 { get; set; }
        [Column("D28", TypeName = "decimal(18,2)")]
        public decimal? D28 { get; set; }
        [Column("D29", TypeName = "decimal(18,2)")]
        public decimal? D29 { get; set; }
        [Column("D30", TypeName = "decimal(18,2)")]
        public decimal? D30 { get; set; }
        [Column("D31", TypeName = "decimal(18,2)")]
        public decimal? D31 { get; set; }
        [Column("T1", TypeName = "decimal(18,2)")]
        public decimal? T1 { get; set; }
        [Column("T2", TypeName = "decimal(18,2)")]
        public decimal? T2 { get; set; }
        [Column("T3", TypeName = "decimal(18,2)")]
        public decimal? T3 { get; set; }
        [Column("T4", TypeName = "decimal(18,2)")]
        public decimal? T4 { get; set; }
        [Column("T5", TypeName = "decimal(18,2)")]
        public decimal? T5 { get; set; }
        [Column("T6", TypeName = "decimal(18,2)")]
        public decimal? T6 { get; set; }
        [Column("T7", TypeName = "decimal(18,2)")]
        public decimal? T7 { get; set; }
        [Column("T8", TypeName = "decimal(18,2)")]
        public decimal? T8 { get; set; }
        [Column("T9", TypeName = "decimal(18,2)")]
        public decimal? T9 { get; set; }
        [Column("T10", TypeName = "decimal(18,2)")]
        public decimal? T10 { get; set; }
        [Column("T11", TypeName = "decimal(18,2)")]
        public decimal? T11 { get; set; }
        [Column("T12", TypeName = "decimal(18,2)")]
        public decimal? T12 { get; set; }
        [Column("T13", TypeName = "decimal(18,2)")]
        public decimal? T13 { get; set; }
        [Column("T14", TypeName = "decimal(18,2)")]
        public decimal? T14 { get; set; }
        [Column("T15", TypeName = "decimal(18,2)")]
        public decimal? T15 { get; set; }
        [Column("T16", TypeName = "decimal(18,2)")]
        public decimal? T16 { get; set; }
        [Column("T17", TypeName = "decimal(18,2)")]
        public decimal? T17 { get; set; }
        [Column("T18", TypeName = "decimal(18,2)")]
        public decimal? T18 { get; set; }
        [Column("T19", TypeName = "decimal(18,2)")]
        public decimal? T19 { get; set; }
        [Column("T20", TypeName = "decimal(18,2)")]
        public decimal? T20 { get; set; }
        [Column("T21", TypeName = "decimal(18,2)")]
        public decimal? T21 { get; set; }
        [Column("T22", TypeName = "decimal(18,2)")]
        public decimal? T22 { get; set; }
        [Column("T23", TypeName = "decimal(18,2)")]
        public decimal? T23 { get; set; }
        [Column("T24", TypeName = "decimal(18,2)")]
        public decimal? T24 { get; set; }
        [Column("T25", TypeName = "decimal(18,2)")]
        public decimal? T25 { get; set; }
        [Column("T26", TypeName = "decimal(18,2)")]
        public decimal? T26 { get; set; }
        [Column("T27", TypeName = "decimal(18,2)")]
        public decimal? T27 { get; set; }
        [Column("T28", TypeName = "decimal(18,2)")]
        public decimal? T28 { get; set; }
        [Column("T29", TypeName = "decimal(18,2)")]
        public decimal? T29 { get; set; }
        [Column("T30", TypeName = "decimal(18,2)")]
        public decimal? T30 { get; set; }
        [Column("T31", TypeName = "decimal(18,2)")]
        public decimal? T31 { get; set; }
        public int? AgencyID { get; set; }
        public string AgencyName { get; set; }
        public string EmployeeName { get; set; }
        public string VisaPositionTitle { get; set; }
        public string WorkSite { get; set; }
        [Column("HourlyRate", TypeName = "decimal(18,2)")]
        public decimal? HourlyRate { get; set; }
        public decimal? AbsentDeductionAmount { get; set; }
        [Column("AbsentDays", TypeName = "decimal(18,2)")]
        public decimal? AbsentDays { get; set; }
        public decimal? BillingRate { get; set; }
        public string CostCentreTitle { get; set; }
        public long? PayrollMasterID { get; set; }
    }
}
