// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl10105ImportOwnEmp
{
    public string EmpId { get; set; }

    public string MobileNo { get; set; }

    public string IqamaNo { get; set; }

    public string IqamaExpAr { get; set; }

    public string MukeemExpAr { get; set; }

    public string NationalityText { get; set; }

    public string PassportNo { get; set; }

    public DateTime? PassportExpDate { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public DateTime? InsuranceExpDate { get; set; }

    public string GosiExpDate { get; set; }

    public string Pplocation { get; set; }

    public DateTime? DrivingLicExpDt { get; set; }

    public string Remarks { get; set; }

    public string EmpOldNo { get; set; }
}