// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl101PaymentType
{
    public byte PaymentTypeId { get; set; }

    public string PaymentType { get; set; }
}