// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl10117EmployeeLeaveByDateTempTable
{
    public string EmpId { get; set; }

    public byte? LeaveType { get; set; }

    public DateTime? LeaveDate { get; set; }

    public int? LeaveTakenId { get; set; }
}