// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl10107PayrollInvoiceMaster
{
    public string PayrollInvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public DateTime? InvoiceEffectiveDate { get; set; }

    public DateTime? InvoiceStartDate { get; set; }

    public DateTime? InvoiceEndDate { get; set; }

    public string ClientLedgerNo { get; set; }

    public string QuotationNo { get; set; }

    public decimal? Discount { get; set; }

    public decimal? Transportation { get; set; }

    public string DeliveryNoteNos { get; set; }

    public string Remarks { get; set; }

    public byte? SalesPerson { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string Pono { get; set; }

    public string ReferenceNo { get; set; }

    public string SosreferenceNo { get; set; }

    public string ClientReferenceName { get; set; }

    public string ClientContactNo { get; set; }

    public string ClientEmail { get; set; }

    public bool? IsSubmitted { get; set; }

    public string SubmittedBy { get; set; }

    public DateTime? SubmittedOn { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedBy { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public DateTime? Podate { get; set; }

    public string InvAdditionsText { get; set; }

    public string InvDeductionText { get; set; }

    public string VatinvoiceNo { get; set; }

    public byte? VatapplicableRate { get; set; }

    public string BadgeNo { get; set; }

    public string Dthno { get; set; }

    public string Drssno { get; set; }

    public string SesreferenceNo { get; set; }

    public byte? InvoicingMode { get; set; }

    public string EmployeeNo { get; set; }

    public int? JobNo { get; set; }

    public short? DeptWorked { get; set; }

    public short? VisaPositionNo { get; set; }

    public string ClientCcno { get; set; }

    public string TransportationKm { get; set; }

    public string ContractNo { get; set; }
}