// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl10120EmpAssignedInProjectTemp
{
    public long? EmpSiteAssignmentId { get; set; }

    public string EmpId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? MobilizedDate { get; set; }

    public DateTime? DemobilizedDate { get; set; }

    public string BillingDescription { get; set; }

    public string IsNeededTimesheet { get; set; }

    public string LastManpowerPayrollNo { get; set; }
}