// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl10102WeekSerial
{
    public short WeekSlNo { get; set; }

    public string WeekDayName { get; set; }

    public byte? WeekCountNo { get; set; }
}