// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl101Contract
{
    public int ContractSlNo { get; set; }

    public string EmpId { get; set; }

    public short? ContractNo { get; set; }

    public string ContractRevision { get; set; }

    public string PositionNo { get; set; }

    public byte? ContractPeriod { get; set; }

    public byte? ContractStatus { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public decimal? BasicSalary { get; set; }

    public decimal? FoodAllowance { get; set; }

    public decimal? TransportAllowance { get; set; }

    public decimal? HousingAllowance { get; set; }

    public decimal? EducationAllowance { get; set; }

    public decimal? MobileAllowance { get; set; }

    public int? AnnualLeave { get; set; }

    public bool? IsOvertimeAllowed { get; set; }

    public decimal? OtherAllowance { get; set; }

    public bool? IsCurrentContract { get; set; }

    public byte? RevisionNo { get; set; }

    public DateTime? RevisionDate { get; set; }

    public byte? TimeSheetTemplate { get; set; }

    public bool? IsAbsentPenalty { get; set; }

    public decimal? AbsentPenaltyAmount { get; set; }

    public byte? ContractWorkHours { get; set; }

    public bool? IsHourlyRate { get; set; }

    public decimal? HourlyRate { get; set; }

    public bool? IsDeductFoodAllowance { get; set; }

    public bool? IsEmpBilling { get; set; }

    public decimal? BillingRate { get; set; }

    public string Pono { get; set; }

    public short? CordinatorIncharge { get; set; }

    public bool? IsNoTimeSheet { get; set; }

    public decimal? OvertimeRate { get; set; }

    public decimal? SplOvertimeRate { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public decimal? SupplierCommissionRate { get; set; }

    public decimal? ClientCommissionRate { get; set; }

    public bool? IsDeductHouseAllowance { get; set; }

    public bool? IsDeductTransAllowance { get; set; }

    public bool? IsDeductMobileAllowance { get; set; }

    public bool? IsDeductOtherAllowance { get; set; }

    public decimal? OvertimePercentage { get; set; }

    public bool? IsUse30DaysForOvertime { get; set; }

    public bool? IsDeductSpecialAllowance { get; set; }

    public decimal? GosiDeductionAmount { get; set; }

    public DateTime? ContractPreparedDate { get; set; }

    public decimal? OtherDeductionAmount { get; set; }

    public DateTime? QiwaContractStartDate { get; set; }

    public DateTime? QiwaContractEndDate { get; set; }
}