// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl10109SalaryPostingMapping
{
    public int SalaryPostingMappingNo { get; set; }

    public byte? SalaryPostingGroupNo { get; set; }

    public byte? SalaryAdditionsId { get; set; }

    public string LedgerAccountNo { get; set; }
}