// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl101EmployeeLoanSchedule
{
    public int LoanScheduleId { get; set; }

    public int? LoanId { get; set; }

    public string EmpId { get; set; }

    public byte? DeductionMode { get; set; }

    public DateTime? ToBeDeductedOn { get; set; }

    public decimal? AmountScheduled { get; set; }

    public int? DeductedPayrollId { get; set; }

    public string DeductedRentalEmpPayrollNo { get; set; }
}