// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl101Agency
{
    public short AgencyCode { get; set; }

    public string AgencyName { get; set; }

    public string AgencyAddress { get; set; }

    public string AgencyCountry { get; set; }

    public string AgencyPhoneNo { get; set; }

    public string AgencyContactPerson { get; set; }

    public string AgencyContactPersonTitle { get; set; }

    public string AgencyEmail { get; set; }
}