// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl20184SalaryPayableByDateReport
{
    public long VoucherEntryNo { get; set; }

    public string ReferenceNo { get; set; }

    public string EmployeeNo { get; set; }

    public decimal? Amount { get; set; }

    public string DrCr { get; set; }

    public string VoucherNo { get; set; }

    public DateTime? VoucherDate { get; set; }

    public decimal? DrAmount { get; set; }

    public decimal? CrAmount { get; set; }

    public decimal? VoucherAmountFormatted { get; set; }
}