// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl30108QuotationChild
{
    public int QuoteChildId { get; set; }

    public string QuoteNo { get; set; }

    public string ItemCode { get; set; }

    public int? QuotedQuantity { get; set; }

    public string QuotedUom { get; set; }

    public int? QuotedPackingUnit { get; set; }

    public decimal? QuotedPrice { get; set; }

    public string DeliveryTerms { get; set; }

    public string QuoteRemarks { get; set; }
}