// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl40129PropertySalesOrderMaster
{
    public string SalesOrderNo { get; set; }

    public DateTime? SalesOrderDate { get; set; }

    public int? ClientId { get; set; }

    public string ClientPono { get; set; }

    public DateTime? ClientPodate { get; set; }

    public string QuoteNo { get; set; }

    public DateTime? QuoteDate { get; set; }

    public string ClientRefNo { get; set; }

    public string Attention { get; set; }

    public string SubjectTitle { get; set; }

    public byte? TypeOfQuote { get; set; }

    public string QuoteType { get; set; }

    public decimal? QuoteTransport { get; set; }

    public decimal? QuoteDiscount { get; set; }

    public byte? PaymentTerms { get; set; }

    public byte? DeliveryPeriod { get; set; }

    public byte? DeliveryTerms { get; set; }

    public string QuoteValidity { get; set; }

    public string PreparedBy { get; set; }

    public DateTime? PreparedOn { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string Rfqcode { get; set; }

    public string ClientContactNo { get; set; }

    public string ClientContactEmail { get; set; }

    public string ClientCode { get; set; }

    public string QuotationSummary { get; set; }

    public byte? QuoteSignatory { get; set; }

    public string QuoteIntro { get; set; }

    public byte? TypeOfRequest { get; set; }

    public byte? ModeOfRequest { get; set; }

    public string AdditionsText { get; set; }

    public string DiscountsText { get; set; }

    public DateTime? QuoteDueDate { get; set; }

    public string Project { get; set; }

    public string SalesPersonCode { get; set; }

    public bool? IsVerified { get; set; }

    public bool? IsApproved { get; set; }

    public bool? IsSubmitted { get; set; }


    public byte? CompanyBranch { get; set; }

    public string PaymentMode { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public string CreditPeriod { get; set; }

    public decimal? CreditLimit { get; set; }

    public string DeliveryLocation { get; set; }

    public string DeliveryContactPerson { get; set; }

    public string DeliveryContactMobile { get; set; }

    public string DeliveryContactEmail { get; set; }

    public string OrderDuration { get; set; }

    public string MobChargesBy { get; set; }

    public string CustomsChargesBy { get; set; }

    public string ApprovedCafattch { get; set; }

    public byte? SopreparedBySignatory { get; set; }

    public string DeliveryRegion { get; set; }

    public DateTime? OrderExpiryDate { get; set; }

    public byte? SoverifiedSign { get; set; }

    public byte? SoapprovedSign { get; set; }

    public string RefNo { get; set; }

    public string VerifiedBy { get; set; }
    public string ClientName { get; set; }



}