// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl40101PropertyMaster
{
    public string PropertyNo { get; set; }

    public byte? PropertyCategory { get; set; }

    public string Specifications { get; set; }

    public string Brand { get; set; }

    public string PlateNo { get; set; }

    public string DoorNo { get; set; }

    public string ChassisNo { get; set; }

    public string Color { get; set; }

    public string Capacity { get; set; }

    public string Model { get; set; }

    public string Year { get; set; }

    public byte? Ownership { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public byte? PurchasedAs { get; set; }

    public decimal? BuyingRatePerHour { get; set; }

    public decimal? BuyingRatePerDay { get; set; }

    public decimal? BuyingRatePerMonth { get; set; }

    public decimal? SellingRatePerHour { get; set; }

    public decimal? SellingRatePerDay { get; set; }

    public decimal? SellingRatePerMonth { get; set; }

    public byte? PropertyCondition { get; set; }

    public bool? IsFinanced { get; set; }

    public short? FinancedFrom { get; set; }

    public decimal? ValueOfProperty { get; set; }

    public decimal? InitialDownPayment { get; set; }

    public decimal? InitialDocCharges { get; set; }

    public decimal? MonthlyInstallment { get; set; }

    public byte? NoOfInstallments { get; set; }

    public DateTime? InstallmentStartDate { get; set; }

    public DateTime? InstallmentEndDate { get; set; }

    public decimal? FinalInstallment { get; set; }

    public string DepreciationMethod { get; set; }

    public byte? LifeSpanOfProperty { get; set; }

    public decimal? ScrapValueOfProperty { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsDiscontinued { get; set; }

    public DateTime? DiscontinuedOn { get; set; }

    public string DiscontinuedRemarks { get; set; }

    public string PropertyDescription { get; set; }

    public string ModelType { get; set; }

    public string Weight { get; set; }

    public string LxWxH { get; set; }

    public string PlatformHeight { get; set; }

    public string OperatingCapacity { get; set; }

    public string OperatingWeight { get; set; }

    public string AddlSpec1 { get; set; }

    public string AddlSpec2 { get; set; }

    public string AddlSpec3 { get; set; }

    public string AddlField1 { get; set; }

    public string AddlField2 { get; set; }

    public string AddlField3 { get; set; }

    public string PurchasedFrom { get; set; }

    public string PurchasedAs2 { get; set; }

    public string PropertyCondition2 { get; set; }

    public string HiringMode { get; set; }

    public DateTime? HiredOn { get; set; }

    public int? HiredFrom { get; set; }

    public bool? IsOperatorIncluded { get; set; }

    public int? OperatorCode { get; set; }

    public decimal? OperatorRate { get; set; }

    public bool? IsReturned { get; set; }

    public DateTime? ReturnedOn { get; set; }

    public string ReturnedRemarks { get; set; }

    public byte? PropertyGroupId { get; set; }

    public string OperatorName { get; set; }

    public string FinancedBy2 { get; set; }

    public int? PropertyType { get; set; }

    public string OperatorContactMobile { get; set; }

    public string OperatorContactMobile2 { get; set; }

    public string OperatorNationalId { get; set; }

    public string EngineNo { get; set; }

    public string AlternatorNo { get; set; }

    public string KvaorKw { get; set; }

    public string Location { get; set; }

    public bool? IsBreakDown { get; set; }

    public string OwnershipText { get; set; }

    public string SupplierCode { get; set; }

    public string PropertyRemarks { get; set; }

    public string PropertyCertification { get; set; }

    public string PropertyPwas { get; set; }

    public string PropertyAttachment { get; set; }

    public decimal? BuyingOtratePerHour { get; set; }

    public byte[] PropertyImage { get; set; }

    public decimal? BuyingRatePerWeek { get; set; }

    public string SupplierPono { get; set; }

    public string SupplierRefNo { get; set; }

    public decimal? SupplierMobRate { get; set; }

    public decimal? SupplierDemobRate { get; set; }

    public short? AgreementHours { get; set; }
}