// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl40103PropertyQuoteMaster
{
    public string QuoteNo { get; set; }

    public DateTime? QuoteDate { get; set; }

    public int? ClientId { get; set; }

    public string ClientRefNo { get; set; }

    public string Attention { get; set; }

    public string SubjectTitle { get; set; }

    public byte? SalesPerson { get; set; }

    public byte? TypeOfQuote { get; set; }

    public string QuoteType { get; set; }

    public decimal? QuoteTransport { get; set; }

    public decimal? QuoteDiscount { get; set; }

    public byte? PaymentTerms { get; set; }

    public byte? DeliveryPeriod { get; set; }

    public byte? DeliveryTerms { get; set; }

    public string QuoteValidity { get; set; }

    public string PreparedBy { get; set; }

    public DateTime? PreparedOn { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string Rfqcode { get; set; }

    public string ClientContactNo { get; set; }

    public string ClientContactEmail { get; set; }

    public string ClientCode { get; set; }

    public string QuotationSummary { get; set; }

    public byte? QuoteSignatory { get; set; }

    public bool? IsIncludeSeal { get; set; }

    public string QuoteIntro { get; set; }

    public byte? TypeOfRequest { get; set; }

    public byte? ModeOfRequest { get; set; }

    public string AdditionsText { get; set; }

    public string DiscountsText { get; set; }

    public DateTime? QuoteDueDate { get; set; }

    public bool? IsShowSignature { get; set; }

    public string Project { get; set; }

    public string SalesPersonCode { get; set; }

    public byte? CompanyBranch { get; set; }

    public string ReferenceNo { get; set; }

    public string SalesOrderNo { get; set; }

    public string QuoteThanksNote { get; set; }

    public string VatapplicableRate { get; set; }

    public byte? RevisionNo { get; set; }

    public bool? IsApproved { get; set; }

    public string JobSite { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedSignatory { get; set; }

    public string ApprovedSignatory { get; set; }

    public short? CoordinatorIncharge { get; set; }

    public string TransportationScope { get; set; }
    public DateTime? VerifiedOn { get; set; }   
    public string? VerifiedBy { get; set; }
    public bool IsSubmitted { get; set; }          
    public string? SubmittedBy { get; set; }       
    public DateTime? SubmittedOn { get; set; }
    public decimal? CurrencyRate { get; set; }
    public int? BaseCurrencyId { get; set; }
    public int? CurrencyId { get; set; }
}