// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl40120PropertyInvoiceMonthlyForInsert
{
    public string InvoiceNo { get; set; }

    public string PropertyNo { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? UnitRate { get; set; }

    public string UoM { get; set; }

    public string DetailedDescription { get; set; }

    public int? DaysToBill { get; set; }

    public string DeliveryNoteNo { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public decimal? LineAmount { get; set; }

    public string Remarks { get; set; }

    public string DatesBilledFor { get; set; }

    public string ClientCode { get; set; }

    public string QuotationNo { get; set; }

    public DateTime? MobilizedDate { get; set; }

    public DateTime? DemobilizedDate { get; set; }
}