// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl40119PropertyInvoiceChild
{
    public int InvoiceChildSlNo { get; set; }

    public string InvoiceNo { get; set; }

    public string PropertyNo { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? UnitRate { get; set; }

    public string UoM { get; set; }

    public string DetailedDescription { get; set; }

    public decimal? DaysToBill { get; set; }

    public string DeliveryNoteNo { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public decimal? LineAmount { get; set; }

    public string Remarks { get; set; }

    public string DatesBilledFor { get; set; }

    public decimal? TotalHours { get; set; }

    public int? WeeksToBill { get; set; }

    public int? MonthsToBill { get; set; }

    public decimal? UnitsToBill { get; set; }

    public decimal? LineOrderNo { get; set; }

    public decimal? Othours { get; set; }

    public decimal? Otrate { get; set; }

    public string PropertyOperatorNames { get; set; }

    public string PropertyOperatorIds { get; set; }
}