// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl40121PropertyTimesheetMaster
{
    public int TimeSheetMasterId { get; set; }

    public DateTime? TimeSheetMonth { get; set; }

    public string PropertyNo { get; set; }

    public int? TimeSheetMonthId { get; set; }

    public bool? IsNoTimeSheet { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public decimal? RatePerHour { get; set; }

    public string InvoiceSummNo { get; set; }

    public string SupplierTssummaryNo { get; set; }

    public bool? IsSupplierTimeSheetApproved { get; set; }

    public string SuppTimesheetApprovedBy { get; set; }

    public DateTime? SuppTimesheetApprovedOn { get; set; }

    public bool? IsSupplierTimesheetSubmitted { get; set; }

    public string SuppTimesheetSubmittedBy { get; set; }

    public DateTime? SuppTimesheetSubmittedOn { get; set; }

    public decimal? Deductions { get; set; }
}