// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl50106CampContractChild
{
    public long CampContractChildSlNo { get; set; }

    public string CampContractNo { get; set; }

    public short? RoomTypeCode { get; set; }

    public byte? RateMethod { get; set; }

    public decimal? RateWithFood { get; set; }

    public decimal? RateWithoutFood { get; set; }

    public decimal? VacatedRoomRate { get; set; }
}