// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl60702rfqchild
{
    public long RfqchildSlNo { get; set; }

    public string Rfqno { get; set; }

    public string Gscode { get; set; }

    public decimal? QuotedQuantity { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? ItemDiscount { get; set; }

    public string QuotationRemarks { get; set; }

    public int? LineOrderNo { get; set; }

    public string AddlDescription { get; set; }

    public bool? IsWonForPo { get; set; }

    public string IsWonUpdatedBy { get; set; }

    public DateTime? IsWonUpdatedDate { get; set; }

    public string PlanNo { get; set; }

    public string DeliveryPeriod { get; set; }

    public string ReasonForSelection { get; set; }
}