// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl60602purchaseRequestChild
{
    public long MprchildSlNo { get; set; }

    public string Mprno { get; set; }

    public string Gscode { get; set; }

    public decimal? QtyRequested { get; set; }

    public byte? UnitRateMethod { get; set; }

    public string ItemRemarks { get; set; }

    public int? LineOrderNo { get; set; }

    public string AddlDescription { get; set; }

    public string PlanNo { get; set; }

    public string DeliveryPeriod { get; set; }

    public string ItemReqPurpose { get; set; }

    public string ItemReqPriority { get; set; }

    public DateTime? ItemReqExpectedDate { get; set; }

    public decimal? ExpectedUnitRate { get; set; }

    public long? QuoteGroupItemSlNo { get; set; }
}