// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl60301deliveryNoteMaster
{
    public string DeliveryNoteNo { get; set; }

    public DateTime DeliveryDate { get; set; }

    public byte? DeliveryType { get; set; }

    public short? ClientId { get; set; }

    public string ClientPono { get; set; }

    public string QuotationNo { get; set; }

    public string SalesOrderNo { get; set; }

    public string MaterialRequestNo { get; set; }

    public short? StoreId { get; set; }

    public short? ProjectId { get; set; }

    public string ClientProject { get; set; }

    public bool? IsVerified { get; set; }

    public bool? IsApproved { get; set; }

    public string PreparedBy { get; set; }

    public DateTime? PreparedOn { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string ClientCode { get; set; }

    public string SalesPersonCode { get; set; }

    public string Attention { get; set; }

    public string ClientContactNo { get; set; }

    public string ClientContactEmail { get; set; }

    public byte? CompanyBranch { get; set; }

    public byte? Dnsignatory { get; set; }

    public string DeliveryNoteRemarks { get; set; }

    public string Salesman { get; set; }

    public string TransportedBy { get; set; }

    public string DriversName { get; set; }

    public string DriversId { get; set; }

    public string VehicleNo { get; set; }

    public string StoreCode { get; set; }

    public DateTime? ClientPodate { get; set; }

    public string RevisionNo { get; set; }

    public string InvoiceNo { get; set; }

    public string StoreIssuedFrom { get; set; }

    public string VoucherNo { get; set; }

    public bool? IsPosted { get; set; }

    public DateTime? PostedOn { get; set; }

    public string PostedBy { get; set; }

    public string ProjectMasterCode { get; set; }

    public string JobOrderNo { get; set; }

    public byte? InventoryMasterGroupId { get; set; }

    public DateTime? InventoryEffectiveDate { get; set; }
}