// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl60501materialReceiptMaster
{
    public string ReceiptNo { get; set; }

    public DateTime? ReceiptDate { get; set; }

    public byte? ModeOfReceiptId { get; set; }

    public string SupplierCode { get; set; }

    public string ClientCode { get; set; }

    public string Mprno { get; set; }

    public string Rfqno { get; set; }

    public string SupplierQuotationNo { get; set; }

    public string OurPurchaseOrderNo { get; set; }

    public string JobCode { get; set; }

    public string IssueRemarks { get; set; }

    public string PreparedBy { get; set; }

    public DateTime? PreparedOn { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public byte? CompanyBranch { get; set; }

    public bool? IsApproved { get; set; }

    public byte? ReceiptSignatory { get; set; }

    public string VatpurchaseBillNo { get; set; }

    public string StoreCode { get; set; }

    public string DeliveryNoteNo { get; set; }

    public bool? IsPosted { get; set; }

    public DateTime? PostedOn { get; set; }

    public string PostedBy { get; set; }

    public string VoucherNo { get; set; }

    public string SupplierDeliveryNoteNo { get; set; }

    public string ProjectMasterCode { get; set; }

    public byte? InventoryMasterGroupId { get; set; }

    public string SalesPersonCode { get; set; }

    public DateTime? InventoryEffectiveDate { get; set; }

    public bool? IsSubmitted { get; set; }

    public string SubmittedBy { get; set; }

    public DateTime? SubmittedOn { get; set; }

    public string VerifiedBy { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsVerified { get; set; }

    public string StoreReceivedIn { get; set; }
    public decimal? CurrencyRate { get; set; }
    public int? BaseCurrencyId { get; set; }
    public int? CurrencyId { get; set; }
}