// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl60303deliveryType
{
    public byte DeliveryTypeCode { get; set; }

    public string DeliveryType { get; set; }
}