// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl90124TutorialsMaster
{
    public long TutorialId { get; set; }

    public string TutorialTitle { get; set; }

    public string TutorialDescription { get; set; }

    public string TutorialLink { get; set; }

    public byte[] TutorialImage { get; set; }

    public string FormName { get; set; }

    public int? OrderNo { get; set; }

    public string FormDescription { get; set; }
}