// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl90102AlertMaster
{
    public long AlertId { get; set; }

    public string AlertText { get; set; }

    public string Emailadd { get; set; }

    public string AlertTextHtml { get; set; }
}