// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Web.DAL.Entities;

public partial class Tbl90104DocumentSignatory
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public byte SignatoryId { get; set; }

    public string SignatoryName { get; set; }

    public string SignatoryPosition { get; set; }

    public string SignatoryContact { get; set; }

    public string SignatoryEmail { get; set; }

    public byte[] SignatureImage { get; set; }

    public string SignatureDescription { get; set; }

    public string SignatureCode { get; set; }

    public string SignatoryMobile1 { get; set; }

    public string SignatoryMobile2 { get; set; }

    public string SignatoryNameAr { get; set; }

    public string SignatoryPositionAr { get; set; }

    public bool? IsFinanceManager { get; set; }

    public byte? UserId { get; set; }
}