// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class TblEmployeeLeave
{
    public int EmployeeLeaveSlNo { get; set; }

    public string EmployeeId { get; set; }

    public short? ContractNo { get; set; }

    public byte? NoOfDays { get; set; }

    public DateTime? LeaveStartDate { get; set; }

    public DateTime? LeaveEndDate { get; set; }

    public bool? IsApproved { get; set; }

    public bool? IsLeavePaid { get; set; }

    public string ApprovedBy { get; set; }

    public byte? LeaveType { get; set; }
}