// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Web.DAL.Entities;

public partial class TblQuotationChild
{
    public int QuotationChildSlNo { get; set; }

    public string QuotationNo { get; set; }

    public string StockNo { get; set; }

    public int Quantity { get; set; }

    public string Unit { get; set; }

    public decimal RatePerDay { get; set; }

    public int PackOf { get; set; }

    public virtual TblQuotationMaster QuotationNoNavigation { get; set; }
}