using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Data.ResponseModel;
using DevExtreme.AspNet.Mvc;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Client;
//using QD.ERP.Web.Areas.Finance.Models;
//using QD.ERP.Web.Areas.Finance.Reports.Payable_Statements;
using QD.ERP.Web.Areas.IMS.Controllers;
using QD.ERP.Web.DAL.Entities;
using QD.ERP.Web.Service;
using QD.ERP.Web.Services.Logging;
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
namespace QD.ERP.Web.Areas.ERM.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class EQPurchaseOrderController : Controller
    {
        private readonly TenantDbContextHelper _tenantDbContextHelper;
        private readonly ILogger<EQPurchaseOrderController> _logger;
        private readonly IUserActionLogger _userActionLogger;

        public EQPurchaseOrderController(ILogger<EQPurchaseOrderController> logger, TenantDbContextHelper tenantDbContextHelper, IUserActionLogger userActionLogger)
        {
            _userActionLogger = userActionLogger;
            _tenantDbContextHelper = tenantDbContextHelper;
            _logger = logger;
        }
        [HttpGet]
        public async Task<IActionResult> GetPurchaseOrders(DateTime? fromDate, DateTime? toDate)
        {
            try
            {
                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    var query = dbContext.Qry40132PropertyPoviewMasters.AsQueryable();


                    // Default dates if not provided
                    if (!fromDate.HasValue)
                    {
                        fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1); // Start of the current month
                    }

                    if (!toDate.HasValue)
                    {
                        toDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)); // End of the current month
                    }

                    // Filtering by date range
                    query = query.Where(i => i.Podate >= fromDate && i.Podate <= toDate);

                    // Fetching the data
                    var data = await query.Select(i => new
                    {
                        i.Pono,
                        i.SupplierCode,
                        i.Podate,
                        i.SupplierName,
                        i.SupplierCategory,
                        i.SupplierQuoteNo,
                        i.SupplierRefNo,
                        i.NoOfItems,
                        i.Postatus,
                        i.TotalAmount,
                    }).ToListAsync();

                    return Json(data);
                }

                return Unauthorized(new { message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in GetProject: {ex.Message}");
                return StatusCode(500, new { message = ex.Message });
            }

            }


        [HttpGet]

        public async Task<ActionResult> GetpurchaseDetails(string frmDate, string toDate)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    if (!DateTime.TryParseExact(frmDate, "MM/dd/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime from))
                        return BadRequest("Invalid from date format. Use MM/dd/yyyy.");

                    if (!DateTime.TryParseExact(toDate, "MM/dd/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime to))
                        return BadRequest("Invalid to date format. Use MM/dd/yyyy.");

                    // Fetch records based on the date range
                    var propertyPoDetails = await dbContext.Qry40135PropertyPowithDetails
                        .FromSqlRaw("SELECT * FROM Qry40135PropertyPowithDetail WHERE InvoiceDate BETWEEN @p0 AND @p1", from, to)
                        .ToListAsync();
                    return Json(propertyPoDetails);
                }
                catch (Exception ex)
                {
                    return StatusCode(500, $"Internal server error: {ex.Message}");
                }
            }
            return Unauthorized(new { message = "Invalid tenant.", success = false });
        }

        [HttpGet]

        public ActionResult<string> GetAutoGeneratedPurchaseorderNumber()
        {
            try
            {


                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    string defaultCompanyString = HttpContext.Session.GetString("DefaultcompanyID") ?? "";
                    byte defaultCompanyByte = 0; // or any default value you want


                    if (!string.IsNullOrEmpty(defaultCompanyString))
                    {
                        // Safest way (avoids exceptions):
                        byte.TryParse(defaultCompanyString, out defaultCompanyByte);
                        // Now defaultCompanyByte holds the parsed value, or 0 if parsing failed.
                    }

                    // Now use defaultCompanyByte as needed


                    if (!string.IsNullOrEmpty(defaultCompanyString))
                    {
                        // Safest way (avoids exceptions):
                        byte.TryParse(defaultCompanyString, out defaultCompanyByte);
                        // Now defaultCompanyByte holds the parsed value, or 0 if parsing failed.
                    }

                    // Now use defaultCompanyByte as needed



                    byte companyId = defaultCompanyByte;

                    var company = dbContext.Tbl901CompanyDetails
                   .FirstOrDefault(c => c.CompanyId == companyId);

                    if (company == null)
                    {
                        return NotFound("Company not found.");
                    }

                    string EquipPOAbbrv = company.EquipPoabbrv;
                    int invoiceYearDigits = company.InvoiceYearDigits ?? 0;
                    bool isResetInvoiceInYear = company.IsResetInvoiceInYear ?? false;
                    DateTime Podate = DateTime.Now;

                    // Generate new debit note number
                    string newDebitNoteNo = GetAbbreviatedCompanyCode(EquipPOAbbrv, invoiceYearDigits, Podate, isResetInvoiceInYear, dbContext);

                    return Ok(newDebitNoteNo);
                }
                else
                {
                    return BadRequest("Tenant or DB Context not found.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in GetNewRequestNoApi: {ex.Message}");
                return StatusCode(500, "Internal server error: " + ex.Message);
            }
        }


        private string GetAbbreviatedCompanyCode(string EquipPOAbbrv, int yearInDigit, DateTime invoiceDate, bool isResetByYear, ERPMasterWtDataContext dbContext)
        {
            try
            {
                var mprNumbers = dbContext.Tbl40126PropertyPomasters
                     .Where(d => !string.IsNullOrEmpty(d.Pono) && d.Pono.Length >= 5 &&
                                 (!isResetByYear || (d.Podate.HasValue && d.Podate.Value.Year == invoiceDate.Year)))
                     .Select(d => d.Pono)
                     .ToList();



                int maxRunningNumber = mprNumbers
                    .Select(no => int.TryParse(no.Substring(no.Length - 5), out int num) ? num : 0)
                    .DefaultIfEmpty(0)
                    .Max();

                maxRunningNumber += 1;




                int maxRunningNumber = mprNumbers
                    .Select(no => int.TryParse(no.Substring(no.Length - 5), out int num) ? num : 0)
                    .DefaultIfEmpty(0)
                    .Max();

                maxRunningNumber += 1;


                string strNewNo = maxRunningNumber.ToString().PadLeft(5, '0');

                string strYear = yearInDigit > 0
                    ? invoiceDate.Year.ToString().Substring(4 - yearInDigit, yearInDigit)
                    : "";

                return $"{EquipPOAbbrv}{strYear}-{strNewNo}";
            }
            catch
            {
                string strYear = yearInDigit > 0
                    ? invoiceDate.Year.ToString().Substring(4 - yearInDigit, yearInDigit)
                    : "";

                return $"{EquipPOAbbrv}{strYear}-00001";
            }
        }





        //[HttpGet]
        //public async Task<IActionResult> GetAutoGeneratedPurcdhaseorderNumber()
        //{
        //    try
        //    {
        //        var tenantName = HttpContext.Session.GetString("TenantName");
        //        if (string.IsNullOrWhiteSpace(tenantName))
        //            return Unauthorized(new { message = "Tenant name not found in session.", success = false });


        //        if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
        //        {
        //            var companyShortName = await dbContext.Tbl901CompanyDetails
        //                .Where(c => c.CompanyNameShort == tenantName)
        //                .Select(c => c.CompanyNameShort)
        //                .FirstOrDefaultAsync();

        //            if (string.IsNullOrWhiteSpace(companyShortName))
        //                return BadRequest(new { message = "Company short name not found for tenant.", success = false });

        //            string shortCode = GetAbbreviatedCompanyCode(companyShortName);
        //            string prefix = $"{shortCode}-PO-{DateTime.Now.Year}";

        //            var lastNote = await dbContext.Tbl40126PropertyPomasters
        //                .Where(d => d.Pono.StartsWith(prefix))
        //                .OrderByDescending(d => d.Pono)
        //                .FirstOrDefaultAsync();

        //            int nextNumber = 1;
        //            if (lastNote != null)
        //            {
        //                var lastNumberPart = lastNote.Pono.Split('-').Last();
        //                if (int.TryParse(lastNumberPart, out int lastNum))
        //                    nextNumber = lastNum + 1;
        //            }

        //            string formattedNumber = nextNumber.ToString("D5");
        //            string Pono = $"{prefix}-{formattedNumber}";

        //            return Ok(new { Pono, success = true });
        //        }

        //        return Unauthorized(new { message = "Tenant not found.", success = false });
        //    }
        //    catch (Exception ex)
        //    {
        //        return StatusCode(500, new { message = $"Server error: {ex.Message}", success = false });
        //    }
        //}

        //private string GetAbbreviatedCompanyCode(string companyNameShort)
        //{
        //    if (string.IsNullOrWhiteSpace(companyNameShort))
        //        return "UNK"; // Default fallback

        //    var trimmed = companyNameShort.Trim();

        //    if (trimmed.Length <= 5)
        //        return trimmed.ToUpper();

        //    var words = trimmed.Split(new[] { ' ', '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
        //    var initials = string.Concat(words.Select(w => char.ToUpper(w[0])));

        //    return initials.Length >= 3 ? initials.Substring(0, 3) : initials.PadRight(3);
        //}
        [HttpGet]
        public async Task<IActionResult> GetClients()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var clients = await dbContext.Tbl30101ClientMasters
                    .Where(c => c.IsDiscontinued != true) // optional: only active clients
                    .Select(c => new
                    {
                        ClientCode = c.ClientCode,
                        ClientName = c.ClientName,
                        ClientProjectRef = c.ClientPono,
                        AttentionTo = c.ContactPerson,
                        SupplierContactNo = c.ContactMobile1,
                        SupplierEmail = c.ContactEmail
                    })
                    .ToListAsync();

                return Json(clients);
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }

        [HttpGet]
        public async Task<IActionResult> GetProjects()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var projects = await dbContext.Qry70002projectsViewMasters
                    .Select(p => new
                    {
                        ProjectId = p.ProjectId,
                        ProjectDescription = p.ProjectDescription
                    })
                    .ToListAsync();

                return Json(projects);
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetSalesPerson(DataSourceLoadOptions loadOptions)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var ClientCategory = dbContext.Tbl20101SalesPersonMasters.Select(i => new
                    {
                        i.SalesPersonCode,
                        i.SalesPersonName
                    });

                    return Json(await DataSourceLoader.LoadAsync(ClientCategory, loadOptions));
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in GetSalesPerson: {ex.Message}");
                    return StatusCode(500, new { message = "An error occurred while fetching the data.", error = ex.Message });
                }
            }

            return Unauthorized(new { message = "Invalid tenant.", success = false });
        }
        [HttpGet]
        public async Task<IActionResult> GetRequestingUnits()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var units = await dbContext.Tbl60604purchaseRequestProjectSubUnits
                        .Select(u => new
                        {
                            ProjectSubUnitCode = u.ProjectSubUnitCode,
                            ProjectSubUnitName = u.ProjectSubUnitName
                        })
                        .ToListAsync();

                    return Json(units);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Requesting Units: {ex.Message}");
                    return StatusCode(500, "Failed to load Requesting Units");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetTypeOfRequests()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var requestTypes = await dbContext.Tbl60601purchaseRequestMasters // Replace with your actual DbSet name
                        .Select(x => new
                        {
                            TypeOfRequestID = x.Mprno,
                            TypeOfRequest = x.TypeOfRequest
                        })
                        .ToListAsync();

                    return Json(requestTypes);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Type of Requests: {ex.Message}");
                    return StatusCode(500, "Failed to load Type of Requests");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }

        [HttpGet]
        public async Task<IActionResult> GetPOCategories()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var categories = await dbContext.Tbl60404pocategories
                        .Select(x => new
                        {
                            POCategoryCode = x.PocategoryId,
                            POCategoryName = x.PocategoryName
                        })
                        .ToListAsync();

                    return Json(categories);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading PO Categories: {ex.Message}");
                    return StatusCode(500, "Failed to load PO Categories");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetInventoryGroups()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var groups = await dbContext.Tbl60008inventoryMasterGroups
                        .Select(x => new
                        {
                            InventoryMasterGroupId = x.InventoryMasterGroupId,
                            InventoryMasterGroup = x.InventoryMasterGroup
                        })
                        .ToListAsync();

                    return Json(groups);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Inventory Groups: {ex.Message}");
                    return StatusCode(500, "Failed to load Inventory Groups");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetCurrencyList()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var currencies = await dbContext.Tbl20169CurrencyExchanges
                        .OrderBy(c => c.CurrencyName)
                        .Select(c => new
                        {
                            CurrencyExchangeId = c.CurrencyExchangeId,
                            CurrencyName = c.CurrencyName
                        })
                        .ToListAsync();

                    return Json(currencies);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading currency list: {ex.Message}");
                    return StatusCode(500, "Failed to load currency list");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetDocumentSignatories()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var signatories = await dbContext.Tbl90104DocumentSignatories
                        .Select(s => new
                        {
                            SignatoryId = s.SignatoryId,
                            SignatoryName = s.SignatoryName
                        })
                        .ToListAsync();

                    return Json(signatories);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading signatories: {ex.Message}");
                    return StatusCode(500, "Failed to load document signatories");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpPost]
        public async Task<IActionResult> SavePurchaseOrder([FromBody] PurchaseOrderDto dto)
        {
            if (dto == null || dto.Master == null || !ModelState.IsValid)
                return BadRequest(new { message = "Invalid data", success = false });

            var model = dto.Master;
            var children = dto.Children ?? new List<Tbl40127PropertyPochild>();

            if (string.IsNullOrWhiteSpace(model.Pono))
                return BadRequest(new { message = "PO No is required", success = false });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            try
            {
                string userName = HttpContext.Session.GetString("UserName") ?? "System";

                // 🔹 Find existing PO
                var existingPo = await dbContext.Tbl40126PropertyPomasters
                    .FirstOrDefaultAsync(x => x.Pono == model.Pono);

                if (existingPo == null)
                {
                    // Insert new master
                    existingPo = new Tbl40126PropertyPomaster
                    {
                        Pono = model.Pono,
                        AddedBy = userName,
                        AddedOn = DateTime.Now,
                        CurrencyRate = model.CurrencyRate ?? 1,
                        BaseCurrencyId = model.BaseCurrencyId ?? 1,
                        CurrencyId = model.CurrencyId ?? 1
                    };
                    dbContext.Tbl40126PropertyPomasters.Add(existingPo);
                }
                else
                {
                    // Update existing master
                    existingPo.ModifiedBy = userName;
                    existingPo.ModifiedOn = DateTime.Now;
                }

                // 🔹 Update master common fields
                existingPo.Podate = model.Podate;
                existingPo.SupplierCode = model.SupplierCode;
                existingPo.SupplierQuoteNo = model.SupplierQuoteNo;
                existingPo.SupplierQuoteDate = model.SupplierQuoteDate;
                existingPo.SupplierRefNo = model.SupplierRefNo;
                existingPo.Attention = model.Attention;
                existingPo.SupplierContactNo = model.SupplierContactNo;
                existingPo.SupplierContactEmail = model.SupplierContactEmail;
                existingPo.SubjectTitle = model.SubjectTitle;

                existingPo.PreparedBy = model.PreparedBy;
                existingPo.PreparedOn = model.PreparedOn;
                existingPo.ApprovedBy = model.ApprovedBy;
                existingPo.ApprovedOn = model.ApprovedOn;
                existingPo.IsApproved = model.IsApproved;

                existingPo.Project = model.Project;
                existingPo.Pointroduction = model.Pointroduction;
                existingPo.Posummary = model.Posummary;
                existingPo.RevisionNo = model.RevisionNo;
                existingPo.CompanyBranch = model.CompanyBranch;
                existingPo.AdditionsText = model.AdditionsText;
                existingPo.DiscountsText = model.DiscountsText;
                existingPo.PodueDate = model.PodueDate;
                existingPo.Posignatory = model.Posignatory;
                existingPo.AdditionsAmount = model.AdditionsAmount;
                existingPo.DeductionsAmount = model.DeductionsAmount;
                existingPo.Posignature1 = model.Posignature1;
                existingPo.PothanksNote = model.PothanksNote;
                existingPo.ProjectMasterCode = model.ProjectMasterCode;
                existingPo.PoverifiedSign = model.PoverifiedSign;
                existingPo.PoapprovedSign = model.PoapprovedSign;

                existingPo.VatapplicableRate = model.VatapplicableRate;
                existingPo.IsVerified = model.IsVerified;
                existingPo.VerifiedBy = model.VerifiedBy;
                existingPo.VerifiedOn = model.VerifiedOn;
                existingPo.IsCancelled = model.IsCancelled;
                existingPo.CancelledBy = model.CancelledBy;
                existingPo.CancelledOn = model.CancelledOn;
                existingPo.PorevisionNo = model.PorevisionNo;
                existingPo.IsSubmitted = model.IsSubmitted;
                existingPo.SubmittedBy = model.SubmittedBy;
                existingPo.SubmittedOn = model.SubmittedOn;
                existingPo.CancellationRemarks = model.CancellationRemarks;
                existingPo.CurrencyRate = model.CurrencyRate ?? 1;
                existingPo.BaseCurrencyId = model.BaseCurrencyId ?? 1;
                existingPo.CurrencyId = model.CurrencyId ?? 1;

                // 🔹 Children handling
                var existingChildren = await dbContext.Tbl40127PropertyPochildren
                    .Where(c => c.PropertyPono == model.Pono)
                    .ToListAsync();

                var currencyRate = model.CurrencyRate ?? 1;

                dbContext.Tbl40127PropertyPochildren.RemoveRange(existingChildren);
                
                foreach (var child in children)
                {
                    // check if child already exists
                    var existingChild = existingChildren
                        .FirstOrDefault(c => c.PropertyPochildNo == child.PropertyPochildNo);

                    if (existingChild != null)
                    {
                        // ✅ Update existing child
                        existingChild.PropertyTypeId = child.PropertyTypeId;
                        existingChild.UnitRate = child.UnitRate * currencyRate;
                        existingChild.QuotedQuantity = child.QuotedQuantity;
                        existingChild.UnitRateMethod = child.UnitRateMethod;
                        existingChild.LineOrderNo = child.LineOrderNo;
                        existingChild.PropertyAddlDescription = child.PropertyAddlDescription;
                    }
                    else
                    {
                        // ✅ Insert new child
                        var newChild = new Tbl40127PropertyPochild
                        {
                            PropertyPono = model.Pono,
                            PropertyTypeId = child.PropertyTypeId,
                            UnitRate = child.UnitRate * currencyRate,
                            QuotedQuantity = child.QuotedQuantity,
                            UnitRateMethod = child.UnitRateMethod,
                            LineOrderNo = child.LineOrderNo,
                            PropertyAddlDescription = child.PropertyAddlDescription
                        };

                        await dbContext.Tbl40127PropertyPochildren.AddAsync(newChild);
                    }
                }
                 
                // ✅ Save all changes once, outside loop
                await dbContext.SaveChangesAsync();

                return Ok(new  
                {
                    message = existingPo.ModifiedOn == existingPo.AddedOn
                        ? "Purchase order inserted successfully"
                        : "Purchase order updated successfully",
                    pono = existingPo.Pono,
                    children = children,
                    success = true
                });

            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "Error saving purchase order: " + ex.Message, success = false });
            }
        }

        public class PurchaseOrderDto
        {
            public Tbl40126PropertyPomaster Master { get; set; }
            public List<Tbl40127PropertyPochild> Children { get; set; }
            public List<Qry40130PropertyPochild> Childrens { get; set; }
        }
        [HttpGet]
        public async Task<IActionResult> GetPurchaseOrderByRefNo([FromQuery] string poNo)
        {
            if (string.IsNullOrWhiteSpace(poNo))
                return BadRequest(new { message = "PO No is required", success = false });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            try
            {
                // 🔹 Fetch master
                var po = await dbContext.Tbl40126PropertyPomasters
                    .FirstOrDefaultAsync(x => x.Pono == poNo);

                if (po == null)
                    return NotFound(new { message = "Purchase Order not found", success = false });

                // 🔹 Map master fields
                var masterDto = new
                {
                    Pono = po.Pono,
                    Podate = po.Podate,
                    SupplierCode = po.SupplierCode,
                    PorevisionNo = po.PorevisionNo,
                    SupplierQuoteNo = po.SupplierQuoteNo,
                    SupplierQuoteDate = po.SupplierQuoteDate,
                    Attention = po.Attention,
                    SupplierContactNo = po.SupplierContactNo,
                    SupplierContactEmail = po.SupplierContactEmail,
                    ProjectMasterCode = po.ProjectMasterCode,
                    Posummary = po.Posummary,
                    Pointroduction = po.Pointroduction,
                    PothanksNote = po.PothanksNote,
                    SubjectTitle = po.SubjectTitle,
                    CancellationRemarks = po.CancellationRemarks,
                    CompanyBranch = po.CompanyBranch,
                    SubmittedBy = po.SubmittedBy,
                    SupplierRefNo = po.SupplierRefNo,
                    VerifiedBy = po.VerifiedBy,
                    ApprovedBy = po.ApprovedBy,
                    CurrencyRate = po.CurrencyRate,
                    BaseCurrencyId = po.BaseCurrencyId,
                    CurrencyId = po.CurrencyId,
                    PreparedBy = po.PreparedBy,
                    IsApproved = po.IsApproved,
                    DeductionsAmount = po.DeductionsAmount,
                    AdditionsAmount = po.AdditionsAmount,
                    DiscountsText = po.DiscountsText,
                    AdditionsText = po.AdditionsText,
                    Project = po.Project,
                    VatapplicableRate = po.VatapplicableRate
                };

                // 🔹 Fetch children separately
                var children = await dbContext.Qry40130PropertyPochildren
                    .Where(c => c.PropertyPono == poNo)
                    .OrderBy(c => c.PropertyPochildNo)
                    .ToListAsync();

                // 🔹 Get currency rate (default to 1 if null)
                var currencyRate = await dbContext.Tbl40126PropertyPomasters
                     .Where(x => x.Pono == poNo)
                    .Select(x => x.CurrencyRate)
                    .FirstOrDefaultAsync() ?? 1;

                // 🔹 If you need a dictionary to hold computed values
                var dict = new Dictionary<string, object>();

                // Example: store average unit rate normalized by currency
                if (children.Any())
                {
                    dict["CalcLineTotal"] = children.Average(c => c.CalcLineTotal) / currencyRate;
                    dict["UnitRate"] = children.Average(c => c.UnitRate) / currencyRate;
                }

                // 🔹 Map children to DTO with UnitRate adjusted
                var childrenDto = children.Select((c, index) => new
                {
                    SNo = index + 1,
                    c.PropertyPochildNo,
                    c.PropertyTypeId,
                    UnitRate = currencyRate > 0
                    ? (decimal)c.UnitRate / (decimal)currencyRate  // ✅ cast to decimal
                    : (decimal)c.UnitRate,
                    c.QuotedQuantity,
                    c.UnitRateMethod,
                    c.PropertyAddlDescription,
                    CalcLineTotal = currencyRate > 0
                    ? (decimal)c.CalcLineTotal / (decimal)currencyRate  // also fix total if needed
                    : (decimal)c.CalcLineTotal
                }).ToList();

                return Ok(new
                {
                    Master = masterDto,
                    Children = childrenDto,
                    success = true
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "Error fetching purchase order: " + ex.Message, success = false });
            }
        }
        [HttpPost]
        public async Task<IActionResult> UnlockPurchaseOrder([FromBody] Tbl40126PropertyPomaster data)
        {
            try
            {
                string pono = data?.Pono;
                if (string.IsNullOrWhiteSpace(pono))
                    return BadRequest(new { success = false, message = "PO number is required." });

                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                    return Unauthorized(new { success = false, message = "Invalid tenant." });

                var po = await dbContext.Tbl40126PropertyPomasters.FirstOrDefaultAsync(x => x.Pono == pono);
                if (po == null)
                    return Ok(new { success = false, message = "Purchase Order not found." });

                // If any status is true, set all to false and save
                if (po.IsSubmitted == true || po.IsVerified == true || po.IsApproved == true)
                {
                    po.IsSubmitted = false;
                    po.IsVerified = false;
                    po.IsApproved = false;
                    await dbContext.SaveChangesAsync();
                    await _userActionLogger.LogAsync(
                      module: "IMS > Unlock Purchase Order",
                      actionDetail: $":Unlocked Purchase Order {data.Pono}",
                      documentNo: $"{data.Pono}"
                    );
                    return Ok(new { success = true, message = "Purchase Order unlocked. All statuses set to false." });
                }
                else
                {
                    return Ok(new { success = true, message = "Already unlocked. All statuses are already false." });
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
            }
        }

        [HttpDelete("{poNo}")]
        public async Task<IActionResult> DeletePurchaseOrder(string poNo)
        {
            if (string.IsNullOrWhiteSpace(poNo))
                return BadRequest(new { message = "PO number is required", success = false });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            try
            {
                var existingPo = await dbContext.Tbl40126PropertyPomasters
                  .FirstOrDefaultAsync(x => x.Pono.Trim().ToLower() == poNo.Trim().ToLower());


                if (existingPo == null)
                    return NotFound(new { message = $"Purchase order {poNo} not found in tenant {tenant}.", success = false });

                if (existingPo == null)
                    return BadRequest(new { message = "Cannot delete: PO has already been submitted.", success = false });

                if (existingPo == null)
                    return BadRequest(new { message = "Cannot delete: PO has already been verified.", success = false });

                if (existingPo == null)
                    return BadRequest(new { message = "Cannot delete: PO has already been approved.", success = false });

                var children = await dbContext.Tbl40127PropertyPochildren
                    .Where(c => c.PropertyPono == poNo)
                    .ToListAsync();

                dbContext.Tbl40127PropertyPochildren.RemoveRange(children);

                dbContext.Tbl40126PropertyPomasters.Remove(existingPo);

                await dbContext.SaveChangesAsync();

                return Ok(new { message = $"Purchase order {poNo} deleted successfully", success = true });
            }
            catch (Exception ex)
            {
                // Optional: log the error
                return StatusCode(500, new { message = "Error deleting purchase order: " + ex.Message, success = false });
            }
        }


        [HttpPost]
        public async Task<ActionResult> CancelPurchaseOrder([FromForm] string Pono)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var userName = HttpContext.Session.GetString("UserName");
                    var userIdString = HttpContext.Session.GetString("UserId");

                    if (string.IsNullOrEmpty(Pono))
                    {
                        return BadRequest(new { Message = "Purchase Order No is required." });
                    }

                    var voucher = dbContext.Tbl40126PropertyPomasters
                                  .FirstOrDefault(v => v.Pono == Pono);

                    if (voucher == null)
                    {
                        return NotFound(new { Message = "Purchase Order No not found." });
                    }

                    voucher.IsCancelled = true;
                    voucher.CancelledOn = DateTime.Now;
                   voucher.CancelledBy = userName;

                    dbContext.SaveChanges();

                    await _userActionLogger.LogAsync(
                      module: "ERM > Cancel Purchase",
                     actionDetail: $"Canceled Purchase Order: {Pono}",
                      documentNo: $"{Pono}"
                    );

                    return Ok(new
                    {
                        Message = "Purchase Order Request has been Cancelled.",
                        VoucherCancelledBy = userName
                    });
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in GetProject: {ex.Message}");
                    return BadRequest(new { Message = ex.Message });
                }
            }

            return Unauthorized(new { Message = "Invalid tenant.", Success = false });
        }
        [HttpPost]
        public async Task<IActionResult> SubmitPurchaseOrder([FromBody] Tbl40126PropertyPomaster data)
        {
            try
            {
                string pono = data?.Pono;
                if (string.IsNullOrWhiteSpace(pono))
                    return BadRequest(new { success = false, message = "PO number is required." });

                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                    return Unauthorized(new { success = false, message = "Invalid tenant." });

                var po = await dbContext.Tbl40126PropertyPomasters.FirstOrDefaultAsync(x => x.Pono == pono);
                if (po == null)
                    return Ok(new { success = false, message = "Please save the purchase order before submitting." });

                if (po.IsSubmitted == true)
                    return Ok(new { success = false, message = "This purchase order is already submitted." });

                po.IsSubmitted = true;
                po.SubmittedBy = HttpContext.Session.GetString("UserName") ?? "System";
                po.SubmittedOn = DateTime.Now;

                await dbContext.SaveChangesAsync();
                await _userActionLogger.LogAsync(
                  module: "IMS > Submit Purchase Order",
                  actionDetail: $"Submited Purchase Order {data.Pono}",
                  documentNo: $"{data.Pono}"
                );

                return Ok(new { success = true, message = "Purchase order submitted successfully." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
            }
        }


        [HttpPost]
        public async Task<IActionResult> VerifyPurchaseOrder([FromBody] Tbl40126PropertyPomaster data)
        {
            try
            {
                string pono = data?.Pono;
                if (string.IsNullOrWhiteSpace(pono))
                    return BadRequest(new { success = false, message = "PO number is required." });

                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                    return Unauthorized(new { success = false, message = "Invalid tenant." });

                var po = await dbContext.Tbl40126PropertyPomasters.FirstOrDefaultAsync(x => x.Pono == pono);
                if (po == null)
                    return Ok(new { success = false, message = "Please save and submit the purchase order before verifying." });

                if (po.IsSubmitted != true)
                    return Ok(new { success = false, message = "Please submit before verifying." });

                if (po.IsVerified == true)
                    return Ok(new { success = false, message = "This purchase order is already verified." });

                po.IsVerified = true;
                po.VerifiedBy = HttpContext.Session.GetString("UserName") ?? "System";
                po.VerifiedOn = DateTime.Now;

                await dbContext.SaveChangesAsync();
                await _userActionLogger.LogAsync(
                    module: "IMS > Delete Purchase Order",
                   actionDetail: $"Deleted Purchase Order {data.Pono}",
                  documentNo: $"{data.Pono}"
                );

                return Ok(new { success = true, message = "Purchase order verified successfully." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
            }
        }


        [HttpPost]
        public async Task<IActionResult> ApprovePurchaseOrder([FromBody] Tbl40126PropertyPomaster data)
        {
            try
            {
                string pono = data?.Pono;
                if (string.IsNullOrWhiteSpace(pono))
                    return BadRequest(new { success = false, message = "PO number is required." });

                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                    return Unauthorized(new { success = false, message = "Invalid tenant." });

                var po = await dbContext.Tbl40126PropertyPomasters.FirstOrDefaultAsync(x => x.Pono == pono); if (po == null)
                    return Ok(new { success = false, message = "Please save and submit the purchase order before approving." });

                if (po.IsVerified != true)
                    return Ok(new { success = false, message = "Please verify before approving." });

                if (po.IsApproved == true)
                    return Ok(new { success = false, message = "This purchase order is already approved." });

                po.IsApproved = true;
                po.ApprovedBy = HttpContext.Session.GetString("UserName") ?? "System";
                po.ApprovedOn = DateTime.Now;

                await dbContext.SaveChangesAsync();
                await _userActionLogger.LogAsync(
                    module: "IMS > Approve Purchase Order",
                   actionDetail: $"Approved Purchase Order {data.Pono}",
                  documentNo: $"{data.Pono}"
                );

                return Ok(new { success = true, message = "Purchase order approved successfully." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> SaveItem([FromBody] List<Tbl60402purchaseOrderChild> items)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                {
                    await dbContext.Tbl60402purchaseOrderChildren.AddRangeAsync(items);
                    await dbContext.SaveChangesAsync();

                    return Ok(new { success = true, message = "Items saved successfully." });
                }

                return Unauthorized(new { success = false, message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
            }
        }

        [HttpPost("UpdateItem")]
        public async Task<IActionResult> UpdateItem([FromBody] Tbl60402purchaseOrderChild updatedItem)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                {
                    var existingItem = await dbContext.Tbl60402purchaseOrderChildren
                        .FirstOrDefaultAsync(i => i.PochildNo == updatedItem.PochildNo);

                    if (existingItem == null)
                        return NotFound(new { success = false, message = "Item not found." });

                    // Update only the available properties
                    existingItem.Pono = updatedItem.Pono;
                    existingItem.Gscode = updatedItem.Gscode;
                    existingItem.AddlDescription = updatedItem.AddlDescription;
                    existingItem.QuotedQuantity = updatedItem.QuotedQuantity;
                    existingItem.UnitRateMethod = updatedItem.UnitRateMethod;
                    existingItem.UnitPrice = updatedItem.UnitPrice;
                    existingItem.ItemDiscount = updatedItem.ItemDiscount;
                    existingItem.PotaxSlab = updatedItem.PotaxSlab;
                    existingItem.PoitemRemarks = updatedItem.PoitemRemarks;
                    existingItem.LineOrderNo = updatedItem.LineOrderNo;
                    existingItem.PlanNo = updatedItem.PlanNo;
                    existingItem.DeliveryPeriod = updatedItem.DeliveryPeriod;
                    existingItem.MritemNo = updatedItem.MritemNo;
                    existingItem.Currency = updatedItem.Currency;
                    existingItem.ExchangeRate = updatedItem.ExchangeRate;
                    existingItem.UnitRateInOc = updatedItem.UnitRateInOc;
                    existingItem.DiscountInOc = updatedItem.DiscountInOc;

                    await dbContext.SaveChangesAsync();

                    return Ok(new { success = true, message = "Item updated successfully." });
                }

                return Unauthorized(new { success = false, message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
            }
        }

    }
}
