using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Mvc;
using Humanizer;
using DevExtreme.AspNet.Data.ResponseModel;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Client;
using QD.ERP.Web.Areas.Finance.Models;
using QD.ERP.Web.Areas.Finance.Reports.Payable_Statements;
using QD.ERP.Web.DAL.Entities;
using QD.ERP.Web.Service;
using System;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
namespace QD.ERP.Web.Areas.ERM.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class EQPurchaseOrderController : Controller
    {
        private readonly TenantDbContextHelper _tenantDbContextHelper;
        private readonly ILogger<EQPurchaseOrderController> _logger;

        public EQPurchaseOrderController(ILogger<EQPurchaseOrderController> logger, TenantDbContextHelper tenantDbContextHelper)
        {
            _tenantDbContextHelper = tenantDbContextHelper;
            _logger = logger;
        }
        [HttpGet]
        public async Task<IActionResult> GetPurchaseOrders(DateTime? fromDate, DateTime? toDate)
        {
            try
            {
                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    var query = dbContext.Qry40132PropertyPoviewMasters.AsQueryable();


                    // Default dates if not provided
                    if (!fromDate.HasValue)
                    {
                        fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1); // Start of the current month
                    }

                    if (!toDate.HasValue)
                    {
                        toDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)); // End of the current month
                    }

                    // Filtering by date range
                    query = query.Where(i => i.Podate >= fromDate && i.Podate <= toDate);

                    // Fetching the data
                    var data = await query.Select(i => new
                    {
                        i.Pono,
                        i.SupplierCode,
                        i.Podate,
                        i.SupplierName,
                        i.SupplierCategory,
                        i.SupplierQuoteNo,
                        i.SupplierRefNo,
                        i.NoOfItems,
                        i.Postatus,
                        i.TotalAmount,
                    }).ToListAsync();

                    return Json(data);
                }

                return Unauthorized(new { message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in GetProject: {ex.Message}");
                return StatusCode(500, new { message = ex.Message });
            }

            }

        [HttpGet]
        public async Task<IActionResult> GetAutoGeneratedPurchaseorderNumber()
        {
            try
            {
                var tenantName = HttpContext.Session.GetString("TenantName");
                if (string.IsNullOrWhiteSpace(tenantName))
                    return Unauthorized(new { message = "Tenant name not found in session.", success = false });


                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    var companyShortName = await dbContext.Tbl901CompanyDetails
                        .Where(c => c.CompanyNameShort == tenantName)
                        .Select(c => c.CompanyNameShort)
                        .FirstOrDefaultAsync();

                    if (string.IsNullOrWhiteSpace(companyShortName))
                        return BadRequest(new { message = "Company short name not found for tenant.", success = false });

                    string shortCode = GetAbbreviatedCompanyCode(companyShortName);
                    string prefix = $"{shortCode}-PO-{DateTime.Now.Year}";

                    var lastNote = await dbContext.Tbl40126PropertyPomasters
                        .Where(d => d.Pono.StartsWith(prefix))
                        .OrderByDescending(d => d.Pono)
                        .FirstOrDefaultAsync();

                    int nextNumber = 1;
                    if (lastNote != null)
                    {
                        var lastNumberPart = lastNote.Pono.Split('-').Last();
                        if (int.TryParse(lastNumberPart, out int lastNum))
                            nextNumber = lastNum + 1;
                    }

                    string formattedNumber = nextNumber.ToString("D5");
                    string Pono = $"{prefix}-{formattedNumber}";

                    return Ok(new { Pono, success = true });
                }

                return Unauthorized(new { message = "Tenant not found.", success = false });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = $"Server error: {ex.Message}", success = false });
            }
        }

        private string GetAbbreviatedCompanyCode(string companyNameShort)
        {
            if (string.IsNullOrWhiteSpace(companyNameShort))
                return "UNK"; // Default fallback

            var trimmed = companyNameShort.Trim();

            if (trimmed.Length <= 5)
                return trimmed.ToUpper();

            var words = trimmed.Split(new[] { ' ', '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
            var initials = string.Concat(words.Select(w => char.ToUpper(w[0])));

            return initials.Length >= 3 ? initials.Substring(0, 3) : initials.PadRight(3);
        }
        [HttpGet]
        public async Task<IActionResult> GetClients()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var clients = await dbContext.Tbl30101ClientMasters
                    .Where(c => c.IsDiscontinued != true) // optional: only active clients
                    .Select(c => new
                    {
                        ClientCode = c.ClientCode,
                        ClientName = c.ClientName,
                        ClientProjectRef = c.ClientPono,
                        AttentionTo = c.ContactPerson,
                        SupplierContactNo = c.ContactMobile1,
                        SupplierEmail = c.ContactEmail
                    })
                    .ToListAsync();

                return Json(clients);
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }

        [HttpGet]
        public async Task<IActionResult> GetProjects()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var projects = await dbContext.Qry70002projectsViewMasters
                    .Select(p => new
                    {
                        ProjectId = p.ProjectId,
                        ProjectDescription = p.ProjectDescription
                    })
                    .ToListAsync();

                return Json(projects);
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetSalesPerson(DataSourceLoadOptions loadOptions)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var ClientCategory = dbContext.Tbl20101SalesPersonMasters.Select(i => new
                    {
                        i.SalesPersonCode,
                        i.SalesPersonName
                    });

                    return Json(await DataSourceLoader.LoadAsync(ClientCategory, loadOptions));
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in GetSalesPerson: {ex.Message}");
                    return StatusCode(500, new { message = "An error occurred while fetching the data.", error = ex.Message });
                }
            }

            return Unauthorized(new { message = "Invalid tenant.", success = false });
        }
        [HttpGet]
        public async Task<IActionResult> GetRequestingUnits()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var units = await dbContext.Tbl60604purchaseRequestProjectSubUnits
                        .Select(u => new
                        {
                            ProjectSubUnitCode = u.ProjectSubUnitCode,
                            ProjectSubUnitName = u.ProjectSubUnitName
                        })
                        .ToListAsync();

                    return Json(units);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Requesting Units: {ex.Message}");
                    return StatusCode(500, "Failed to load Requesting Units");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetTypeOfRequests()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var requestTypes = await dbContext.Tbl60601purchaseRequestMasters // Replace with your actual DbSet name
                        .Select(x => new
                        {
                            TypeOfRequestID = x.Mprno,
                            TypeOfRequest = x.TypeOfRequest
                        })
                        .ToListAsync();

                    return Json(requestTypes);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Type of Requests: {ex.Message}");
                    return StatusCode(500, "Failed to load Type of Requests");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }

        [HttpGet]
        public async Task<IActionResult> GetPOCategories()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var categories = await dbContext.Tbl60404pocategories
                        .Select(x => new
                        {
                            POCategoryCode = x.PocategoryId,
                            POCategoryName = x.PocategoryName
                        })
                        .ToListAsync();

                    return Json(categories);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading PO Categories: {ex.Message}");
                    return StatusCode(500, "Failed to load PO Categories");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetInventoryGroups()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var groups = await dbContext.Tbl60008inventoryMasterGroups
                        .Select(x => new
                        {
                            InventoryMasterGroupId = x.InventoryMasterGroupId,
                            InventoryMasterGroup = x.InventoryMasterGroup
                        })
                        .ToListAsync();

                    return Json(groups);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Inventory Groups: {ex.Message}");
                    return StatusCode(500, "Failed to load Inventory Groups");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetCurrencyList()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var currencies = await dbContext.Tbl20169CurrencyExchanges
                        .OrderBy(c => c.CurrencyName)
                        .Select(c => new
                        {
                            CurrencyExchangeId = c.CurrencyExchangeId,
                            CurrencyName = c.CurrencyName
                        })
                        .ToListAsync();

                    return Json(currencies);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading currency list: {ex.Message}");
                    return StatusCode(500, "Failed to load currency list");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetDocumentSignatories()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var signatories = await dbContext.Tbl90104DocumentSignatories
                        .Select(s => new
                        {
                            SignatoryId = s.SignatoryId,
                            SignatoryName = s.SignatoryName
                        })
                        .ToListAsync();

                    return Json(signatories);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading signatories: {ex.Message}");
                    return StatusCode(500, "Failed to load document signatories");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        //[HttpPost]
        //public async Task<IActionResult> SavePurchaseOrder([FromBody] Tbl40126PropertyPomaster model)
        //{
        //    if (model == null || !ModelState.IsValid)
        //        return BadRequest(new { message = "Invalid data", success = false });

        //    if (string.IsNullOrWhiteSpace(model.Pono))
        //        return BadRequest(new { message = "PO No is required", success = false });

        //    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
        //        return Unauthorized(new { message = "Invalid tenant", success = false });

        //    try
        //    {
        //        string userName = HttpContext.Session.GetString("UserName") ?? "System";

        //        var existingPo = await dbContext.Tbl40126PropertyPomasters
        //            .FirstOrDefaultAsync(x => x.Pono == model.Pono);

        //        if (existingPo == null)
        //        {
        //            // New PO - initialize states
        //            model.AddedBy = userName;
        //            model.AddedOn = DateTime.Now;
        //            model.IsApproved = false;
        //            model.IsVerified = false;
        //            model.IsSubmitted = model.IsSubmitted ?? false;

        //            if (model.IsSubmitted == true)
        //            {
        //                model.SubmittedBy = userName;
        //                model.SubmittedOn = DateTime.Now;
        //            }

        //            dbContext.Tbl40126PropertyPomasters.Add(model);
        //        }
        //        else
        //        {
        //            // If already approved, do NOT allow editing
        //            if (existingPo.IsApproved == true)
        //            {
        //                return BadRequest(new { message = "This purchase order has been approved and cannot be edited.", success = false });
        //            }

        //            // Update fields normally
        //            existingPo.Podate = model.Podate;
        //            existingPo.SupplierCode = model.SupplierCode;
        //            existingPo.SupplierQuoteNo = model.SupplierQuoteNo;
        //            existingPo.SupplierQuoteDate = model.SupplierQuoteDate;
        //            existingPo.SupplierRefNo = model.SupplierRefNo;
        //            existingPo.Attention = model.Attention;
        //            existingPo.SupplierContactNo = model.SupplierContactNo;
        //            existingPo.SupplierContactEmail = model.SupplierContactEmail;
        //            existingPo.SubjectTitle = model.SubjectTitle;

        //            // Handle submit, verify, approve logic

        //            // Submit
        //            if (model.IsSubmitted == true && existingPo.IsSubmitted != true)
        //            {
        //                existingPo.IsSubmitted = true;
        //                existingPo.SubmittedBy = userName;
        //                existingPo.SubmittedOn = DateTime.Now;
        //            }

        //            // Verify - only if submitted and not verified yet
        //            if (model.IsVerified == true && existingPo.IsVerified != true)
        //            {
        //                if (existingPo.IsSubmitted != true)
        //                {
        //                    return BadRequest(new { message = "Cannot verify before submitting.", success = false });
        //                }
        //                existingPo.IsVerified = true;
        //                existingPo.VerifiedBy = userName;
        //                existingPo.VerifiedOn = DateTime.Now;
        //            }

        //            // Approve - only if verified and not approved yet
        //            if (model.IsApproved == true && existingPo.IsApproved != true)
        //            {
        //                if (existingPo.IsVerified != true)
        //                {
        //                    return BadRequest(new { message = "Cannot approve before verification.", success = false });
        //                }
        //                existingPo.IsApproved = true;
        //                existingPo.ApprovedBy = userName;
        //                existingPo.ApprovedOn = DateTime.Now;
        //            }

        //            // Update other fields that can be changed before approval
        //            existingPo.PreparedBy = model.PreparedBy;
        //            existingPo.PreparedOn = model.PreparedOn;
        //            existingPo.Project = model.Project;
        //            existingPo.Pointroduction = model.Pointroduction;
        //            existingPo.Posummary = model.Posummary;
        //            existingPo.RevisionNo = model.RevisionNo;
        //            existingPo.CompanyBranch = model.CompanyBranch;
        //            existingPo.AdditionsText = model.AdditionsText;
        //            existingPo.DiscountsText = model.DiscountsText;
        //            existingPo.PodueDate = model.PodueDate;
        //            existingPo.Posignatory = model.Posignatory;
        //            existingPo.AdditionsAmount = model.AdditionsAmount;
        //            existingPo.DeductionsAmount = model.DeductionsAmount;
        //            existingPo.PothanksNote = model.PothanksNote;
        //            existingPo.ProjectMasterCode = model.ProjectMasterCode;
        //            existingPo.PoverifiedSign = model.PoverifiedSign;
        //            existingPo.PoapprovedSign = model.PoapprovedSign;
        //            existingPo.PorevisionNo = model.PorevisionNo;
        //            existingPo.ModifiedBy = userName;
        //            existingPo.ModifiedOn = DateTime.Now;
        //        }

        //        await dbContext.SaveChangesAsync();

        //        return Ok(new
        //        {
        //            message = "Purchase order saved successfully",
        //            pono = model.Pono,
        //            isApproved = existingPo?.IsApproved ?? model.IsApproved ?? false,
        //            success = true
        //        });

        //    }
        //    catch (Exception ex)
        //    {
        //        return StatusCode(500, new { message = "Error saving purchase order: " + ex.Message, success = false });
        //    }
        //}
        [HttpPost]
        public async Task<IActionResult> SavePurchaseOrder([FromBody] PurchaseOrderDto dto)
        {
            if (dto == null || dto.Master == null || !ModelState.IsValid)
                return BadRequest(new { message = "Invalid data", success = false });

            var model = dto.Master;
            var children = dto.Children ?? new List<Tbl40127PropertyPochild>();

            if (string.IsNullOrWhiteSpace(model.Pono))
                return BadRequest(new { message = "PO No is required", success = false });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            try
            {
                string userName = HttpContext.Session.GetString("UserName") ?? "System";

                // 🔹 Master check
                var existingPo = await dbContext.Tbl40126PropertyPomasters
                    .FirstOrDefaultAsync(x => x.Pono == model.Pono);

                if (existingPo == null)
                {
                    // Insert
                    existingPo = new Tbl40126PropertyPomaster
                    {
                        Pono = model.Pono,
                        AddedBy = userName,
                        AddedOn = DateTime.Now
                    };
                    dbContext.Tbl40126PropertyPomasters.Add(existingPo);
                }
                else
                {
                    // Update
                    existingPo.ModifiedBy = userName;
                    existingPo.ModifiedOn = DateTime.Now;
                }

                // 🔹 Common master fields
                existingPo.PreparedBy = model.PreparedBy;
                existingPo.PreparedOn = model.PreparedOn;
                existingPo.Project = model.Project;
                existingPo.Pointroduction = model.Pointroduction;
                existingPo.Posummary = model.Posummary;
                existingPo.RevisionNo = model.RevisionNo;
                existingPo.CompanyBranch = model.CompanyBranch;
                existingPo.AdditionsText = model.AdditionsText;
                existingPo.DiscountsText = model.DiscountsText;
                existingPo.PodueDate = model.PodueDate;
                existingPo.Posignatory = model.Posignatory;
                existingPo.AdditionsAmount = model.AdditionsAmount;
                existingPo.DeductionsAmount = model.DeductionsAmount;
                existingPo.PothanksNote = model.PothanksNote;
                existingPo.ProjectMasterCode = model.ProjectMasterCode;
                existingPo.PoverifiedSign = model.PoverifiedSign;
                existingPo.PoapprovedSign = model.PoapprovedSign;
                existingPo.PorevisionNo = model.PorevisionNo;

                // 🔹 Handle children
                foreach (var child in children)
                {
                    // Try to find existing child by its PK
                    var existingChild = await dbContext.Tbl40127PropertyPochildren
                        .FirstOrDefaultAsync(c => c.PropertyPochildNo == child.PropertyPochildNo);

                    if (existingChild == null)
                    {
                        // Insert new child
                        child.PropertyPono = model.Pono; // FK mapping
                        dbContext.Tbl40127PropertyPochildren.Add(child);
                    }
                    else
                    {
                        // Update existing child
                        existingChild.PropertyTypeId = child.PropertyTypeId;
                        existingChild.UnitRate = child.UnitRate;
                        existingChild.QuotedQuantity = child.QuotedQuantity;
                        existingChild.UnitRateMethod = child.UnitRateMethod;
                        existingChild.LineOrderNo = child.LineOrderNo;
                    }
                }
                await dbContext.SaveChangesAsync();

                return Ok(new
                {
                    message = existingPo.ModifiedOn == existingPo.AddedOn
                        ? "Purchase order inserted successfully"
                        : "Purchase order updated successfully",
                    pono = existingPo.Pono,
                    children = children,
                    success = true
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "Error saving purchase order: " + ex.Message, success = false });
            }
        }
        public class PurchaseOrderDto
        {
            public Tbl40126PropertyPomaster Master { get; set; }
            public List<Tbl40127PropertyPochild> Children { get; set; }
        }

        [HttpPost]
        public async Task<IActionResult> SaveItem([FromBody] List<Tbl60402purchaseOrderChild> items)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                {
                    await dbContext.Tbl60402purchaseOrderChildren.AddRangeAsync(items);
                    await dbContext.SaveChangesAsync();

                    return Ok(new { success = true, message = "Items saved successfully." });
                }

                return Unauthorized(new { success = false, message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
            }
        }

        [HttpPost("UpdateItem")]
        public async Task<IActionResult> UpdateItem([FromBody] Tbl60402purchaseOrderChild updatedItem)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                {
                    var existingItem = await dbContext.Tbl60402purchaseOrderChildren
                        .FirstOrDefaultAsync(i => i.PochildNo == updatedItem.PochildNo);

                    if (existingItem == null)
                        return NotFound(new { success = false, message = "Item not found." });

                    // Update only the available properties
                    existingItem.Pono = updatedItem.Pono;
                    existingItem.Gscode = updatedItem.Gscode;
                    existingItem.AddlDescription = updatedItem.AddlDescription;
                    existingItem.QuotedQuantity = updatedItem.QuotedQuantity;
                    existingItem.UnitRateMethod = updatedItem.UnitRateMethod;
                    existingItem.UnitPrice = updatedItem.UnitPrice;
                    existingItem.ItemDiscount = updatedItem.ItemDiscount;
                    existingItem.PotaxSlab = updatedItem.PotaxSlab;
                    existingItem.PoitemRemarks = updatedItem.PoitemRemarks;
                    existingItem.LineOrderNo = updatedItem.LineOrderNo;
                    existingItem.PlanNo = updatedItem.PlanNo;
                    existingItem.DeliveryPeriod = updatedItem.DeliveryPeriod;
                    existingItem.MritemNo = updatedItem.MritemNo;
                    existingItem.Currency = updatedItem.Currency;
                    existingItem.ExchangeRate = updatedItem.ExchangeRate;
                    existingItem.UnitRateInOc = updatedItem.UnitRateInOc;
                    existingItem.DiscountInOc = updatedItem.DiscountInOc;

                    await dbContext.SaveChangesAsync();

                    return Ok(new { success = true, message = "Item updated successfully." });
                }

                return Unauthorized(new { success = false, message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
            }
        }

    }
}
