// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class AllAccountCrEntry
{
    public long VoucherEntryNo { get; set; }

    public string VoucherNo { get; set; }

    public string AccountHead { get; set; }

    public string AccountHead2 { get; set; }

    public string DrCr { get; set; }

    public string SysRemarks { get; set; }
}