// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class AqryListOfReceiptsDateQueried
{
    public DateTime ReceiptDate { get; set; }

    public short? ClientId { get; set; }

    public string QuotationNo { get; set; }

    public string StockNo { get; set; }

    public int? QtyReceived { get; set; }

    public string DeliveryNoteNo { get; set; }
}