// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class DqryIssuesContractsEditDg
{
    public int IssueChildSlNo { get; set; }

    public string IssueNo { get; set; }

    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public int QtyIssued { get; set; }

    public string Unit { get; set; }

    public int PackOf { get; set; }

    public string Remarks { get; set; }

    public string DetailedDescription { get; set; }
}