// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class DqryIssueHiredMaster
{
    public string IssueNo { get; set; }

    public DateTime IssueDate { get; set; }

    public byte ModeOfIssueId { get; set; }

    public short? SupplierId { get; set; }

    public string SupplierReference { get; set; }

    public string IssueRemarks { get; set; }

    public string StockNo { get; set; }

    public int? QtyIssued { get; set; }

    public string Unit { get; set; }

    public decimal? RentPerDay { get; set; }

    public int? PackOf { get; set; }

    public int BalanceToBeReturned { get; set; }

    public string SupplierName { get; set; }

    public string StockDescription { get; set; }
}