// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class DqryQuoteMaster
{
    public string QuoteNo { get; set; }

    public DateTime? QuoteDate { get; set; }

    public string ClientRefNo { get; set; }

    public string Attention { get; set; }

    public double? QuotePercentage { get; set; }

    public byte? SalesPerson { get; set; }

    public byte? TypeOfQuote { get; set; }

    public string SubjectTitle { get; set; }

    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public int? QtyQuoted { get; set; }

    public string ClientName { get; set; }

    public decimal? RatePerDay { get; set; }

    public decimal? UnitPrice { get; set; }

    public string Unit { get; set; }

    public decimal? ReplacementCost { get; set; }

    public decimal? LineTotalRental { get; set; }

    public decimal? LineTotalSales { get; set; }

    public string QuoteType { get; set; }

    public decimal? LineTotal { get; set; }

    public decimal? Price { get; set; }

    public decimal? GrossAmount { get; set; }
}