// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class DqryIssuesHiredMrnosHaveBalance
{
    public string ReceiptNo { get; set; }

    public DateTime ReceiptDate { get; set; }

    public short? SupplierId { get; set; }

    public string ReceiveRemarks { get; set; }

    public string GivenTo { get; set; }
}