// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class DqryInvoiceNetAmount
{
    public string InvoiceNo { get; set; }

    public decimal? GrossAmount { get; set; }

    public decimal Discount { get; set; }

    public decimal Transportation { get; set; }

    public decimal? NetAmount { get; set; }

    public decimal? GrossAmountSales { get; set; }

    public decimal? NetAmountSales { get; set; }
}