// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class EmailTemplate
{
    public int Id { get; set; }

    public string TemplateName { get; set; }

    public string Category { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public string Status { get; set; }
}