// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class MasRqryRentedBalanceWithClient
{
    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public int? TotalRented { get; set; }

    public int? TotalReturned { get; set; }

    public int? Balance { get; set; }

    public short? ClientId { get; set; }

    public string ClientName { get; set; }
}