// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry00101invoiceCounterValue
{
    public string InvoiceNo { get; set; }

    public long InvoiceCounterValue { get; set; }
}