// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry10118EmployeesMobileAllowance
{
    public string EmployeeId { get; set; }

    public byte? PayrollTemplateAdditions { get; set; }

    public decimal MobileAllowance { get; set; }

    public int? ContractSlNo { get; set; }

    public byte? AllowanceStatusId { get; set; }
}