// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry10155EmployeeLoan
{
    public int LoanId { get; set; }

    public string EmpId { get; set; }

    public byte? NoOfInstallments { get; set; }

    public DateTime? ToBeDeductedOn { get; set; }

    public decimal? AmountScheduled { get; set; }

    public int? DeductedPayrollId { get; set; }

    public int? PayrollMasterId { get; set; }

    public byte? PayrollDeductions { get; set; }

    public decimal? DeductionAmount { get; set; }

    public string SalaryDeductions { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string PaymentStatus { get; set; }

    public decimal? BalAmtTobeDeducted { get; set; }

    public string Status { get; set; }
}