// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101CurrentEmployee
{
    public string EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string EmployeeNameAr { get; set; }

    public short? Category { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public byte? Gender { get; set; }

    public DateTime? EmploymentDate { get; set; }

    public short? Nationality { get; set; }

    public short? VisaPosition { get; set; }

    public string SiteAllocated { get; set; }

    public int? Client { get; set; }

    public string Sponsor { get; set; }

    public string ContactPhone { get; set; }

    public string ContactMobile { get; set; }

    public string ContactMobile2 { get; set; }

    public string HomeAddress { get; set; }

    public string HomeCity { get; set; }

    public string HomeCountry { get; set; }

    public string ContactPerson { get; set; }

    public string ContactPersonMobile { get; set; }

    public string ContactPersonKsa { get; set; }

    public string ContactPersonKsamobile { get; set; }

    public string PassportNo { get; set; }

    public string PassportIssuedAt { get; set; }

    public DateTime? PassportIssuedOn { get; set; }

    public DateTime? PassportExpiryDate { get; set; }

    public string NationalId { get; set; }

    public string NationalIdissuedAt { get; set; }

    public DateTime? NationalIdissuedOn { get; set; }

    public DateTime? NationalIdexpiryDate { get; set; }

    public string NationalIdexpiryDateAr { get; set; }

    public byte[] EmployeePicture { get; set; }

    public string DrivingLicenceNo { get; set; }

    public DateTime? DrivingLicenceExpDate { get; set; }

    public string ProfessionalLicenceNo { get; set; }

    public DateTime? ProfessionalLicenceExpDat { get; set; }

    public short? AgencyHired { get; set; }

    public string EmployeeEmail { get; set; }

    public short? RecordAddedBy { get; set; }

    public DateTime? RecordAddedOn { get; set; }

    public short? RecordModifiedBy { get; set; }

    public DateTime? RecordModifiedOn { get; set; }

    public byte? Religion { get; set; }

    public bool? IsDiscontinued { get; set; }

    public DateTime? DiscountinuedOn { get; set; }

    public string ReasonForDiscontinued { get; set; }
}