// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101PositionsDb
{
    public int PositionId { get; set; }

    public string PositionCode { get; set; }

    public short? CostCentreCode { get; set; }

    public string CostCentreTitle { get; set; }

    public short? DepartmentCode { get; set; }

    public string Department { get; set; }

    public string JobTitle { get; set; }

    public string PositionGrade { get; set; }

    public string Grade { get; set; }
}