// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101CurrentContractsWithPosition
{
    public int ContractSlNo { get; set; }

    public string EmpId { get; set; }

    public short? ContractNo { get; set; }

    public string PositionCode { get; set; }

    public string JobTitle { get; set; }

    public string PositionNo { get; set; }

    public int? JobId { get; set; }

    public byte? GradeId { get; set; }

    public string Grade { get; set; }

    public short? CostCentreCode { get; set; }

    public string CostCentreTitle { get; set; }

    public short? DepartmentCode { get; set; }

    public string Department { get; set; }

    public string JobTitleAr { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public bool? IsEmpBilling { get; set; }

    public decimal? BillingRate { get; set; }

    public string Pono { get; set; }

    public short? CordinatorIncharge { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }

    public decimal? OvertimeRate { get; set; }

    public decimal HiringRate { get; set; }

    public bool? IsDeductHouseAllowance { get; set; }

    public bool? IsDeductTransAllowance { get; set; }

    public bool? IsDeductMobileAllowance { get; set; }

    public bool? IsDeductOtherAllowance { get; set; }

    public bool? IsDeductSpecialAllowance { get; set; }

    public int? AnnualLeave { get; set; }

    public bool IsOvertimeAllowed { get; set; }

    public byte? ContractWorkHours { get; set; }

    public bool? IsHourlyRate { get; set; }

    public decimal? HourlyRate { get; set; }

    public DateTime? QiwaContractStartDate { get; set; }

    public DateTime? QiwaContractEndDate { get; set; }
}