// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry10159ContractWithCc
{
    public string EmpId { get; set; }

    public string PositionNo { get; set; }

    public DateTime? ContractStartDate { get; set; }

    public DateTime? ContractEndDate { get; set; }

    public int? PositionJobTitle { get; set; }

    public string JobTitle { get; set; }

    public string CostCentreTitle { get; set; }

    public int ContractSlNo { get; set; }

    public bool? IsHourlyRate { get; set; }

    public decimal? HourlyRate { get; set; }

    public bool? IsEmpBilling { get; set; }

    public decimal? BillingRate { get; set; }

    public decimal? OvertimeRate { get; set; }

    public decimal? SplOvertimeRate { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }
}