// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101137payrollDeductAllOtherDeductMaster
{
    public int? PayrollMasterId { get; set; }

    public byte? PayrollDeductions { get; set; }

    public decimal? TotalOtherDeductions { get; set; }
}