// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101103002dailyLogToUpdate01
{
    public long TimeSheetId { get; set; }

    public string EmpId { get; set; }

    public DateTime? TimeSheetDate { get; set; }

    public decimal? BasicWorkHours { get; set; }

    public short? BasicWorkMinutes { get; set; }

    public string TimeSheetDay { get; set; }

    public byte? TimeSheetTemplate { get; set; }
}