// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101AbsentDeductionInsertMaster2
{
    public string EmpId { get; set; }

    public int? NoOfDays { get; set; }

    public decimal? TotalDeductions { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public int PayrollMasterId { get; set; }

    public bool IsApproved { get; set; }
}