// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101EmployeeLoanChart
{
    public int LoanId { get; set; }

    public string EmpId { get; set; }

    public DateTime? ToBeDeductedOn { get; set; }

    public decimal? AmountScheduled { get; set; }

    public decimal? LoanRepaid { get; set; }

    public int? PayrollMasterId { get; set; }

    public string Remarks { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string PaymentStatus { get; set; }

    public decimal? BalAmtTobeDeducted { get; set; }

    public decimal DeductedAmount { get; set; }

    public string PaidVoucherNo { get; set; }

    public string DeductedRentalEmpPayrollNo { get; set; }

    public decimal? TotalScheduled { get; set; }

    public decimal? LoanDeductions { get; set; }

    public string DeductionStatus { get; set; }

    public string Remarks2 { get; set; }
}