// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101110employeesDocumentsFull
{
    public short DocumentTypeId { get; set; }

    public string DocumentType { get; set; }

    public string EmployeeId { get; set; }

    public string EmployeeName { get; set; }

    public string EmployeeNameAr { get; set; }

    public bool? IsEmployeeDocument { get; set; }
}