// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101MasterPayrollPanel
{
    public int PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string EmpId { get; set; }

    public decimal TotalPayrollAdditions { get; set; }

    public decimal TotalPayrollDeductions { get; set; }

    public decimal? NetSalary { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public bool? IsPaid { get; set; }

    public DateTime? PaidOn { get; set; }

    public string PaidBy { get; set; }

    public byte? PaymentMode { get; set; }

    public bool? IsCashReceived { get; set; }

    public string CashReceivedBy { get; set; }

    public DateTime? CashReceivedOn { get; set; }

    public bool? IsContractAvailable { get; set; }

    public int? PayrollMonthId { get; set; }

    public bool? IsNoTimeSheet { get; set; }

    public byte? SalaryPostingGroupNo { get; set; }

    public string SalaryPostingGroup { get; set; }

    public bool? IsItemSelected { get; set; }

    public string PayrollNotes { get; set; }

    public string PayrollRemarks { get; set; }

    public string ProjectsAssigned { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedOn { get; set; }
}