// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101Tsfriday
{
    public byte TimeSheetGenTempId { get; set; }

    public string TimeSheetDay { get; set; }

    public decimal? WorkHoursFriday { get; set; }

    public short? Shift1StartFriday { get; set; }

    public short? Shift1EndFriday { get; set; }

    public short? Shift2StartFriday { get; set; }

    public short? Shift2EndFriday { get; set; }

    public byte? DaystatusFriday { get; set; }
}