// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101114employeeAssignment
{
    public long EmpSiteAssignmentId { get; set; }

    public string EmpId { get; set; }

    public string EmployeeName { get; set; }

    public int? ProjectId { get; set; }

    public string ProjectCode { get; set; }

    public string ProjectName { get; set; }

    public DateTime? MobilizedDate { get; set; }

    public DateTime? DemobilizedDate { get; set; }

    public string ClientCode { get; set; }

    public string ClientName { get; set; }

    public decimal? ClientRegRate { get; set; }

    public decimal? ClientOtrate { get; set; }

    public string SupplierCode { get; set; }

    public string SupplierName { get; set; }

    public decimal? SupplierRegRate { get; set; }

    public decimal? SupplierOtrate { get; set; }

    public string AssignmentRemarks { get; set; }

    public short? VisaPositionNo { get; set; }

    public string PositionAssignedAs { get; set; }

    public string CordinatorName { get; set; }

    public string RigNo { get; set; }

    public string WellNo { get; set; }

    public string Dth { get; set; }

    public string Drss { get; set; }

    public string Esvno { get; set; }

    public string Site { get; set; }

    public string Location { get; set; }

    public string Department { get; set; }

    public string BadgeNo { get; set; }

    public decimal? ClientRegRatePerDay { get; set; }

    public decimal? SupplierRegRatePerDay { get; set; }

    public short? BasicWorkHours { get; set; }

    public string ClientCcno { get; set; }

    public string TransportationKm { get; set; }

    public string ManpowerPayrollNo { get; set; }

    public string PayrollInvoiceNo { get; set; }

    public string InvoiceNo { get; set; }

    public string AssignmentPayrollStatus { get; set; }

    public string Pono { get; set; }

    public string ContractNo { get; set; }

    public string Expr1 { get; set; }

    public string CategoryTitle { get; set; }

    public string VisaPositionTitle { get; set; }

    public string WorkSite { get; set; }

    public string SponsorName { get; set; }

    public string PositionTitle { get; set; }

    public DateTime? TsreceivedOn { get; set; }

    public DateTime? TssubmittedOn { get; set; }

    public DateTime? TscollectedOn { get; set; }

    public string TscollectedBy { get; set; }

    public DateTime? AssgContReceivedOn { get; set; }

    public DateTime? AssgContSubmittedOn { get; set; }

    public DateTime? AssgContCollectedOn { get; set; }

    public string EmployeeGroup { get; set; }

    public string CostCentreTitle { get; set; }

    public string Expr2 { get; set; }

    public DateTime? QiwaContractStartDate { get; set; }

    public DateTime? QiwaContractEndDate { get; set; }
}