// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry10178LoansGivenBeforeAdate
{
    public int LoanId { get; set; }

    public string EmpId { get; set; }

    public DateTime? LoanAppliedOn { get; set; }

    public decimal? LoanSanctionedAmount { get; set; }

    public int? InstallmentStartMonthId { get; set; }

    public DateTime? MonthSelectedDateFrom { get; set; }
}