// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry10143SundryDebtor
{
    public string AccountId { get; set; }

    public string AccountHead { get; set; }

    public string AccountGroup { get; set; }

    public string AccountsContactName { get; set; }

    public string AccountsContactMobile { get; set; }

    public string AccountsContactTitle { get; set; }

    public string BillingContactPerson { get; set; }

    public string BillingContactPersonTitle { get; set; }

    public string EmailAddress { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string BankAccountNo { get; set; }

    public string BankIban { get; set; }

    public string BankName { get; set; }

    public string BankBranch { get; set; }

    public string BankSwiftCode { get; set; }

    public string BankAccountName { get; set; }

    public string AccountHeadArabic { get; set; }

    public string BillingNameAr { get; set; }

    public string BillingAddressAr { get; set; }

    public string VatregistrationNo { get; set; }

    public string BankNameAr { get; set; }

    public string BankAccountNameAr { get; set; }

    public string ClientVendorNo { get; set; }

    public string BankBranchAr { get; set; }

    public string AccountGroupId { get; set; }

    public string MasterGroupId { get; set; }
}