// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry10139BillingMaster
{
    public int PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string EmployeeNo { get; set; }

    public string EmployeeName { get; set; }

    public decimal? FullTotal { get; set; }

    public decimal? SalaryTotal { get; set; }

    public decimal? Hratotal { get; set; }

    public decimal? TotalAdditions { get; set; }

    public decimal? TotalDeductions { get; set; }

    public decimal? TotalPayableHours { get; set; }

    public decimal? TotalOvertimeHours { get; set; }

    public decimal? TotalRegHours { get; set; }

    public string JobTitle { get; set; }

    public string CostCentreTitle { get; set; }

    public string SponsorName { get; set; }

    public decimal? BillingRate { get; set; }

    public string Pono { get; set; }

    public short? CordinatorIncharge { get; set; }

    public bool? IsEmpBilling { get; set; }

    public decimal? SplOvertimeHours { get; set; }

    public decimal? OvertimeRate { get; set; }

    public decimal? SplOvertimeRate { get; set; }

    public decimal? HourlyRate { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }
}