// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry101103001timesheetDailyLog
{
    public long TimeSheetId { get; set; }

    public string EmpId { get; set; }

    public DateTime? TimeSheetDate { get; set; }

    public DateTime? StartTimeShift1 { get; set; }

    public DateTime? EndTimeShift1 { get; set; }

    public DateTime? StartTimeShift2 { get; set; }

    public DateTime? EndTimeShift2 { get; set; }

    public decimal? BasicWorkHours { get; set; }

    public byte? WorkStatus { get; set; }

    public short? BasicWorkMinutes { get; set; }

    public int? ProjectId { get; set; }

    public short? BonusMinutes { get; set; }

    public short? TotalHoursM { get; set; }

    public string TimesheetDayRemarks { get; set; }

    public string EmployeeName { get; set; }

    public string ProjectName { get; set; }

    public int? ProjectGroupId { get; set; }

    public string ProjectGroupName { get; set; }

    public string EmployeeGroup { get; set; }

    public string PayrollStatus { get; set; }

    public int PayrollStatusCode { get; set; }

    public long? EmpSiteAssignmentId { get; set; }

    public string ClientCode { get; set; }

    public string AccountHead { get; set; }
}