// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201602vatinvoiceReport
{
    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public DateTime? InvoiceEffectiveDate { get; set; }

    public string InvoiceDateAr { get; set; }

    public DateTime? InvoiceDeliveryDate { get; set; }

    public string InvoiceDeliveryDateAr { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string BankAccountNo { get; set; }

    public string BankIban { get; set; }

    public string BankName { get; set; }

    public string BankBranch { get; set; }

    public string BankSwiftCode { get; set; }

    public string BankAccountName { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public string GsdescriptionAr { get; set; }

    public string UoM { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public decimal? UnitsToBill { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public decimal? UnitRate { get; set; }

    public string DetailedDescription { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public string TaxSlab { get; set; }

    public string TaxSlabAr { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TotalInvoiceAmount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public string Pono { get; set; }

    public DateTime? Podate { get; set; }

    public string PodateAr { get; set; }

    public string BillingNameAr { get; set; }

    public string BillingAddressAr { get; set; }

    public string VatregistrationNo { get; set; }

    public decimal? CalcLineTotalWithTax { get; set; }

    public string QuotationNo { get; set; }

    public string DeliveryNoteNos { get; set; }

    public string ReferenceNo { get; set; }

    public string SosreferenceNo { get; set; }

    public string RemarksInEn { get; set; }

    public string RemarksInAr { get; set; }

    public string ClientVatnoAr { get; set; }

    public string CompanyVatno { get; set; }

    public string OurVatnoAr { get; set; }

    public string InvoiceNoAr { get; set; }

    public string BankNameAr { get; set; }

    public string BankAccountNameAr { get; set; }

    public string BankAccountNoAr { get; set; }

    public string PlateNo { get; set; }

    public string ModelNo { get; set; }

    public string TypeOfVehicle { get; set; }

    public string Kilometer { get; set; }

    public string ClientVendorNo { get; set; }

    public decimal AdvanceAmount { get; set; }

    public decimal RetentionAmount { get; set; }

    public decimal? BalanceDueAmount { get; set; }

    public string AdvanceText { get; set; }

    public string RetentionText { get; set; }

    public string AdvanceTextAr { get; set; }

    public string RetentionTextAr { get; set; }

    public decimal Discount { get; set; }

    public decimal? CalcLineAmountBeforeDiscount { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalInvoiceAmountBeforeDiscount { get; set; }

    public DateTime? InvoiceStartDate { get; set; }

    public DateTime? InvoiceEndDate { get; set; }

    public DateTime? InvoiceDueDate { get; set; }

    public byte? Currency { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? CalcLineAmountOc { get; set; }

    public decimal? CalcTaxAmountOc { get; set; }

    public decimal? CalcLineAmtB4discOc { get; set; }

    public decimal? UnitRateInOc { get; set; }

    public decimal? DiscountInOc { get; set; }

    public decimal? CalcLineTotalWithTaxInOc { get; set; }

    public decimal? BalanceDueAmountInOc { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencyCodeAr { get; set; }

    public string CurrencyNameAr { get; set; }

    public decimal? TotalInvoiceAmountInOc { get; set; }

    public decimal? TotalTaxAmountInOc { get; set; }

    public decimal? TotalWithTaxInOc { get; set; }

    public decimal? TotalDiscountInOc { get; set; }

    public decimal? TotalInvAmtB4discOc { get; set; }

    public string UnitsToBillInAr { get; set; }

    public string QtyInAr { get; set; }

    public string UnitRateAr { get; set; }

    public string CalcLineAmountAr { get; set; }

    public string CalcTaxAmountAr { get; set; }

    public string CalcLineTotalWithTaxAr { get; set; }

    public string TotalInvoiceAmountAr { get; set; }

    public string TotalTaxAmountAr { get; set; }

    public string TotalWithTaxAr { get; set; }

    public string BalanceDueAmountAr { get; set; }

    public string AdvanceAmountAr { get; set; }

    public string RetentionAmountAr { get; set; }

    public string TaxRateAr { get; set; }

    public string CompanyName { get; set; }

    public string CompanyAddress1 { get; set; }

    public string CompanyNameAr { get; set; }

    public string CompanyAddress1Ar { get; set; }

    public string CompanyFullAddress { get; set; }

    public string CompanyFullAddressAr { get; set; }

    public string BankBranchAr { get; set; }

    public string InvoicePreparedBy { get; set; }

    public string InvoiceCheckedBy { get; set; }

    public string InvoiceApprovedBy { get; set; }

    public byte[] InvoicePreparedBySign { get; set; }

    public byte[] InvoiceCheckedBySign { get; set; }

    public byte[] InvoiceApprovedBySign { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string UnitDescAr { get; set; }

    public string InvoiceAbbrv { get; set; }

    public string InvoiceNoWtAbbr { get; set; }

    public string AccountId { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string BatchNo { get; set; }

    public string ExpiryDateFormatted { get; set; }

    public string ClientNameOrCashClient { get; set; }

    public string ClientVatorCashClientVat { get; set; }

    public string ClientNameArOrCashClientAr { get; set; }

    public string ClientVatorCashClientVatar { get; set; }

    public string DetailedDescriptionAr { get; set; }

    public string BankIbanar { get; set; }

    public string InvDateAr { get; set; }

    public string SupplyDateAr { get; set; }

    public string InvDueDateAr { get; set; }

    public string PonoAr { get; set; }

    public string ReferenceNoAr { get; set; }

    public string SosReferenceNoAr { get; set; }

    public string ClientVendorNoAr { get; set; }

    public string InvoicePreparedByAr { get; set; }

    public string InvoicePreparedByPosAr { get; set; }

    public string InvoiceCheckedByAr { get; set; }

    public string InvoiceCheckedByPosAr { get; set; }

    public string InvoiceApprovedByAr { get; set; }

    public string InvoiceApprovedByPosAr { get; set; }

    public string InvoicePreparedByPos { get; set; }

    public string InvoiceCheckedByPos { get; set; }

    public string InvoiceApprovedByPos { get; set; }

    public string InvoiceNoArRev { get; set; }

    public string TotalInvoiceAmountBeforeDiscountAr { get; set; }

    public string TotalDiscountAr { get; set; }

    public string DiscountAr { get; set; }

    public string PaymentTerms { get; set; }

    public string InvoiceUuid { get; set; }

    public short? InvoiceTypeCode { get; set; }

    public string InvoiceTransactionCode { get; set; }

    public string InvoiceTypeCodeSubType { get; set; }

    public bool? IsThirdParty { get; set; }

    public bool? IsNominal { get; set; }

    public bool? IsExport { get; set; }

    public bool? IsSummary { get; set; }

    public bool? IsSelfBilled { get; set; }

    public long? InvoiceCounterValue { get; set; }

    public string InvoiceCurrencyCode { get; set; }

    public string TaxCurrencyCode { get; set; }

    public string SellerGroupVatnumber { get; set; }

    public string SellerOtherIdtype { get; set; }

    public string SellerOtherSellerId { get; set; }

    public string SellerAddressStreet { get; set; }

    public string SellerAddressStreetAr { get; set; }

    public string SellerAdditionalStreet { get; set; }

    public string SellerAdditionalStreetAr { get; set; }

    public string SellerBuildingNumber { get; set; }

    public string SellerAdditionalNumber { get; set; }

    public string SellerCity { get; set; }

    public string SellerCityAr { get; set; }

    public string SellerPostalCode { get; set; }

    public string SellerProvince { get; set; }

    public string SellerProvinceAr { get; set; }

    public string SellerNeighborhood { get; set; }

    public string SellerNeighborhoodAr { get; set; }

    public string SellerCountryCode { get; set; }

    public string SellerVatnumber { get; set; }

    public string SellerName { get; set; }

    public string SellerNameAr { get; set; }

    public string BuyerGroupVatnumber { get; set; }

    public string BuyerOtherIdtype { get; set; }

    public string BuyerOtherId { get; set; }

    public string BuyerAddressStreet { get; set; }

    public string BuyerAddressStreetAr { get; set; }

    public string BuyerAdditionalStreet { get; set; }

    public string BuyerAdditionalStreetAr { get; set; }

    public string BuyerBuildingNumber { get; set; }

    public string BuyerAdditionalNumber { get; set; }

    public string BuyerCity { get; set; }

    public string BuyerCityAr { get; set; }

    public string BuyerPostalCode { get; set; }

    public string BuyerProvince { get; set; }

    public string BuyerProvinceAr { get; set; }

    public string BuyerNeighborhood { get; set; }

    public string BuyerNeighborhoodAr { get; set; }

    public string BuyerCountryCode { get; set; }

    public string BuyerVatnumber { get; set; }

    public string BuyerName { get; set; }

    public string BuyerNameAr { get; set; }

    public byte? PaymentMeansTypeCode { get; set; }

    public string ReasonforIssuanceOfCrn { get; set; }

    public string ReasonforIssuanceOfCrnar { get; set; }

    public string PaymentTerms1 { get; set; }

    public string PaymentTermsAr { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public string SellerBuildingNumberAr { get; set; }

    public string SellerAdditionalNumberAr { get; set; }

    public string SellerPostalCodeAr { get; set; }

    public string SellerVatnumberAr { get; set; }

    public string SellerOtherSellerIdar { get; set; }

    public string BuyerVatnumberAr { get; set; }

    public string BuyerPostalCodeAr { get; set; }

    public string BuyerAdditionalNumberAr { get; set; }

    public string BuyerBuildingNumberAr { get; set; }

    public string BuyerOtherIdar { get; set; }

    public string ClientAdditionalStreetAr { get; set; }

    public string LedgerReferenceNo { get; set; }

    public string BuyerCountryName { get; set; }

    public string SellerCountryName { get; set; }

    public string BuyerCountryNameArabic { get; set; }

    public string SellerCountryNameArabic { get; set; }

    public string DiscountText { get; set; }

    public string DiscountTextArabic { get; set; }

    public byte? UnitCode { get; set; }

    public decimal? AdvanceAmountInOc { get; set; }

    public decimal? RetentionAmountInOc { get; set; }

    public decimal? BalanceDueWthConvertedAdvAndRetention { get; set; }

    public string ItemPartNo { get; set; }

    public decimal OtherDeductionAmount { get; set; }

    public string OtherDeductionText { get; set; }

    public string OtherDeductionTextAr { get; set; }

    public decimal? OtherDeductionAmountInOc { get; set; }

    public int? InvoiceChildSlNo { get; set; }

    public decimal? IssuedInvoiceCostPrice { get; set; }

    public decimal? CurrentQtyOnPosting { get; set; }

    public decimal? TaxRateIn100 { get; set; }

    public string TaxCodeInZatca { get; set; }

    public string PaymentMeansType { get; set; }

    public string PaymentDescription { get; set; }

    public string BadgeNo { get; set; }

    public string Dthno { get; set; }

    public string Drssno { get; set; }

    public string SesreferenceNo { get; set; }

    public string InvoicingMode { get; set; }

    public string InvoicingModeAr { get; set; }

    public string EmployeeName { get; set; }

    public string EmployeeNameAr { get; set; }

    public string JobTitle { get; set; }

    public string JobTitleAr { get; set; }

    public string NationalityEn { get; set; }

    public string NationalityAr { get; set; }

    public string Department { get; set; }

    public string DepartmentArabic { get; set; }

    public DateTime? ItemServiceStartDate { get; set; }

    public DateTime? ItemServiceEndDate { get; set; }

    public string CostCenterCode { get; set; }

    public string VisaPositionTitle { get; set; }

    public string VisaPositionTitleAr { get; set; }

    public string ClientCcno { get; set; }

    public string InvoicePeriodInText { get; set; }

    public DateTime? InventoryEffectiveDate { get; set; }

    public string TaxCodeToDisplay { get; set; }

    public string EmployeeNoInChild { get; set; }

    public string PropertyNo { get; set; }

    public string TaxExemptionReasonCode { get; set; }

    public string EmployeeNoInMaster { get; set; }

    public string CountryOfOrigin { get; set; }

    public string ItemMake { get; set; }

    public string CompanyTin { get; set; }

    public string ClientTin { get; set; }

    public string InvoicePeriodInText02 { get; set; }

    public string InvoiceCurrencyNote { get; set; }

    public string InvoiceCurrencyPoints { get; set; }

    public string EmpNameInLineItem { get; set; }

    public string EmpNameArInLineItem { get; set; }

    public string EmpIdinLineItem { get; set; }

    public decimal? BalanceDueAmountBhd { get; set; }

    public string SellerAddress001 { get; set; }

    public string SellerAddress002 { get; set; }

    public string SellerIdnos { get; set; }

    public decimal TotalAdjustedInclusiveAmount { get; set; }

    public decimal? InvoiceTotalPayableAmount { get; set; }

    public decimal TotalAdjustedInclusiveAmountInSar { get; set; }

    public decimal? InvoiceTotalPayableAmountInOc { get; set; }

    public decimal? InvoiceTotalPayableAmountInSar { get; set; }

    public string SubmittedInvoiceUuid { get; set; }

    public string ClientGrnreferenceNo { get; set; }
}