// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201718vatpurchaseBillReport
{
    public string PurchaseVoucherNo { get; set; }

    public DateTime? PurchaseVoucherDate { get; set; }

    public string SupplierCode { get; set; }

    public string AccountHead { get; set; }

    public string PurchaseBillNo { get; set; }

    public DateTime? PurchaseBillDate { get; set; }

    public string PurchaseOrderNo { get; set; }

    public DateTime? PurchaseOrderDate { get; set; }

    public string MaterialReceiptNo { get; set; }

    public DateTime? MaterialReceiptDate { get; set; }

    public string ItemCode { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public decimal? UnitsToBill { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? Discount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public decimal? LineAmount { get; set; }

    public string Gsdescrpition { get; set; }

    public decimal? TotalAfterDiscount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalPurchaseAmount { get; set; }

    public decimal? TotalDiscount { get; set; }

    public string SupplierVatno { get; set; }

    public DateTime? PurchaseDueDate { get; set; }

    public string SupplierNameOnCashPurchase { get; set; }

    public string SupplierVatonCashPurchase { get; set; }

    public string SupplierVatorCashSupplierVat { get; set; }

    public string SupplierAddress { get; set; }

    public string SupplierNameOrCashSupplier { get; set; }

    public decimal? UnitRate { get; set; }

    public string DetailedDescription { get; set; }

    public decimal? TotalWithDiscount { get; set; }

    public decimal? LineTotalWithDiscount { get; set; }

    public decimal TotalWithTaxAfterDiscount { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public byte? UnitCode { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public decimal? RetentionAmount { get; set; }

    public string AdvanceText { get; set; }

    public string RetentionText { get; set; }

    public decimal? TotalWtTaxAfterDiscAndDeductions { get; set; }

    public string DiscountText { get; set; }

    public string EmployeeNo { get; set; }

    public string PropertyNo { get; set; }
}