// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201804vatcreditNoteWtClassified
{
    public string CreditNoteNo { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? DomesticStandartRatedRevenue { get; set; }

    public decimal? DomesticZeroRatedRevenue { get; set; }

    public decimal? DomesticExemptedRevenue { get; set; }

    public decimal? GccstandardRatedRevenue { get; set; }

    public decimal? ExportsRevenue { get; set; }

    public decimal? DomesticStandartRatedTax { get; set; }

    public decimal? DomesticZeroRatedTax { get; set; }

    public decimal? DomesticExemptedTax { get; set; }

    public decimal? GccstandardRatedTax { get; set; }

    public decimal? ExportsTax { get; set; }

    public decimal? TotalCreditNoteAmount { get; set; }

    public decimal? RevenueOf15Per { get; set; }

    public decimal? TaxOf15Per { get; set; }

    public decimal? RevenueOf10Per { get; set; }

    public decimal? TaxOf10Per { get; set; }
}