// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201715vatpurchaseReturnsMaster
{
    public string PurchaseVoucherNo { get; set; }

    public DateTime? PurchaseVoucherDate { get; set; }

    public decimal? DomesticStandardPurchases { get; set; }

    public decimal? DomesticZeroTaxPurchases { get; set; }

    public decimal? DomesticExemptedTaxPurchases { get; set; }

    public decimal? ImportsVatpaidAtCustoms { get; set; }

    public decimal? ImportsVatthruRcm { get; set; }

    public decimal? DomesticStandardPurTax { get; set; }

    public decimal? DomesticZeroTaxPurTax { get; set; }

    public decimal? DomesticExemptedTaxPurTax { get; set; }

    public decimal? ImportsVatpaidAtCustomsTax { get; set; }

    public decimal? ImportsVatthruRcmtax { get; set; }

    public decimal? TotalPurchaseAmount { get; set; }

    public string Vatgroup { get; set; }

    public decimal? TotalDspurchase15Perc { get; set; }

    public decimal? TotalImportPurchase15Perc { get; set; }

    public decimal? TotalRcmpurchase15Perc { get; set; }

    public decimal? TotalDspurchaseTax15Perc { get; set; }

    public decimal? TotalImportPurchaseTax15Perc { get; set; }

    public decimal? TotalRcmpurchaseTax15Perc { get; set; }

    public decimal? TotalDspurchase10Perc { get; set; }

    public decimal? TotalDspurchaseTax10Perc { get; set; }

    public decimal? TotalImportPurchase10Perc { get; set; }

    public decimal? TotalImportPurchaseTax10Perc { get; set; }

    public decimal? TotalRcmpurchase10Perc { get; set; }

    public decimal? TotalRcmpurchaseTax10Perc { get; set; }
}