// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201101mainVoucherEntriesForAcctBalance
{
    public string AccountHead { get; set; }

    public string AccountHeadName { get; set; }

    public string AccountHeadArabic { get; set; }

    public decimal? VoucherAmountFormatted { get; set; }

    public string AccountsContactName { get; set; }

    public string AccountsContactMobile { get; set; }

    public string AccountsContactTitle { get; set; }

    public string EmailAddress { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string BillingNameAr { get; set; }

    public string BillingAddressAr { get; set; }

    public string SupplierName { get; set; }

    public string SupplierNameAr { get; set; }

    public string SupplierAddress { get; set; }

    public string SupplierAddressAr { get; set; }

    public DateTime VoucherDate { get; set; }

    public string ClientVendorNo { get; set; }
}