// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20192ExpensesClaimEntriesToCheck
{
    public string ClaimRefNo { get; set; }

    public decimal? ApprovedAmount { get; set; }

    public bool? IsTaxIncluded { get; set; }

    public decimal? TaxableAmount { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? RoundOff { get; set; }

    public decimal? AccountableAmount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public string MatchingStatus { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public string TaxStatus { get; set; }

    public string AccountId { get; set; }

    public string BillRefNo { get; set; }

    public string ExpenseDescription { get; set; }

    public decimal? TaxRate { get; set; }

    public string TaxRateInWord { get; set; }

    public long ClaimChildNo { get; set; }
}