// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20188PostExpClaimEntryChecking
{
    public string ClaimRefNo { get; set; }

    public decimal? TotalExpenses { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalRoundOff { get; set; }

    public decimal? TotalPayableAmount { get; set; }

    public decimal? TotalDebitAmount { get; set; }

    public decimal? TotalCreditAmount { get; set; }

    public decimal? DifferenceInPosting { get; set; }
}