// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20136VoucherMasterList
{
    public string VoucherNo { get; set; }

    public DateTime VoucherDate { get; set; }

    public string VoucherRefNo { get; set; }

    public string VoucherNarration { get; set; }

    public string VoucherEnteredBy { get; set; }

    public DateTime? VoucherEnteredOn { get; set; }

    public bool IsVerified { get; set; }

    public string VoucherVerifiedBy { get; set; }

    public DateTime? VoucherVerifiedOn { get; set; }

    public bool IsApproved { get; set; }

    public string VoucherApprovedBy { get; set; }

    public DateTime? VoucherApprovedOn { get; set; }

    public string VoucherType { get; set; }

    public DateTime? VoucherEffectiveDate { get; set; }

    public string VoucherModifiedBy { get; set; }

    public DateTime? VoucherModifiedOn { get; set; }

    public decimal? DebitAmount { get; set; }

    public decimal? CreditAmount { get; set; }

    public string AuditVerifiedBy { get; set; }

    public DateTime? AuditVerifiedOn { get; set; }

    public bool IsAuditVerified { get; set; }
    public decimal? ConvertedDrAmount { get; set; }
    public decimal? ConvertedCrAmount { get; set; }
    public string CurrencyName { get; set; }
    public string TransactionCurrencySymbol { get; set; }
    public string CurrencyImage { get; set; }
}