// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry210006itemsWithLastPurchasedDate
{
    public DateTime? PurchaseVoucherDate { get; set; }

    public string ItemCode { get; set; }
}