// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201901vatdebitNoteChild
{
    public long DebitNoteChildSlNo { get; set; }

    public string DebitNoteNo { get; set; }

    public string ItemCode { get; set; }

    public string UoM { get; set; }

    public decimal? QuantityDebited { get; set; }

    public decimal? UnitsToDebited { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? UnitRate { get; set; }

    public string DetailedDescription { get; set; }

    public byte? TaxSlabCode { get; set; }

    public decimal? TaxAmount { get; set; }

    public byte? Currency { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? UnitRateInOc { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? Discount { get; set; }

    //public string CurrencyImage { get; set; }
    //public string CurrencySymbole { get; set; }
}