// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry202101journalRegisterChild
{
    public long JournalChildNo { get; set; }

    public string JournalRefNo { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string AccountId { get; set; }

    public string DrCr { get; set; }

    public string EntryNarration { get; set; }

    public decimal? DrAmount { get; set; }

    public decimal? CrAmount { get; set; }

    public string AccountHead { get; set; }

    public string CostAllocationDescription { get; set; }

    public string EmployeeCostDescription { get; set; }

    public string PropertyCostDescription { get; set; }

    public decimal? FormattedAmount { get; set; }

    public decimal? TotalCostAllocated { get; set; }

    public decimal? TotalEmpAllocated { get; set; }

    public decimal? TotalEqpAllocted { get; set; }
}