// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20152AccountGroupsWithMasterGroup
{
    public string AccountGroupId { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }
}