// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20159ProfitLossStatement
{
    public string AccountHead { get; set; }

    public string AccountHeadName { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroup { get; set; }

    public decimal? VoucherTotal { get; set; }

    public string MonthYearEffectiveDate { get; set; }

    public string EffectiveDateMonth { get; set; }

    public DateTime? VoucherEffectiveDate { get; set; }

    public decimal? MasterOrderNo { get; set; }

    public string MonthYearVoucherDate { get; set; }

    public string VoucherDateMonth { get; set; }

    public DateTime? VoucherDate { get; set; }

    public string AccountGroupId { get; set; }

    public string MasterGroupId { get; set; }
}