// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201632EInvoiceToXmlchildLineItem
{
    public string InvoiceNo { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public string UnitDesc { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public decimal? UnitRate { get; set; }

    public decimal? CalcLineAmountBeforeDiscount { get; set; }

    public decimal Discount { get; set; }

    public decimal? LineTaxExclusiveAmount { get; set; }

    public decimal? LineExtensionAmount { get; set; }

    public decimal? LineAllowanceCharges { get; set; }

    public decimal? LineTaxAmount { get; set; }

    public string UnitType { get; set; }

    public string TaxSlab { get; set; }

    public string TaxSlabAr { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? TotalInvoiceAmount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public decimal? CalcLineTotalWithTax { get; set; }

    public decimal AdvanceAmount { get; set; }

    public decimal RetentionAmount { get; set; }

    public decimal? BalanceDueAmount { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalInvoiceAmountBeforeDiscount { get; set; }

    public byte? Currency { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? LineTaxExclusiveAmountOc { get; set; }

    public decimal? CalcTaxAmountOc { get; set; }

    public decimal? CalcLineAmtB4discOc { get; set; }

    public decimal? UnitRateInOc { get; set; }

    public decimal? DiscountInOc { get; set; }

    public decimal? CalcLineTotalWithTaxInOc { get; set; }

    public decimal? BalanceDueAmountInOc { get; set; }

    public decimal? TotalInvoiceAmountInOc { get; set; }

    public decimal? TotalTaxAmountInOc { get; set; }

    public decimal? TotalWithTaxInOc { get; set; }

    public decimal? TotalDiscountInOc { get; set; }

    public decimal? TotalInvAmtB4discOc { get; set; }

    public decimal? LineOrderNo { get; set; }

    public decimal? TaxRateIn100 { get; set; }

    public string TaxCodeInZatca { get; set; }

    public int? InvoiceChildSlNo { get; set; }

    public decimal? LineExtensionAmountOc { get; set; }

    public decimal? LineAllowanceChargesOc { get; set; }

    public decimal? LineTaxAmountOc { get; set; }

    public decimal? CalcLineAmountOc { get; set; }

    public string TaxExemptionReasonCode { get; set; }

    public string ItemDescriptionAr { get; set; }
}