// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201706vatpurchaseRegisterMain
{
    public string PurchaseVoucherNo { get; set; }

    public DateTime? PurchaseVoucherDate { get; set; }

    public string SupplierCode { get; set; }

    public string AccountHead { get; set; }

    public string PurchaseBillNo { get; set; }

    public DateTime? PurchaseBillDate { get; set; }

    public DateTime? PurchaseEffectiveDate { get; set; }

    public DateTime? PurchaseDeliveryDate { get; set; }

    public string PurchasePeriod { get; set; }

    public byte? TypeOfPurchase { get; set; }

    public string PurchaseOrderNo { get; set; }

    public DateTime? PurchaseOrderDate { get; set; }

    public string MaterialReceiptNo { get; set; }

    public DateTime? MaterialReceiptDate { get; set; }

    public string ReferenceNo { get; set; }

    public string Remarks { get; set; }

    public string RemarksAr { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public byte? PurchaseTaxCategoryCode { get; set; }

    public string PurchaseLedgerAccountNo { get; set; }

    public string CostCenterCode { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedBy { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public bool? IsPosted { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedOn { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public decimal? DomesticStandardPurchases { get; set; }

    public decimal? DomesticZeroTaxPurchases { get; set; }

    public decimal? DomesticExemptedTaxPurchases { get; set; }

    public decimal? ImportsVatpaidAtCustoms { get; set; }

    public decimal? ImportsVatthruRcm { get; set; }

    public decimal? DomesticStandardPurTax { get; set; }

    public decimal? DomesticZeroTaxPurTax { get; set; }

    public decimal? DomesticExemptedTaxPurTax { get; set; }

    public decimal? ImportsVatpaidAtCustomsTax { get; set; }

    public decimal? ImportsVatthruRcmtax { get; set; }

    public decimal? TotalPurchaseAmount { get; set; }

    public string SupplierVatno { get; set; }

    public string AccountGroupId { get; set; }

    public string SupplierAddressAr { get; set; }

    public string SupplierNameAr { get; set; }

    public DateTime? PurchaseDueDate { get; set; }

    public DateTime? SupplierInvRecdOn { get; set; }

    public string SupplierInvRecdBy { get; set; }

    public string PurchaseLedgerName { get; set; }

    public string PurchaseAccountGroupName { get; set; }

    public string PurchaseAccountMasterName { get; set; }

    public string SupplierNameInCash { get; set; }

    public string SupplierVatinCash { get; set; }

    public string SupplierNameInCashAr { get; set; }

    public string CashOrSupplierIdgroup { get; set; }

    public string PurchaseAccountMasterGroupId { get; set; }

    public string AccountHeadArabic { get; set; }

    public decimal? TotalQtyInvoiced { get; set; }

    public string CostAllocationUnit { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocationMasterGroup { get; set; }

    public string CostCenterIncharge { get; set; }

    public decimal? TotalDspurchase15Perc { get; set; }

    public decimal? TotalImportPurchase15Perc { get; set; }

    public decimal? TotalRcmpurchase15Perc { get; set; }

    public decimal? TotalDspurchaseTax15Perc { get; set; }

    public decimal? TotalImportPurchaseTax15Perc { get; set; }

    public decimal? TotalRcmpurchaseTax15Perc { get; set; }

    public string SupplierAddress { get; set; }

    public string SupplierGroupVatnumber { get; set; }

    public string SupplierOtherIdtype { get; set; }

    public string SupplierOtherId { get; set; }

    public string SupplierAddressStreet { get; set; }

    public string SupplierAddressStreetAr { get; set; }

    public string SupplierAdditionalStreet { get; set; }

    public string SupplierAdditionalStreetAr { get; set; }

    public string SupplierBuildingNumber { get; set; }

    public string SupplierAdditionalNumber { get; set; }

    public string SupplierCity { get; set; }

    public string SupplierCityAr { get; set; }

    public string SupplierPostalCode { get; set; }

    public string SupplierProvince { get; set; }

    public string SupplierProvinceAr { get; set; }

    public string SupplierNeighborhood { get; set; }

    public string SupplierNeighborhoodAr { get; set; }

    public string SupplierCountryCode { get; set; }

    public string SupplierVatnumber { get; set; }

    public string SupplierName { get; set; }

    public string SupplierNameAr002 { get; set; }

    public decimal? AdvanceAmount { get; set; }

    public decimal? RetentionAmount { get; set; }

    public string AdvanceText { get; set; }

    public string RetentionText { get; set; }

    public byte? CompanyId { get; set; }

    public string CompanyName { get; set; }

    public string BranchName { get; set; }

    public string BranchCode { get; set; }

    public string DiscountText { get; set; }

    public DateTime? InventoryEffectiveDate { get; set; }

    public decimal? TotalDspurchase10Perc { get; set; }

    public decimal? TotalDspurchaseTax10Perc { get; set; }

    public decimal? TotalImportPurchase10Perc { get; set; }

    public decimal? TotalImportPurchaseTax10Perc { get; set; }

    public decimal? TotalRcmpurchase10Perc { get; set; }

    public decimal? TotalRcmpurchaseTax10Perc { get; set; }

    public decimal? Discount { get; set; }
}