// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201646adjustedInvoiceForInvoiceReportFc
{
    public string EInvoiceNo { get; set; }

    public decimal AdjustedAmount { get; set; }

    public byte? TaxSlabCode { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? AdjustedTaxAmount { get; set; }

    public decimal? AdjustedInclusiveAmount { get; set; }

    public string CurrencyMasterCode { get; set; }

    public decimal? ExchangeRate { get; set; }

    public decimal? AdjustedAmountInSar { get; set; }

    public decimal? AdjustedTaxAmountInSar { get; set; }

    public decimal? AdjustedInclusiveAmountInSar { get; set; }
}