// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201647prepaidOpBalInvoiceMaster
{
    public string AdvanceOpBalInvoiceNo { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public string ClientCode { get; set; }

    public string InvoiceStatus { get; set; }

    public int InvoiceTypeCode { get; set; }

    public string SubmittedInvoiceUuid { get; set; }

    public string CurrencyMasterCode { get; set; }

    public decimal? ExchangeRate { get; set; }

    public string TaxCodeInZatca { get; set; }

    public decimal? TaxRateIn100 { get; set; }

    public decimal? BalanceAmountInSar { get; set; }

    public decimal? BalanceTaxAmountInSar { get; set; }

    public decimal? BalanceAmountWtTaxInSar { get; set; }

    public decimal BalanceAmountInFc { get; set; }

    public decimal? BalanceTaxAmountInFc { get; set; }

    public decimal? BalanceAmountWtTaxInFc { get; set; }
}