// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201SubLedgerAllDr
{
    public string AccountHeadNo { get; set; }

    public string AccountHead { get; set; }

    public string ReferenceNo { get; set; }

    public decimal? AmountDr { get; set; }

    public string DrCr { get; set; }

    public decimal? RetentionAmount { get; set; }
}