// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201204depreciationChildTotal
{
    public string DepreciationDocNo { get; set; }

    public decimal? AssetOpeningBalance { get; set; }

    public decimal? AssetTotalDebitTrans { get; set; }

    public decimal? AssetTotalCreditTrans { get; set; }

    public decimal? AssetClosingBalance { get; set; }

    public decimal? TotalDepreciationAmount { get; set; }

    public decimal? AccumulatedOpeningBalance { get; set; }

    public decimal? AccumulatedTotalBalance { get; set; }

    public decimal? TotalBookValue { get; set; }

    public int? NoOfAssets { get; set; }

    public decimal? Expr1 { get; set; }
}