// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201916vatdebitNoteReturn
{
    public string Vatgroup { get; set; }

    public string DocumentNo { get; set; }

    public DateTime? DocumentDate { get; set; }

    public decimal? DssDebitNote { get; set; }

    public decimal? DzrDebitNote { get; set; }

    public decimal? DexDebitNote { get; set; }

    public decimal? IpcDebitNote { get; set; }

    public decimal? RcmDebitNote { get; set; }

    public decimal? DssDebitTax { get; set; }

    public decimal? IpcDebitTax { get; set; }

    public decimal? RcmDebitTax { get; set; }

    public decimal? Dss15perDebitNote { get; set; }

    public decimal? Ipc15perDebitNote { get; set; }

    public decimal? Rcm15perDebitNote { get; set; }

    public decimal? Dss15perDebitTax { get; set; }

    public decimal? Ipc15perDebitTax { get; set; }

    public decimal? Rcm15perDebitTax { get; set; }

    public decimal? Dss10perDebitNote { get; set; }

    public decimal? Ipc10perDebitNote { get; set; }

    public decimal? Rcm10perDebitNote { get; set; }

    public decimal? Dss10perDebitTax { get; set; }

    public decimal? Ipc10perDebitTax { get; set; }

    public decimal? Rcm10perDebitTax { get; set; }
}