// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201646adjustedInvoicesToDisplay002
{
    public long PrepaidAdjInvoiceSlNo { get; set; }

    public string EInvoiceNo { get; set; }

    public string PrepaidInvoiceNo { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public string ClientCode { get; set; }

    public string InvoiceStatus { get; set; }

    public int? InvoiceTypeCode { get; set; }

    public string SubmittedInvoiceUuid { get; set; }

    public decimal? AdjustedAmount { get; set; }

    public decimal? TaxRate { get; set; }

    public decimal? AdjustedTaxAmount { get; set; }

    public decimal? AdjustedInclusiveAmount { get; set; }

    public byte? TaxSlabCode { get; set; }

    public string TaxCodeInZatca { get; set; }
}