// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20107ChartOfAccount
{
    public string AccountId { get; set; }

    public string AccountHead { get; set; }

    public string AccountGroupId { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }

    public bool IsRestrictedEntry { get; set; }

    public string ReferenceNo { get; set; }

    public decimal? OpeningBalance { get; set; }

    public string OpeningBalanceDrCr { get; set; }

    public string BankAccountNo { get; set; }

    public string BankIban { get; set; }

    public string BankName { get; set; }

    public string BankBranch { get; set; }

    public string BankSwiftCode { get; set; }

    public string BankAccountName { get; set; }

    public string BillingName { get; set; }

    public string BillingAddress { get; set; }

    public string BillingContactPerson { get; set; }

    public string BillingPhoneNo { get; set; }

    public string BillingFaxNo { get; set; }

    public string BillingContactPersonTitle { get; set; }

    public string BillingBankAccount { get; set; }

    public string LedgerRemarks { get; set; }

    public string AccountHeadArabic { get; set; }

    public string AccountGroupAr { get; set; }

    public string MasterGroupAr { get; set; }

    public decimal? MasterOrderNo { get; set; }

    public string MasterGroupCategory { get; set; }

    public decimal? ChartOfAccountsOrder { get; set; }

    public decimal? AccountGroupOrderNo { get; set; }

    public string MasterGroupCategoryAr { get; set; }

    public string VoucherAbbr { get; set; }

    public bool? IsMaintainBillByBill { get; set; }

    public string RecordCreatedBy { get; set; }

    public DateTime? RecordCreatedOn { get; set; }

    public string RecordModifiedBy { get; set; }

    public DateTime? RecordModifiedOn { get; set; }

    public short? NoOfDaysCreditPeriod { get; set; }

    public string AccountsContactName { get; set; }

    public string AccountsContactMobile { get; set; }

    public string AccountsContactTitle { get; set; }

    public bool? IsEmployeeAllocated { get; set; }

    public string ClientVatno { get; set; }

    public string SupplierName { get; set; }

    public string SupplierNameAr { get; set; }

    public string SupplierAddress { get; set; }

    public string SupplierAddressAr { get; set; }

    public string SupplierVatno { get; set; }

    public string ClientVendorNo { get; set; }

    public bool? IsPropertyAllocated { get; set; }

    public string AccountSubGroup { get; set; }

    public string ClientGroupVatnumber { get; set; }

    public string ClientOtherId { get; set; }

    public string ClientOtherIdtype { get; set; }

    public string ClientAddressStreet { get; set; }

    public string ClientAddressStreetAr { get; set; }

    public string ClientAdditionalStreet { get; set; }

    public string ClientAdditionalStreetAr { get; set; }

    public string ClientBuildingNumber { get; set; }

    public string ClientAdditionalNumber { get; set; }

    public string ClientCity { get; set; }

    public string ClientCityAr { get; set; }

    public string ClientPostalCode { get; set; }

    public string ClientProvince { get; set; }

    public string ClientProvinceAr { get; set; }

    public string ClientNeighborhood { get; set; }

    public string ClientNeighborhoodAr { get; set; }

    public string ClientCountryCode { get; set; }

    public string SupplierGroupVatnumber { get; set; }

    public string SupplierOtherIdtype { get; set; }

    public string SupplierOtherId { get; set; }

    public string SupplierAddressStreet { get; set; }

    public string SupplierAddressStreetAr { get; set; }

    public string SupplierAdditionalStreet { get; set; }

    public string SupplierAdditionalStreetAr { get; set; }

    public string SupplierBuildingNumber { get; set; }

    public string SupplierAdditionalNumber { get; set; }

    public string SupplierCity { get; set; }

    public string SupplierCityAr { get; set; }

    public string SupplierPostalCode { get; set; }

    public string SupplierProvince { get; set; }

    public string SupplierProvinceAr { get; set; }

    public string SupplierNeighborhood { get; set; }

    public string SupplierNeighborhoodAr { get; set; }

    public string SupplierCountryCode { get; set; }

    public bool? IsLedgerObselete { get; set; }

    public int? MasterGroupRefNo { get; set; }

    public string MainGroup { get; set; }
}