// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry210011invoiceProfitSummary
{
    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public byte? UnitCode { get; set; }

    public string UnitType { get; set; }

    public decimal? SellingLineQty { get; set; }

    public decimal? SellingRate { get; set; }

    public decimal? SellingLineAmountAfterDiscount { get; set; }

    public byte? UnitCodeOfConversion { get; set; }

    public decimal? SellingPricePerUnit { get; set; }

    public decimal? PurchaseCostPrice { get; set; }

    public decimal TotalSellingPrice { get; set; }

    public decimal TotalPurchaseCostPrice { get; set; }

    public decimal? ProfitOnSale { get; set; }
}