// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201MainVoucherEntry
{
    public long VoucherEntryNo { get; set; }

    public string VoucherNo { get; set; }

    public string AccountHead { get; set; }

    public string AccountHeadName { get; set; }

    public decimal? VoucherAmount { get; set; }

    public string DrCr { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string EntryNarration { get; set; }

    public decimal? DrAmount { get; set; }

    public decimal? CrAmount { get; set; }

    public decimal? VoucherAmountFormatted { get; set; }

    public string SysRemarks { get; set; }

    public DateTime? BankClearedOn { get; set; }
}