// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201618vatinvoiceChildTotalForPropertyCost
{
    public string InvoiceNo { get; set; }

    public decimal? TotalCalcLineAmount { get; set; }

    public string PropertyNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string AddedBy { get; set; }

    public DateTime? InvoiceEffectiveDate { get; set; }

    public string RevenueAccount { get; set; }
}