// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20120ExpenseClaimPropertyCostEntry
{
    public long VoucherEntryNo { get; set; }

    public string ExpenseClaimRefNo { get; set; }

    public string PropertyCostAllocFromClaim { get; set; }

    public string DrCr { get; set; }

    public decimal? VoucherAmount { get; set; }

    public DateTime VoucherDate { get; set; }

    public string EntryNarration { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string VoucherNo { get; set; }
}