// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201999vatpurchseReturnsToCombine
{
    public string Vatgroup { get; set; }

    public string DocumentNo { get; set; }

    public DateTime? DocumentDate { get; set; }

    public int DssRevenue { get; set; }

    public int DzrRevenue { get; set; }

    public int DexRevenue { get; set; }

    public int GccRevenue { get; set; }

    public int ExpRevenue { get; set; }

    public int DssSalesTax { get; set; }

    public decimal? DssPurchases { get; set; }

    public decimal? DzrPurchases { get; set; }

    public decimal? DexPurchases { get; set; }

    public decimal? IpcPurchases { get; set; }

    public decimal? RcmPurchases { get; set; }

    public decimal? DssPurTax { get; set; }

    public decimal? IpcPurTax { get; set; }

    public decimal? RcmPurTax { get; set; }

    public int DssCreditNote { get; set; }

    public int DzrCreditNote { get; set; }

    public int DexCreditNote { get; set; }

    public int GccCreditNote { get; set; }

    public int ExpCreditNote { get; set; }

    public int DssTaxCreditNote { get; set; }

    public int DssDebitNote { get; set; }

    public int DzrDebitNote { get; set; }

    public int DexDebitNote { get; set; }

    public int IpcDebitNote { get; set; }

    public int RcmDebitNote { get; set; }

    public int DssDebitTax { get; set; }

    public int IpcDebitTax { get; set; }

    public int RcmDebitTax { get; set; }

    public int Dss15Revenue { get; set; }

    public int Dss15SalesTax { get; set; }

    public int Dss15CreditNote { get; set; }

    public int DssTax15CreditNote { get; set; }

    public decimal? DssPurchases15Perc { get; set; }

    public decimal? IpcPurchases15Perc { get; set; }

    public decimal? RcmPurchases15Perc { get; set; }

    public decimal? DssPurTax15Perc { get; set; }

    public decimal? IpcPurTax15Perc { get; set; }

    public decimal? RcmPurTax15Perc { get; set; }

    public int Dss15perDebitNote { get; set; }

    public int Ipc15perDebitNote { get; set; }

    public int Rcm15perDebitNote { get; set; }

    public int Dss15perDebitTax { get; set; }

    public int Ipc15perDebitTax { get; set; }

    public int Rcm15perDebitTax { get; set; }

    public int Dss10Revenue { get; set; }

    public int Dss10SalesTax { get; set; }

    public int Dss10CreditNote { get; set; }

    public int DssTax10CreditNote { get; set; }

    public decimal? DssPurchases10Perc { get; set; }

    public decimal? IpcPurchases10Perc { get; set; }

    public decimal? RcmPurchases10Perc { get; set; }

    public decimal? DssPurTax10Perc { get; set; }

    public decimal? IpcPurTax10Perc { get; set; }

    public decimal? RcmPurTax10Perc { get; set; }

    public int Dss10perDebitNote { get; set; }

    public int Ipc10perDebitNote { get; set; }

    public int Rcm10perDebitNote { get; set; }

    public int Dss10perDebitTax { get; set; }

    public int Ipc10perDebitTax { get; set; }

    public int Rcm10perDebitTax { get; set; }
}