// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201124propertyAllocationWoPropertyNo
{
    public long? VoucherEntryNo { get; set; }

    public string PropertyNo { get; set; }

    public decimal? UnAllocatedAmount { get; set; }
}