// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry210002itemsUnitsConversion
{
    public string Gscode { get; set; }

    public byte? UnitCodeOfConversion { get; set; }

    public decimal? UnitConverted { get; set; }
}