// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201732vatonVoucherPostedToCheck
{
    public string VoucherRefNo { get; set; }

    public decimal? TaxAmountInVoucher { get; set; }

    public DateTime VoucherDate { get; set; }

    public string AccountHead { get; set; }
}