// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201643prepaidInvoicesToDisplay002
{
    public string PrepaidInvoiceNo { get; set; }

    public DateTime? PrepaidInvoiceDateWtTime { get; set; }

    public string ClientCode { get; set; }

    public string InvoiceStatus { get; set; }

    public int? InvoiceTypeCode { get; set; }

    public string SubmittedInvoiceUuid { get; set; }

    public string CurrencyMasterCode { get; set; }

    public decimal? ExchangeRate { get; set; }

    public string TaxCodeInZatca { get; set; }

    public decimal? TaxRateIn100 { get; set; }

    public decimal? TotalExclusiveAmountInvCurr { get; set; }

    public decimal? TaxAmountByTaxRateInvCurr { get; set; }

    public decimal? TotalInclusiveAmountInCurr { get; set; }
}