// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201622invoiceCostPostingExtractOfInvoiceInDetail
{
    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string ClientName { get; set; }

    public string BillingName { get; set; }

    public string ItemCode { get; set; }

    public string Gsdescrpition { get; set; }

    public string UoM { get; set; }

    public decimal? QuantityInvoiced { get; set; }

    public decimal? UnitsToBill { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public decimal? UnitRate { get; set; }

    public decimal? AmountBeforeDiscount { get; set; }

    public decimal? Discount { get; set; }

    public decimal? AmountAfterDiscount { get; set; }

    public decimal? VatAmount { get; set; }

    public decimal? Total { get; set; }

    public DateTime? InvoiceEffectiveDate { get; set; }

    public DateTime? InvoiceDeliveryDate { get; set; }

    public string QuotationNo { get; set; }

    public string DeliveryNoteNos { get; set; }

    public string ReferenceNo { get; set; }

    public string SosreferenceNo { get; set; }

    public string Pono { get; set; }

    public DateTime? Podate { get; set; }

    public byte? SalesPerson { get; set; }

    public string RemarksInEn { get; set; }

    public string RemarksInAr { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedBy { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public string BillingAddress { get; set; }

    public string BillingNameAr { get; set; }

    public string BillingAddressAr { get; set; }

    public string VatregistrationNo { get; set; }

    public string CompanyBranch { get; set; }

    public string Crno { get; set; }

    public string CostAllocationMasterGroup { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocationUnit { get; set; }

    public string SalesPersonName { get; set; }

    public string AccountId { get; set; }

    public string VatregistrationNoAr { get; set; }

    public string InvoicePeriod { get; set; }

    public string ClientCode { get; set; }

    public string CashOrClientGroupId { get; set; }

    public string CashOrClientGroupName { get; set; }

    public string ClientNameInCash { get; set; }

    public string ClientVatinCash { get; set; }

    public string ClientNameInCashAr { get; set; }

    public string ClientNameOrCashClient { get; set; }

    public string ClientVatorCashClientVat { get; set; }

    public string ClientNameArOrCashClientAr { get; set; }

    public string RevenueLedgerNo { get; set; }

    public string RevenueLedgerName { get; set; }

    public string StockGroupName { get; set; }

    public string ClientCodeFromInventory { get; set; }

    public string ItemPartNo { get; set; }

    public string ItemBrand { get; set; }

    public string ItemMake { get; set; }

    public string StockClassification { get; set; }

    public decimal? TotalDeliveredQty { get; set; }

    public decimal? CostPriceTotal { get; set; }

    public string InvoiceStatus { get; set; }

    public decimal? PerItemCost { get; set; }

    public decimal? LineItemsCost { get; set; }

    public string DetailedDescription { get; set; }

    public string BuyerVatnumber { get; set; }

    public string BuyerOtherId { get; set; }

    public string BuyerCity { get; set; }

    public string BuyerCountryCode { get; set; }

    public string BuyerNeighborhood { get; set; }

    public string BuyerProvince { get; set; }

    public string BuyerPostalCode { get; set; }

    public string BuyerBuildingNumber { get; set; }

    public string BuyerAdditionalNumber { get; set; }

    public string BuyerAddressStreet { get; set; }

    public string BuyerGroupVatnumber { get; set; }

    public string BuyerName { get; set; }

    public decimal? IssuedInvoiceCostPrice { get; set; }

    public byte? UnitRateMethod { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string BatchNo { get; set; }

    public decimal? LineOrderNo { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public string CostAllocationUnitId { get; set; }

    public bool? IsCogsPosted { get; set; }

    public string IsCogsPostedBy { get; set; }

    public DateTime? IsCogsPostedOn { get; set; }

    public decimal? CurrentQtyOnPosting { get; set; }

    public int? InvoiceChildSlNo { get; set; }

    public bool IsServicesGroup { get; set; }
}