// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry20146IncomeStatementWithCostCenter
{
    public string AccountHead { get; set; }

    public string AccountHeadName { get; set; }

    public string AccountGroup { get; set; }

    public string MasterGroup { get; set; }

    public decimal? VoucherTotal { get; set; }

    public DateTime VoucherDate { get; set; }

    public string VoucherNo { get; set; }

    public long? VoucherEntryNo { get; set; }

    public string CostAllocationUnit { get; set; }

    public string CostAllocationGroup { get; set; }

    public string CostAllocationMasterGroup { get; set; }
}