// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201205depreciationMasterView
{
    public string DepreciationDocNo { get; set; }

    public DateTime? DeprStartDate { get; set; }

    public DateTime? DeprEndDate { get; set; }

    public string DeprRemarks { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsPosted { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedOn { get; set; }

    public decimal? AssetOpeningBalance { get; set; }

    public decimal? AssetTotalDebitTrans { get; set; }

    public decimal? AssetTotalCreditTrans { get; set; }

    public decimal? AssetClosingBalance { get; set; }

    public decimal? TotalDepreciationAmount { get; set; }

    public decimal? AccumulatedOpeningBalance { get; set; }

    public decimal? AccumulatedTotalBalance { get; set; }

    public decimal? TotalBookValue { get; set; }

    public int? NoOfAssets { get; set; }

    public string JournalVoucherNo { get; set; }
}