// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry201724vatpurchaseGoodsInTransitLedger
{
    public string AccountId { get; set; }

    public string AccountHead { get; set; }

    public string AccountHeadArabic { get; set; }

    public string AccountGroup { get; set; }

    public string AccountGroupId { get; set; }

    public string MasterGroupId { get; set; }

    public string MasterGroup { get; set; }

    public bool? IsGoodsInTransit { get; set; }
}