// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry202114costAllocationTotalByJournalChildNo
{
    public long JournalChildNo { get; set; }

    public decimal? TotalCostAllocated { get; set; }
}