// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry30105ClientStatusLatest2
{
    public long ClientStatusNo { get; set; }

    public string ClientCode { get; set; }

    public DateTime? StatusDate { get; set; }

    public string ReportedBy { get; set; }

    public DateTime? ReportedOn { get; set; }

    public string StatusRemarks { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public DateTime? FollowupOn { get; set; }

    public string Status { get; set; }
}