// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry40123PropertyListMobilized
{
    public string PropertyNo { get; set; }

    public DateTime? LastIssuedDate { get; set; }
}