// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry40707propertyRevenueCostSheetCombined
{
    public string PropertyNo { get; set; }

    public DateTime? TimeSheetDate { get; set; }

    public decimal? ClientRegHoursPerDay { get; set; }

    public decimal? ClientRegAmountPerDay { get; set; }

    public decimal? ClientOthoursPerDay { get; set; }

    public decimal? ClientOtamountPerDay { get; set; }

    public decimal? ClientAmountPerDay { get; set; }

    public decimal? SuppRegHoursPerDay { get; set; }

    public decimal? SuppRegAmountPerDay { get; set; }

    public decimal? SuppOthoursPerDay { get; set; }

    public decimal? SuppOtamountPerDay { get; set; }

    public decimal? SuppTotalPerDay { get; set; }

    public decimal? InvoicedAmount { get; set; }

    public decimal? RevenueAllocated { get; set; }

    public decimal? ExpensesAllocated { get; set; }
}