// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry40905suppSumInvoiceOtlineSeparated
{
    public string SuppTimesheetSummaryNo { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string PropertyNo { get; set; }

    public string PropertyDescription { get; set; }

    public decimal? UnitToBill { get; set; }

    public int? UnitRateMethod { get; set; }

    public decimal? UnitRate { get; set; }

    public string UoM { get; set; }

    public decimal LineDeductions { get; set; }
}