// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry40318propertyTsdayshiftOprtCombined
{
    public int? TimeSheetMasterId { get; set; }

    public string EmployeeName { get; set; }
}