// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry40401salesOrderListForDeliveryNote
{
    public string SalesOrderNo { get; set; }

    public string ClientPono { get; set; }

    public DateTime? ClientPodate { get; set; }

    public string QuoteNo { get; set; }

    public DateTime? QuoteDate { get; set; }

    public string ClientRefNo { get; set; }

    public string ClientCode { get; set; }

    public string Attention { get; set; }

    public string ClientContactNo { get; set; }

    public string ClientContactEmail { get; set; }
}