// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry65112deliveryNoteItemsWithPrice2
{
    public string DeliveryNoteNo { get; set; }

    public string SalesOrderNo { get; set; }

    public string Gscode { get; set; }

    public decimal? IssuedQty { get; set; }

    public string IssuedUom { get; set; }

    public byte? UnitRateMethod { get; set; }

    public string DeliveryRemarks { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string AddlDescription { get; set; }

    public DateTime DeliveryDate { get; set; }

    public decimal? IssuedUnitPrice { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string BatchNo { get; set; }

    public decimal? IssuedQuoteUnitPrice { get; set; }
}