// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry65203expDtStockReceiptsMaster
{
    public string ReceiptNo { get; set; }

    public long ReceiptChildSlNo { get; set; }

    public string Gscode { get; set; }

    public decimal? QtyReceived { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? UnitPrice { get; set; }

    public byte? UnitCodeOfConversion { get; set; }

    public decimal UnitsConverted { get; set; }

    public decimal? StockReceivedQty { get; set; }

    public decimal? StockReceivedUnitPrice { get; set; }

    public DateTime? ReceiptDate { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string BatchNo { get; set; }
}