// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry65112salesOrdersWtPriceForDnitem
{
    public string SalesOrderNo { get; set; }

    public string Gscode { get; set; }

    public decimal? QuotedUnitPrice { get; set; }

    public byte? QuotedTaxSlab { get; set; }

    public decimal? QuotedDiscount { get; set; }

    public decimal? LineOrderNo { get; set; }
}