// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry671001stockPurchaseGoodsInTransitMaster
{
    public string GoodsInTransitPurchaseVoucherNo { get; set; }

    public bool IsGoodsInTransitAccount { get; set; }

    public string GoodsInTransitAccountNo { get; set; }

    public decimal QuantityInvoiced { get; set; }

    public decimal UnitRate { get; set; }

    public string ItemCode { get; set; }

    public decimal Discount { get; set; }

    public decimal? LineTotalAfterDiscount { get; set; }
}