// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60410purchaseItemDetail
{
    public string Pono { get; set; }

    public DateTime? Podate { get; set; }

    public string SupplierCode { get; set; }

    public string SupplierQuoteNo { get; set; }

    public DateTime? SupplierQuoteDate { get; set; }

    public string SupplierRefNo { get; set; }

    public string Attention { get; set; }

    public string SupplierContactNo { get; set; }

    public string SupplierContactEmail { get; set; }

    public string SubjectTitle { get; set; }

    public string PreparedBy { get; set; }

    public DateTime? PreparedOn { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string Pointroduction { get; set; }

    public string Posummary { get; set; }

    public byte? RevisionNo { get; set; }

    public byte? CompanyBranch { get; set; }

    public string AdditionsText { get; set; }

    public string DiscountsText { get; set; }

    public DateTime? PodueDate { get; set; }

    public byte? Posignatory { get; set; }

    public decimal? AdditionsAmount { get; set; }

    public decimal? DeductionsAmount { get; set; }

    public decimal? TotalBeforeTax { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalAfterDiscount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalWithTax { get; set; }

    public decimal? GrandTotal { get; set; }

    public string CompanyName { get; set; }

    public string Gscode { get; set; }

    public string Gsdescrpition { get; set; }

    public string GsdescriptionAr { get; set; }

    public string AddlDescription { get; set; }

    public decimal? QuotedQuantity { get; set; }

    public byte? UnitRateMethod { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? ItemDiscount { get; set; }

    public byte? PotaxSlab { get; set; }

    public string PoitemRemarks { get; set; }

    public int? LineOrderNo { get; set; }

    public string PurchaseTaxSlab { get; set; }

    public decimal? PurchaseTaxRate { get; set; }

    public decimal? LineTotalBeforeTax { get; set; }

    public decimal? LineTotalAfterDisc { get; set; }

    public decimal? LineTaxAmount { get; set; }

    public decimal? LineTotalWithTax { get; set; }

    public string SupplierName { get; set; }

    public string SupplierNameAr { get; set; }

    public string SupplierAddress { get; set; }

    public string Mprno { get; set; }

    public string PothanksNote { get; set; }

    public string Hscode { get; set; }

    public string VerifiedName { get; set; }

    public string VerifiedPosition { get; set; }

    public string VerifiedContactNo { get; set; }

    public string VerifiedEmail { get; set; }

    public string ApprovedName { get; set; }

    public string ApprovedPosition { get; set; }

    public string ApprovedContact { get; set; }

    public string ApprovedEmail { get; set; }

    public decimal? OrderedQty { get; set; }

    public decimal? ReceivedQty { get; set; }

    public decimal? BalanceToReceive { get; set; }

    public byte? InventoryMasterGroupId { get; set; }

    public string InventoryMasterGroup { get; set; }

    public string SalesPersonCode { get; set; }

    public string SalesPersonName { get; set; }

    public byte? SalesPersonUserId { get; set; }

    public string DeliveryPeriod { get; set; }

    public string ProjectMasterCode { get; set; }

    public string ProjectDescription { get; set; }

    public string ProjectLocation { get; set; }

    public bool IsObseleteVersion { get; set; }
}