// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60004inventoryUploadsUom
{
    public byte? UnitCode { get; set; }

    public string UnitType { get; set; }

    public string GsuomDesc { get; set; }
}