// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry671003stockPurchaseEntriesWtGitcost03ByQty
{
    public string PurchaseVoucherNo { get; set; }

    public string Gscode { get; set; }

    public decimal? LineTotalAfterDiscount { get; set; }

    public decimal TotalAfterDiscount { get; set; }

    public decimal TotalGitcost { get; set; }

    public decimal? AvgLineCost { get; set; }

    public decimal? GticostPerLine { get; set; }

    public decimal? GitcostByQty { get; set; }

    public int PurchaseChildSlNo { get; set; }

    public decimal? UnitPriceAfterDiscount { get; set; }
}