// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry65316getInventoryIssuePriceUsingAvgCost
{
    public string Gscode { get; set; }

    public decimal? TotalQty { get; set; }

    public decimal? TotalAmount { get; set; }

    public decimal? AvgCostUnitRate { get; set; }
}