// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60123quoteDistributionOfProfitMargin
{
    public long QuoteChildId { get; set; }

    public string QuotationNo { get; set; }

    public decimal? QuotedQuantity { get; set; }

    public decimal? QuotedCostPrice { get; set; }

    public decimal? PostingAmount { get; set; }

    public decimal? PostingPercentage { get; set; }

    public string Gscode { get; set; }

    public decimal? QuotedLineAmount { get; set; }

    public string PostingCostItemCode { get; set; }

    public decimal? QuotedTotalCostAmount { get; set; }

    public int? QuotedLineItems { get; set; }

    public decimal? EquallyDistributed { get; set; }

    public decimal? PorpoDistPercentage { get; set; }

    public decimal? PropoDistributed { get; set; }

    public int? EqualPercentage { get; set; }

    public decimal? DistributedByPercentage { get; set; }

    public decimal? TotalCostOfItemInclAll { get; set; }

    public decimal? ProfitMarginByPercentage { get; set; }

    public decimal? ProfitMarginByProportion { get; set; }

    public decimal? ProfitMarginByEqual { get; set; }

    public decimal? ProfitMarginPerItemByPercentage { get; set; }

    public decimal? ProfitMarginPerItemByProportion { get; set; }

    public decimal? ProfitMarginPerItemByEqual { get; set; }
}