// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60311deliveryNotesWithDetail
{
    public string DeliveryNoteNo { get; set; }

    public DateTime DeliveryDate { get; set; }

    public byte? DeliveryType { get; set; }

    public string DeliveredTo { get; set; }

    public string ClientName { get; set; }

    public string ClientCode { get; set; }

    public string ClientPono { get; set; }

    public string SalesOrderNo { get; set; }

    public string InvoiceNo { get; set; }

    public string ClientAccountLedgerNo { get; set; }

    public string OrderStatus { get; set; }

    public string InvoiceStatus { get; set; }
}