// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60703rfqwithTotal
{
    public string Rfqno { get; set; }

    public int? NoOfItems { get; set; }

    public decimal? TotalBeforeTax { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalAfterDiscount { get; set; }
}