// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60111quotationItemCost
{
    public long? QuoteChildId { get; set; }

    public string QuoteNo { get; set; }

    public string Gscode { get; set; }

    public string CostItemCode { get; set; }

    public decimal? CostPercentage { get; set; }

    public decimal? CostItemPrice { get; set; }

    public decimal? CostItemQty { get; set; }

    public decimal? CostItemSubTotal { get; set; }

    public long QuoteCostSlNo { get; set; }
}