// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60507totalReceivedQtyByPurchaseOrder
{
    public string OurPurchaseOrderNo { get; set; }

    public string Gscode { get; set; }

    public decimal? ReceivedQty { get; set; }
}