// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry60503materialReceiptWithTotal
{
    public string ReceiptNo { get; set; }

    public int? NoOfItems { get; set; }

    public decimal? TotalBeforeTax { get; set; }

    public decimal? TotalDiscount { get; set; }

    public decimal? TotalAfterDiscount { get; set; }

    public decimal? TotalTaxAmount { get; set; }

    public decimal? TotalWithTax { get; set; }
}