// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry70006projectMaterialDelivery
{
    public string ProjectMasterCode { get; set; }

    public string DeliveryNoteNo { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string DeliveryTypeName { get; set; }

    public string Gscode { get; set; }

    public decimal? IssuedQty { get; set; }

    public string UnitType { get; set; }

    public string UnitDesc { get; set; }

    public string TransportedBy { get; set; }

    public string SalesOrderNo { get; set; }

    public string ClientPono { get; set; }

    public string Gsdescrpition { get; set; }
}