// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry80306mnpayrollLineItemsToSummInvoice
{
    public string ManpowerPayrollNo { get; set; }

    public string PositionTitle { get; set; }

    public string ProjectName { get; set; }

    public DateTime? PayrollEffectiveDate { get; set; }

    public string EmpId { get; set; }

    public string EmployeeName { get; set; }

    public decimal? LineNetAmount { get; set; }

    public decimal? LineHoursWorked { get; set; }

    public decimal? LineRatePerHour { get; set; }

    public string WorkingHours { get; set; }

    public DateTime? PayrollStartDate { get; set; }

    public DateTime? PayrollEndDate { get; set; }

    public string DetailedDescription { get; set; }
}