// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry80203manpowerPoitemsWithTotal
{
    public string ManpowerPono { get; set; }

    public int? NoOfItems { get; set; }

    public decimal? TotalAmount { get; set; }
}