// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry90137eInvoiceCombinedLogMasterView
{
    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public string InvoiceStatus { get; set; }

    public DateTime? InvoiceDateWtTime { get; set; }

    public string AccountHead { get; set; }

    public string InvoiceZatcaStatus { get; set; }

    public string EInvoiceSubmittedToZatcaBy { get; set; }

    public DateTime? EInvoiceSubmittedToZatcaOn { get; set; }

    public bool? IsVerified { get; set; }

    public string VerifiedBy { get; set; }

    public string VerifiedByAr { get; set; }

    public DateTime? VerifiedOn { get; set; }

    public bool? IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public string ApprovedByAr { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public string AddedBy { get; set; }

    public string AddedByAr { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public string ModifiedByAr { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public bool? IsPosted { get; set; }

    public string PostedBy { get; set; }

    public DateTime? PostedOn { get; set; }

    public decimal? CalcLineAmount { get; set; }

    public decimal? CalcTaxAmount { get; set; }

    public string InvoiceTypeCodeSubType { get; set; }

    public decimal? TotalInvoiceAmount { get; set; }
}