// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qry90122EquipmentDocNotifyToInsertAlertMaster
{
    public string AlertNo { get; set; }

    public string AlertMessage { get; set; }

    public DateTime? DocumentNotificationTime { get; set; }

    public string AlertDocumentType { get; set; }

    public string AlertDocumentRefNo { get; set; }
}