// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Qy10151PayrollPostingTotal
{
    public int PayrollMasterId { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string EmpId { get; set; }

    public decimal? AmountFormatted { get; set; }
}