// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Shared.DAL.Entities
{
    public partial class sp20155CashFlowMaster01Result
    {
        public string AccountHead { get; set; }
        public string AccountHeadName { get; set; }
        public decimal? VoucherAmountFormatted { get; set; }
        public string AccountGroup { get; set; }
        public string MasterGroup { get; set; }
        public string TransactionsFull { get; set; }
        public string VoucherNo { get; set; }
    }
}
