// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Shared.DAL.Entities
{
    public partial class stPro50102MandaysReportResult
    {
        public long CheckInID { get; set; }
        public string NationalityCategory { get; set; }
        public string RoomCategory { get; set; }
        public string ClientName { get; set; }
        public int? NoOfDays { get; set; }
        public decimal? TotalRent { get; set; }
    }
}
