// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QD.ERP.Shared.DAL.Entities
{
    public partial class stpro401_24GetEquipDailyTotalResult
    {
        [Column("PreviousBalance", TypeName = "decimal(38,7)")]
        public decimal? PreviousBalance { get; set; }
        public string BalanceText { get; set; }
    }
}
