// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl101ContractStatus
{
    public byte ContractStatusId { get; set; }

    public string ContractStatus { get; set; }
}