// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl101PayrollMasterAddition
{
    public int PayrollAdditionsId { get; set; }

    public int? PayrollMasterId { get; set; }

    public byte? PayrollAdditions { get; set; }

    public decimal? AdditionAmount { get; set; }

    public string AdditionRemarks { get; set; }
}