// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl10106PayrollInvoice
{
    public long SlNo { get; set; }

    public int? PayrollMasterId { get; set; }

    public string JobTitle { get; set; }

    public string CostCentreTitle { get; set; }

    public DateTime? PayrollMonth { get; set; }

    public string EmployeeNo { get; set; }

    public string EmployeeName { get; set; }

    public decimal? FullTotal { get; set; }

    public decimal? TotalPayableHours { get; set; }

    public decimal? TotalRegHours { get; set; }

    public decimal? TotalOvertimeHours { get; set; }

    public decimal? SplOvertimeHours { get; set; }

    public decimal? HourlyRate { get; set; }

    public decimal? OvertimeRate { get; set; }

    public decimal? SplOvertimeRate { get; set; }

    public decimal? PayableAmount { get; set; }

    public decimal? BillingRate { get; set; }

    public decimal? BillingOtrate { get; set; }

    public decimal? BillingSplOtrate { get; set; }

    public decimal? BillingAmount { get; set; }

    public string InvoiceNo { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string DetailedJobDescription { get; set; }
}