// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl101SalaryAddition
{
    public byte SalaryAdditionsId { get; set; }

    public string SalaryAddition { get; set; }

    public bool? IsDefault { get; set; }

    public string AdditionShortName { get; set; }

    public string AdditionAbbr { get; set; }

    public string EmployeeAdditionsCode { get; set; }
}