// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl102002manpowerPayrollTimesheet
{
    public long ManpowerPayrollChildSlNo { get; set; }

    public string ManpowerPayrollNo { get; set; }

    public DateTime? ManpowerPayrollDate { get; set; }

    public short? ClientRegHoursWorked { get; set; }

    public short? ClientOthoursWorked { get; set; }

    public decimal? ClientRegRatePerHour { get; set; }

    public decimal? ClientOtratePerHour { get; set; }

    public decimal? ClientRegRatePerDay { get; set; }

    public short? SupplierRegHoursWorked { get; set; }

    public short? SupplierOthoursWorked { get; set; }

    public decimal? SupplierRegRatePerHour { get; set; }

    public decimal? SupplierOtratePerHour { get; set; }

    public decimal? SupplierRegRatePerDay { get; set; }

    public byte? WorkStatus { get; set; }

    public string TimesheetDayRemarks { get; set; }
}