// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl101SalaryDeduction
{
    public byte SalaryDeductionsId { get; set; }

    public string SalaryDeductions { get; set; }

    public bool? IsDefault { get; set; }

    public string DeductionShortName { get; set; }

    public string DeductionAbbr { get; set; }

    public string EmployeeDeductionsCode { get; set; }
}