// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl101Department
{
    public short DepartmentCode { get; set; }

    public string Department { get; set; }

    public string DepartmentHead { get; set; }

    public string DepartmentHeadTitle { get; set; }

    public string DepartmentArabic { get; set; }
}