// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl101EmployeeLeaveDate
{
    public int LeaveDatesSlNo { get; set; }

    public int? LeaveApplicationId { get; set; }

    public string EmpId { get; set; }

    public DateTime? LeaveDate { get; set; }

    public bool? IsApproved { get; set; }

    public bool? IsPaid { get; set; }
}