// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl201VoucherEntryTemp
{
    public int VoucherEntryNo { get; set; }

    public string VoucherNo { get; set; }

    public string AccountHead { get; set; }

    public decimal? VoucherAmount { get; set; }

    public string DrCr { get; set; }

    public string AddedBy { get; set; }

    public DateTime? AddedOn { get; set; }

    public string EntryNarration { get; set; }

    public string SysRemarks { get; set; }
}