// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl20168VatpurchaseTaxSlab
{
    public byte PurchaseTaxSlabCode { get; set; }

    public string PurchaseTaxSlab { get; set; }

    public string PurchaseTaxSlabAr { get; set; }

    public decimal? PurchaseTaxRate { get; set; }

    public byte? PurchaseTaxCategoryId { get; set; }

    public string PurchaseTaxCategory { get; set; }

    public string PurchaseTaxCategoryAr { get; set; }

    public string PurchaseTaxInWords { get; set; }
}