// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl20199AddressDetailsToUpload
{
    public int SlNo { get; set; }

    public string LedgerNo { get; set; }

    public string LedgerName { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public string Website { get; set; }

    public string CountryName { get; set; }

    public string BankName { get; set; }

    public string Iban { get; set; }

    public string Vatnumber { get; set; }

    public string PhoneNo { get; set; }

    public string FaxNo { get; set; }

    public string ContactNo { get; set; }

    public string MobileNo { get; set; }
}