// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl20164GoodsAndServicesMaster
{
    public string Gscode { get; set; }

    public string Gsdescrpition { get; set; }

    public string GsdescriptionAr { get; set; }

    public string GsdetailedDesc { get; set; }

    public string GsdetailedDescAr { get; set; }

    public byte? GsgroupId { get; set; }

    public byte? GsuoM { get; set; }

    public int? GspackingUnit { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public decimal? GssellingRate { get; set; }

    public decimal? CostPrice { get; set; }

    public string StoreId { get; set; }

    public string Remarks { get; set; }

    public string ItemSize { get; set; }

    public string ItemColor { get; set; }

    public string ItemDimension { get; set; }

    public string ItemPartNo { get; set; }

    public string ItemThickness { get; set; }

    public string ItemBrand { get; set; }

    public string ItemMake { get; set; }

    public decimal? OpeningBalance { get; set; }

    public byte[] ItemImage { get; set; }

    public bool? IsDiscontinued { get; set; }

    public byte? ItemClassificationId { get; set; }

    public bool? IsExpiringItem { get; set; }

    public decimal? MinQty { get; set; }

    public decimal? MaxQty { get; set; }

    public decimal? ReorderLevel { get; set; }

    public decimal? ReorderQty { get; set; }

    public decimal? ReorderLeadTime { get; set; }

    public string StoreCode { get; set; }

    public DateTime? ExpiryDate { get; set; }

    public string BatchNo { get; set; }

    public string Hscode { get; set; }

    public string ActualSize { get; set; }

    public string Identification { get; set; }

    public decimal? ExFactoryCostPrice { get; set; }

    public string CountryOfOrigin { get; set; }

    public decimal? MinSellingPrice { get; set; }

    public decimal? MaxSellingPrice { get; set; }
}