// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl30110StockGroupMaster
{
    public int StockGroupId { get; set; }

    public string StockGroupName { get; set; }
}