// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl40130PropertySalesOrderChild
{
    public long SalesOrderChildId { get; set; }

    public string SalesOrderNo { get; set; }

    public string PropertyNo { get; set; }

    public string PropertyAddlDescription { get; set; }

    public decimal? QuotedQuantity { get; set; }

    public string QuotedUom { get; set; }

    public byte? UnitRateMethod { get; set; }

    public decimal? LineOrderNo { get; set; }

    public decimal? UnitRate { get; set; }

    public string DeliveryTerms { get; set; }

    public string QuoteRemarks { get; set; }

    public bool? IsWithOperator { get; set; }

    public decimal? QuotedOperatorRate { get; set; }

    public decimal? MobRate { get; set; }

    public decimal? DemobRate { get; set; }

    public int? PropertyTypeId { get; set; }

    public byte? UnitRateMethod1 { get; set; }

    public decimal? UnitRate1 { get; set; }

    public byte? UnitRateMethod2 { get; set; }

    public decimal? UnitRate2 { get; set; }

    public byte? UnitRateMethod3 { get; set; }

    public decimal? UnitRate3 { get; set; }

    public string AddlNotes { get; set; }

    public string Certification { get; set; }

    public string Capacity { get; set; }

    public string Operator { get; set; }

    public string Attachment { get; set; }

    public string Notes { get; set; }

    public string DeliveryDetails { get; set; }


    public string HasEquipmentDetails { get; set; }
    public string PropertyOrdered { get; set; }

}