// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl40131PropertyStatusBySelectedMonth
{
    public string PropertyNo { get; set; }

    public string CurrentStatus { get; set; }

    public string BillingDescription { get; set; }

    public byte? BillingDescriptionCode { get; set; }

    public string IsNeededTimesheet { get; set; }

    public string IsTimesheetAdded { get; set; }

    public long SlNo { get; set; }
}