// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl40143EquipmentDailyTslogTemporary
{
    public string PropertyNo { get; set; }

    public string ClientCode { get; set; }

    public string ClientName { get; set; }

    public string ClientSite { get; set; }

    public decimal? ClientRatePerHour { get; set; }

    public decimal? ClientOtratePerHour { get; set; }

    public short? NoOfHours { get; set; }
}