// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl60008inventoryMasterGroup
{
    public byte InventoryMasterGroupId { get; set; }

    public string InventoryMasterGroup { get; set; }

    public bool? IsEquipmentSparePart { get; set; }

    public string PonoSequenceForGroup { get; set; }
}