// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl60202salesOrderChild
{
    public long SalesOrderChildId { get; set; }

    public string SalesOrderNo { get; set; }

    public string QuoteNo { get; set; }

    public decimal? QuotedQuantity { get; set; }

    public string QuotedUom { get; set; }

    public byte? UnitRateMethod { get; set; }

    public string DeliveryTerms { get; set; }

    public string QuoteRemarks { get; set; }

    public string Gscode { get; set; }

    public decimal? QuotedUnitPrice { get; set; }

    public byte? QuotedTaxSlab { get; set; }

    public decimal? QuotedDiscount { get; set; }

    public decimal? LineOrderNo { get; set; }

    public string AddlDescription { get; set; }

    public string PlanNo { get; set; }

    public string DeliveryPeriod { get; set; }

    public decimal? CostPrice { get; set; }

    public decimal? DeliveringQuantity { get; set; }
}