// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl60107quotationChildItemGroup
{
    public long QuoteGroupItemSlNo { get; set; }

    public string QuotationNo { get; set; }

    public string GroupCode { get; set; }

    public string GroupName { get; set; }

    public string GroupRemarks { get; set; }

    public bool? IsShowLineItemsTotal { get; set; }

    public string Mprno { get; set; }
}