// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl60802jobOrderDocReportMaster
{
    public string ReportDocCode { get; set; }

    public string ReportDocText { get; set; }

    public string ReportType { get; set; }

    public bool? IsDefaultForType { get; set; }

    public string ReportDocName { get; set; }
}