// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl70006projectGroup
{
    public byte ProjectGroupId { get; set; }

    public string ProjectGroup { get; set; }

    public string ProjectGroupCode { get; set; }

    public string ProjectGroupAr { get; set; }

    public string ProjectCategory { get; set; }
}