// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl90113AlertSetting
{
    public string SystemAlertSettingCode { get; set; }

    public string SystemAlertDesc { get; set; }

    public bool? IsAlertActivated { get; set; }

    public byte? AlertIsSetForUserId { get; set; }

    public string AlertMessageToBeSet { get; set; }

    public bool? IsEmailAlertActivated { get; set; }

    public string EmailAlertSetForEmails { get; set; }

    public string EmailAlertMessage { get; set; }

    public bool? IsEmailToProjectIncharge { get; set; }

    public bool? IsEmailToProjectSubUnits { get; set; }

    public bool? IsEmailToRequester { get; set; }

    public string EmailAlertSetForEmailsCc { get; set; }
}