// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl90116UserEntryLogSheet
{
    public long UserEntryLogNo { get; set; }

    public string EntryLogFor { get; set; }

    public string EntryLogDetails { get; set; }

    public DateTime? LogCreatedOn { get; set; }

    public string LogCreatedBy { get; set; }

    public string LogDocumentNo { get; set; }
}