// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl90117VoucherDateLocking
{
    public string VoucherTypeCode { get; set; }

    public string VoucherType { get; set; }

    public string VoucherModule { get; set; }

    public DateTime? VoucherDateLocked { get; set; }
}