// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl901CompanyEmail
{
    public string CompanyEmailsCode { get; set; }

    public string CompanyEmail { get; set; }

    public string CompanyEmailPw { get; set; }

    public string Remarks { get; set; }

    public string EmailerName { get; set; }
}