// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class Tbl90103EmailAutoMailer
{
    public short EmailFormatNo { get; set; }

    public string EmailType { get; set; }

    public string EmailFrequency { get; set; }

    public string EmailAddress { get; set; }

    public string EmailHeader { get; set; }

    public string EmailAttachment { get; set; }

    public string EmailBody { get; set; }

    public string EmailFooter { get; set; }
}