// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class TblClosingBalance2011
{
    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public string StockGroup { get; set; }

    public double? ClosingBalance { get; set; }

    public double? CostPrice { get; set; }
}