// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class TblQuoteChild
{
    public int QuoteSlNo { get; set; }

    public string QuoteNo { get; set; }

    public string StockNo { get; set; }

    public int? QtyQuoted { get; set; }

    public string Unit { get; set; }

    public int? PackOf { get; set; }

    public decimal? RatePerDay { get; set; }

    public decimal? UnitPrice { get; set; }

    public decimal? ReplacementCost { get; set; }
}