// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class TblTest
{
    public string EmpNo { get; set; }

    public string EmpName { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? DateJoined { get; set; }
}