// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class View2
{
    public int ReceiveChildSlNo { get; set; }

    public string ReceiptNo { get; set; }

    public string StockNo { get; set; }

    public int? QtyReceived { get; set; }

    public string Unit { get; set; }

    public decimal? PricePerUnit { get; set; }

    public decimal? RentPerDay { get; set; }

    public string DeliveryNoteNo { get; set; }

    public int? PackOf { get; set; }
}