// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QD.ERP.Shared.DAL.Entities;

public partial class VrqryMaster
{
    public string StockNo { get; set; }

    public string StockDescription { get; set; }

    public int OpeningBalance { get; set; }

    public int Purchased { get; set; }

    public int Sold { get; set; }

    public int? OurMaterialStock { get; set; }

    public int StocksContracted { get; set; }

    public int StocksContractedReturn { get; set; }

    public int? StocksInSites { get; set; }

    public int StocksRented { get; set; }

    public int StocksRentedReturn { get; set; }

    public int? BalanceToGetBack { get; set; }

    public int StocksHired { get; set; }

    public int StocksHiredReturned { get; set; }

    public int? StocksFromOthers { get; set; }

    public int StocksDamaged { get; set; }

    public string UnitOfIssue { get; set; }

    public short? PackOfIssue { get; set; }

    public byte? StockGroupId { get; set; }
}