// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QD.ERP.Web.Models.DAL;

public partial class ERPMasterWtDataContext : DbContext
{
    public ERPMasterWtDataContext(DbContextOptions<ERPMasterWtDataContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Qry201ListOfAccount> Qry201ListOfAccounts { get; set; }

    public virtual DbSet<TblUserAccess> TblUserAccesses { get; set; }

    public virtual DbSet<TblUserMaster> TblUserMasters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Qry201ListOfAccount>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("qry201ListOfAccounts");

            entity.Property(e => e.AccountGroup)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.AccountGroupId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("AccountGroupID");
            entity.Property(e => e.AccountHead)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.AccountId)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("AccountID");
            entity.Property(e => e.Expr1)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.MasterGroup)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.MasterGroupId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("MasterGroupID");
            entity.Property(e => e.ReferenceNo)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TblUserAccess>(entity =>
        {
            entity.HasKey(e => e.SlNo);

            entity.ToTable("tblUserAccess");

            entity.HasIndex(e => e.UserId, "IX_tblUserAccess");

            entity.Property(e => e.GroupSlNo).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.ItemDescription).IsUnicode(false);
            entity.Property(e => e.ItemForm).IsUnicode(false);
            entity.Property(e => e.ItemName).IsUnicode(false);
            entity.Property(e => e.ItemNotes).IsUnicode(false);
            entity.Property(e => e.ItemRemarks).IsUnicode(false);
            entity.Property(e => e.ItemSlNo).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.MasterSlNo).HasColumnType("decimal(18, 0)");
            entity.Property(e => e.Module).IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TblUserMaster>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("tblUserMaster");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.CompanyId).HasColumnName("CompanyID");
            entity.Property(e => e.CreatedBy).IsUnicode(false);
            entity.Property(e => e.CreatedOn).HasColumnType("datetime");
            entity.Property(e => e.EmailAddress).IsUnicode(false);
            entity.Property(e => e.HrlevelCode).HasColumnName("HRLevelCode");
            entity.Property(e => e.HrtimeSheetProjectGroup).HasColumnName("HRTimeSheetProjectGroup");
            entity.Property(e => e.InventoryMpraccess).HasColumnName("InventoryMPRAccess");
            entity.Property(e => e.LastLogOffTime).HasColumnType("datetime");
            entity.Property(e => e.LastLogOnTime).HasColumnType("datetime");
            entity.Property(e => e.LogTerminal).HasMaxLength(50);
            entity.Property(e => e.MobileNo).IsUnicode(false);
            entity.Property(e => e.ModifiedBy).IsUnicode(false);
            entity.Property(e => e.ModifiedOn).HasColumnType("datetime");
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PettyCashAccount)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserName).HasMaxLength(50);
            entity.Property(e => e.UserPicture).HasColumnType("image");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}