using DevExpress.Pdf.Native.BouncyCastle.Utilities;
using DevExtreme.AspNet.Data;
using DevExtreme.AspNet.Data.ResponseModel;
using DevExtreme.AspNet.Mvc;
using Humanizer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.Identity.Client;
using QD.ERP.Web.Areas.Finance.Models;
using QD.ERP.Web.Areas.Finance.Reports.Payable_Statements;
using QD.ERP.Web.DAL.Entities;
using QD.ERP.Web.Service;
using QD.ERP.Web.Services.Logging;
using System;
using System.Dynamic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
namespace QD.ERP.Web.Areas.IMS.Controllers
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class PurchaseOrdersController : Controller
    {
        private readonly TenantDbContextHelper _tenantDbContextHelper;
        private readonly ILogger<PurchaseOrdersController> _logger;
        private readonly IUserActionLogger _userActionLogger;


        public PurchaseOrdersController(ILogger<PurchaseOrdersController> logger, TenantDbContextHelper tenantDbContextHelper, IUserActionLogger userActionLogger)
        {
            _userActionLogger = userActionLogger;
            _tenantDbContextHelper = tenantDbContextHelper;
            _logger = logger;
        }
        [HttpGet]
        public async Task<IActionResult> GetPurchaseOrders(DateTime? fromDate, DateTime? toDate)
        {
            try
            {
                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    var query = dbContext.Qry60404purchaseOrderViewMasters.AsQueryable();


                    // Default dates if not provided
                    if (!fromDate.HasValue)
                    {
                        fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1); // Start of the current month
                    }

                    if (!toDate.HasValue)
                    {
                        toDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)); // End of the current month
                    }

                    // Filtering by date range
                    query = query.Where(i => i.Podate >= fromDate && i.Podate <= toDate);

                    // Fetching the data
                    var data = await query.Select(i => new
                    {
                        i.Pono,
                        i.PorevisionNo,
                        i.Podate,
                        i.SupplierName,
                        i.IsSubmitted,
                        i.IsVerified,
                        i.IsApproved,
                        i.NoOfItems,
                        i.OrderStatus,
                        i.BillStatus,
                        i.TotalBeforeTax,
                        i.TotalDiscount,
                        i.TotalAfterDiscount,
                        i.TotalTaxAmount,
                        i.TotalWithTax,
                        i.AdditionsAmount,
                        i.DeductionsAmount,
                        i.GrandTotal,
                    }).ToListAsync();

                    return Json(data);
                }

                return Unauthorized(new { message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in GetProject: {ex.Message}");
                return StatusCode(500, new { message = ex.Message });
            }

            }
     
        public IActionResult GetAutoGeneratedPurchaseorderNumber()
        {
            try
            {
                // Step 1: Get DB context
                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    // Step 2: Get DefaultcompanyID from session
                    string defaultCompanyString = HttpContext.Session.GetString("DefaultcompanyID") ?? "";
                    byte defaultCompanyByte = 0;

                    if (!string.IsNullOrEmpty(defaultCompanyString))
                    {
                        byte.TryParse(defaultCompanyString, out defaultCompanyByte);
                    }

                    byte companyId = defaultCompanyByte;

                    // Step 3: Get company details by CompanyId
                    var company = dbContext.Tbl901CompanyDetails
                        .FirstOrDefault(c => c.CompanyId == companyId);

                    if (company == null)
                    {
                        return NotFound("Company not found in Tbl901CompanyDetails.");
                    }

                    // Step 4: Get PurchaseOrderAbbrv, year digit, reset flag, and number of digits
                    string purchaseOrderAbbrv = company.PurchaseOrderAbbrv ?? "";
                    int yearInDigit = company.InvoiceYearDigits ?? 0;
                    bool isResetByYear = company.IsResetInvoiceInYear ?? false;

                    int noOfDigits = dbContext.Tbl901CompanyDetails02s
                        .Where(c => c.CompanyId == company.CompanyId)
                        .Select(c => c.NoOfDigitsToInventoryQuotation ?? 5)
                        .FirstOrDefault();

                    DateTime currentDate = DateTime.Now;
                    string yearPart = currentDate.Year.ToString();

                    if (yearInDigit > 0)
                        yearPart = yearPart.Substring(yearPart.Length - yearInDigit, yearInDigit);
                    else
                        yearPart = "";

                    string basePrefix = $"{purchaseOrderAbbrv}{yearPart}-";

                    // Step 5: Get existing matching PO numbers
                    var poNos = dbContext.Tbl60401purchaseOrderMasters
                        .Where(x => x.Pono.StartsWith(basePrefix))
                        .Select(x => x.Pono)
                        .ToList();

                    // Step 6: Extract and compute next number
                    int maxNumber = poNos
                        .Select(no => int.TryParse(no?.Substring(no.Length - noOfDigits), out int num) ? num : 0)
                        .DefaultIfEmpty(0)
                        .Max();

                    int nextNumber = maxNumber + 1;
                    string nextPono = $"{basePrefix}{nextNumber.ToString().PadLeft(noOfDigits, '0')}";

                    return Ok(new { Pono = nextPono, success = true });
                }
                else
                {
                    _logger.LogWarning("Invalid tenant context when generating PurchaseOrderNo.");
                    return Unauthorized(new { message = "Invalid tenant." });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in GetAutoGeneratedPurchaseorderNumber: {ex.Message}");
                return StatusCode(500, new { message = "An error occurred while generating Purchase Order No.", error = ex.Message });
            }
        }



        private string GetAbbreviatedCompanyCode(string companyNameShort)
        {
            if (string.IsNullOrWhiteSpace(companyNameShort))
                return "UNK"; // Default fallback

            var trimmed = companyNameShort.Trim();

            if (trimmed.Length <= 5)
                return trimmed.ToUpper();

            var words = trimmed.Split(new[] { ' ', '-', '_' }, StringSplitOptions.RemoveEmptyEntries);
            var initials = string.Concat(words.Select(w => char.ToUpper(w[0])));

            return initials.Length >= 3 ? initials.Substring(0, 3) : initials.PadRight(3);
        }

        [HttpGet]
        public IActionResult GetClients(DataSourceLoadOptions loadOptions)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var query = dbContext.Tbl30199SupplierMasters
                    .Where(c => c.IsDiscontinued != true)
                    .Select(c => new
                    {
                        c.SupplierCode,
                        c.SupplierName
                    });

                return Json(DataSourceLoader.Load(query, loadOptions));
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }

        [HttpGet]
        public async Task<IActionResult> GetProjects()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var projects = await dbContext.Qry70002projectsViewMasters
                    .Select(p => new
                    {
                        ProjectId = p.ProjectId,
                        ProjectDescription = p.ProjectDescription
                    })
                    .ToListAsync();

                return Json(projects);
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetSalesPerson(DataSourceLoadOptions loadOptions)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var ClientCategory = dbContext.Tbl20101SalesPersonMasters.Select(i => new
                    {
                        i.SalesPersonCode,
                        i.SalesPersonName
                    });

                    return Json(await DataSourceLoader.LoadAsync(ClientCategory, loadOptions));
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in GetSalesPerson: {ex.Message}");
                    return StatusCode(500, new { message = "An error occurred while fetching the data.", error = ex.Message });
                }
            }

            return Unauthorized(new { message = "Invalid tenant.", success = false });
        }
        [HttpGet]
        public async Task<IActionResult> GetRequestingUnits()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var units = await dbContext.Tbl60604purchaseRequestProjectSubUnits
                        .Select(u => new
                        {
                            ProjectSubUnitCode = u.ProjectSubUnitCode,
                            ProjectSubUnitName = u.ProjectSubUnitName
                        })
                        .ToListAsync();

                    return Json(units);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Requesting Units: {ex.Message}");
                    return StatusCode(500, "Failed to load Requesting Units");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        
        [HttpGet]
        public async Task<IActionResult> GetTypeOfRequests(DataSourceLoadOptions loadOptions)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var ClientCategory = dbContext.Tbl30104TypeOfRequestMasters.Select(i => new
                    {
                        i.TypeOfRequestId,
                        i.TypeOfRequest

                    });

                    return Json(await DataSourceLoader.LoadAsync(ClientCategory, loadOptions));
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in GetProject: {ex.Message}");
                    return StatusCode(500, new { message = "An error occurred while fetching the data.", error = ex.Message });
                }
            }

            return Unauthorized(new { message = "Invalid tenant.", success = false });
        }
        [HttpGet]
        public async Task<IActionResult> GetPOCategories()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var categories = await dbContext.Tbl60404pocategories
                        .Select(x => new
                        {
                            POCategoryCode = x.PocategoryId,
                            POCategoryName = x.PocategoryName
                        })
                        .ToListAsync();

                    return Json(categories);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading PO Categories: {ex.Message}");
                    return StatusCode(500, "Failed to load PO Categories");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetInventoryGroups()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var groups = await dbContext.Tbl60008inventoryMasterGroups
                        .Select(x => new
                        {
                            InventoryMasterGroupId = x.InventoryMasterGroupId,
                            InventoryMasterGroup = x.InventoryMasterGroup
                        })
                        .ToListAsync();

                    return Json(groups);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading Inventory Groups: {ex.Message}");
                    return StatusCode(500, "Failed to load Inventory Groups");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetCurrencyList()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var currencies = await dbContext.Tbl20169CurrencyExchanges
                        .OrderBy(c => c.CurrencyName)
                        .Select(c => new
                        {
                            CurrencyExchangeId = c.CurrencyExchangeId,
                            CurrencyName = c.CurrencyName
                        })
                        .ToListAsync();

                    return Json(currencies);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading currency list: {ex.Message}");
                    return StatusCode(500, "Failed to load currency list");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpGet]
        public async Task<IActionResult> GetDocumentSignatories()
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var signatories = await dbContext.Tbl90104DocumentSignatories
                        .Select(s => new
                        {
                            SignatoryId = s.SignatoryId,
                            SignatoryName = s.SignatoryName
                        })
                        .ToListAsync();

                    return Json(signatories);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error loading signatories: {ex.Message}");
                    return StatusCode(500, "Failed to load document signatories");
                }
            }

            return BadRequest("Unable to resolve tenant or database context.");
        }
        [HttpPost]
        public async Task<IActionResult> SavePurchaseOrder1([FromBody] Tbl60401purchaseOrderMaster model)
        {
            if (model == null || !ModelState.IsValid)
                return BadRequest(new { message = "Invalid data", success = false });

            if (string.IsNullOrWhiteSpace(model.Pono))
                return BadRequest(new { message = "PO No is required", success = false });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            try
            {
                string userName = HttpContext.Session.GetString("UserName") ?? "System";

                var existingPo = await dbContext.Tbl60401purchaseOrderMasters
                    .FirstOrDefaultAsync(x => x.Pono == model.Pono);

                if (existingPo == null)
                {
                    // New PO - initialize states
                    model.AddedBy = userName;
                    model.AddedOn = DateTime.Now;
                    model.IsApproved = false;
                    model.IsVerified = false;
                    model.IsSubmitted = model.IsSubmitted ?? false;

                    if (model.IsSubmitted == true)
                    {
                        model.SubmittedBy = userName;
                        model.SubmittedOn = DateTime.Now;
                    }

                    dbContext.Tbl60401purchaseOrderMasters.Add(model);
                }
                else
                {
                    // If already approved, do NOT allow editing
                    if (existingPo.IsApproved == true)
                    {
                        return BadRequest(new { message = "This purchase order has been approved and cannot be edited.", success = false });
                    }

                    // Update fields normally
                    existingPo.Podate = model.Podate;
                    existingPo.SupplierCode = model.SupplierCode;
                    existingPo.SupplierQuoteNo = model.SupplierQuoteNo;
                    existingPo.SupplierQuoteDate = model.SupplierQuoteDate;
                    existingPo.SupplierRefNo = model.SupplierRefNo;
                    existingPo.Attention = model.Attention;
                    existingPo.SupplierContactNo = model.SupplierContactNo;
                    existingPo.SupplierContactEmail = model.SupplierContactEmail;
                    existingPo.SubjectTitle = model.SubjectTitle;

                    // Handle submit, verify, approve logic

                    // Submit
                    if (model.IsSubmitted == true && existingPo.IsSubmitted != true)
                    {
                        existingPo.IsSubmitted = true;
                        existingPo.SubmittedBy = userName;
                        existingPo.SubmittedOn = DateTime.Now;
                    }

                    // Verify - only if submitted and not verified yet
                    if (model.IsVerified == true && existingPo.IsVerified != true)
                    {
                        if (existingPo.IsSubmitted != true)
                        {
                            return BadRequest(new { message = "Cannot verify before submitting.", success = false });
                        }
                        existingPo.IsVerified = true;
                        existingPo.VerifiedBy = userName;
                        existingPo.VerifiedOn = DateTime.Now;
                    }

                    // Approve - only if verified and not approved yet
                    if (model.IsApproved == true && existingPo.IsApproved != true)
                    {
                        if (existingPo.IsVerified != true)
                        {
                            return BadRequest(new { message = "Cannot approve before verification.", success = false });
                        }
                        existingPo.IsApproved = true;
                        existingPo.ApprovedBy = userName;
                        existingPo.ApprovedOn = DateTime.Now;
                    }

                    // Update other fields that can be changed before approval
                    existingPo.PreparedBy = model.PreparedBy;
                    existingPo.PreparedOn = model.PreparedOn;
                    existingPo.Project = model.Project;
                    existingPo.Pointroduction = model.Pointroduction;
                    existingPo.Posummary = model.Posummary;
                    existingPo.RevisionNo = model.RevisionNo;
                    existingPo.CompanyBranch = model.CompanyBranch;
                    existingPo.AdditionsText = model.AdditionsText;
                    existingPo.DiscountsText = model.DiscountsText;
                    existingPo.PodueDate = model.PodueDate;
                    existingPo.Posignatory = model.Posignatory;
                    existingPo.AdditionsAmount = model.AdditionsAmount;
                    existingPo.DeductionsAmount = model.DeductionsAmount;
                    existingPo.Rfqno = model.Rfqno;
                    existingPo.TypeOfRequest = model.TypeOfRequest;
                    existingPo.PothanksNote = model.PothanksNote;
                    existingPo.ProjectMasterCode = model.ProjectMasterCode;
                    existingPo.PoverifiedSign = model.PoverifiedSign;
                    existingPo.PoapprovedSign = model.PoapprovedSign;
                    existingPo.PopaymentTerm = model.PopaymentTerm;
                    existingPo.PodeliveryTerm = model.PodeliveryTerm;
                    existingPo.PodeliveryPeriod = model.PodeliveryPeriod;
                    existingPo.PodocRequired = model.PodocRequired;
                    existingPo.PowarrantyPeriod = model.PowarrantyPeriod;
                    existingPo.PoshipTo = model.PoshipTo;
                    existingPo.PobillTo = model.PobillTo;
                    existingPo.PorevisionNo = model.PorevisionNo;
                    existingPo.Currency = model.Currency;
                    existingPo.ExchangeRate = model.ExchangeRate;
                    existingPo.PocategoryId = model.PocategoryId;
                    existingPo.PorevisionId = model.PorevisionId;
                    existingPo.IsObseleteVersion = model.IsObseleteVersion;
                    existingPo.PorevisedBy = model.PorevisedBy;
                    existingPo.PorevisedOn = model.PorevisedOn;
                    existingPo.InventoryMasterGroupId = model.InventoryMasterGroupId;
                    existingPo.SalesPersonCode = model.SalesPersonCode;
                    existingPo.Mprno = model.Mprno;
                    existingPo.ProjectSubUnitCode = model.ProjectSubUnitCode;
                    existingPo.CurrencyId = model.CurrencyId ?? 1;
                    existingPo.CurrencyRate = model.CurrencyRate ?? 1;
                    existingPo.BaseCurrencyId = model.BaseCurrencyId ?? 1;
                    existingPo.ModifiedBy = userName;
                    existingPo.ModifiedOn = DateTime.Now;
                }

                await dbContext.SaveChangesAsync();
                await _userActionLogger.LogAsync(
                  module: "IMS > Save Purchase Order1",
                  actionDetail: $"Saved Purchase Order1  {model.PocategoryId}",
                  documentNo: $"{model.PocategoryId}"
                );

                return Ok(new
                {
                    message = "Purchase order saved successfully",
                    pono = model.Pono,
                    isApproved = existingPo?.IsApproved ?? model.IsApproved ?? false,
                    success = true
                });

            }
            catch (Exception ex)
            {
                return StatusCode(500, new { message = "Error saving purchase order: " + ex.Message, success = false });
            }
        }
      [HttpPost]
public async Task<IActionResult> SavePurchaseOrder([FromBody] PurchaseOrderViewModel model)
{
    if (model == null || model.Master == null)
        return BadRequest(new { success = false, message = "Invalid data." });

    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
        return Unauthorized(new { success = false, message = "Invalid tenant." });

    var strategy = dbContext.Database.CreateExecutionStrategy();
    try
    {
        await strategy.ExecuteAsync(async () =>
        {
            using var transaction = await dbContext.Database.BeginTransactionAsync();

            var master = model.Master;
            var children = model.Children ?? new List<Tbl60402purchaseOrderChild>();
            var pono = master.Pono?.Trim();
            string userName = HttpContext.Session.GetString("UserName") ?? "System";

            // --- MASTER UPSERT ---
            var existingPo = await dbContext.Tbl60401purchaseOrderMasters
                     .FirstOrDefaultAsync(x => x.Pono == master.Pono);

            if (existingPo == null)
            {
                master.AddedBy = userName;
                master.AddedOn = DateTime.Now;
                master.IsApproved = false;
                master.IsVerified = false;
                master.IsSubmitted = master.IsSubmitted ?? false;

                if (master.IsSubmitted == true)
                {
                    master.SubmittedBy = userName;
                    master.SubmittedOn = DateTime.Now;
                }

                dbContext.Tbl60401purchaseOrderMasters.Add(master);
            }
            else
            {
                // If already approved, do NOT allow editing
                if (existingPo.IsApproved == true)
                {
                    throw new Exception("This purchase order has been approved and cannot be edited.");
                }

                // Update all fields (copy from master to existingPo)
                existingPo.Podate = master.Podate;
                existingPo.SupplierCode = master.SupplierCode;
                existingPo.SupplierQuoteNo = master.SupplierQuoteNo;
                existingPo.SupplierQuoteDate = master.SupplierQuoteDate;
                existingPo.SupplierRefNo = master.SupplierRefNo;
                existingPo.Attention = master.Attention;
                existingPo.SupplierContactNo = master.SupplierContactNo;
                existingPo.SupplierContactEmail = master.SupplierContactEmail;
                existingPo.SubjectTitle = master.SubjectTitle;
                existingPo.Project = master.Project;
                existingPo.ProjectMasterCode = master.ProjectMasterCode;
                existingPo.ProjectSubUnitCode = master.ProjectSubUnitCode;
                existingPo.PodueDate = master.PodueDate;

                existingPo.PreparedBy = master.PreparedBy;
                existingPo.PreparedOn = master.PreparedOn;
                existingPo.PorevisedBy = master.PorevisedBy;
                existingPo.PorevisedOn = master.PorevisedOn;
                existingPo.RevisionNo = master.RevisionNo;
                existingPo.IsObseleteVersion = master.IsObseleteVersion;
                existingPo.Posignatory = master.Posignatory;
                existingPo.PopaymentTerm = master.PopaymentTerm;
                existingPo.PodeliveryTerm = master.PodeliveryTerm;
                existingPo.PorevisionNo = master.PorevisionNo;
                existingPo.PodeliveryPeriod = master.PodeliveryPeriod;
                existingPo.PodocRequired = master.PodocRequired;
                existingPo.PowarrantyPeriod = master.PowarrantyPeriod;
                existingPo.PoshipTo = master.PoshipTo;
                existingPo.PobillTo = master.PobillTo;
                existingPo.Currency = master.Currency;
                existingPo.ExchangeRate = master.ExchangeRate;
                existingPo.PothanksNote = master.PothanksNote;
                existingPo.AdditionsText = master.AdditionsText;
                existingPo.DiscountsText = master.DiscountsText;
                existingPo.AdditionsAmount = master.AdditionsAmount;
                existingPo.DeductionsAmount = master.DeductionsAmount;
                existingPo.InventoryMasterGroupId = master.InventoryMasterGroupId;
                existingPo.PocategoryId = master.PocategoryId;
                existingPo.Rfqno = master.Rfqno;
                existingPo.TypeOfRequest = master.TypeOfRequest;
                existingPo.Pointroduction = master.Pointroduction;
                existingPo.Posummary = master.Posummary;
                existingPo.CompanyBranch = master.CompanyBranch;
                existingPo.SalesPersonCode = master.SalesPersonCode;
                existingPo.PoverifiedSign = master.PoverifiedSign;
                existingPo.PoapprovedSign = master.PoapprovedSign;
                existingPo.CurrencyId = master.CurrencyId ?? 1;
                existingPo.CurrencyRate = master.CurrencyRate ?? 1;
                existingPo.BaseCurrencyId = master.BaseCurrencyId ?? 1;
                existingPo.Posignatory = master.Posignatory;
                existingPo.PoverifiedSign = master.PoverifiedSign;
                existingPo.PoapprovedSign = master.PoapprovedSign;
                // Submit
                if (master.IsSubmitted == true && existingPo.IsSubmitted != true)
                {
                    existingPo.IsSubmitted = true;
                    existingPo.SubmittedBy = userName;
                    existingPo.SubmittedOn = DateTime.Now;
                }

                // Verify
                if (master.IsVerified == true && existingPo.IsVerified != true)
                {
                    if (existingPo.IsSubmitted != true)
                        throw new Exception("Cannot verify before submitting.");
                    existingPo.IsVerified = true;
                    existingPo.VerifiedBy = userName;
                    existingPo.VerifiedOn = DateTime.Now;
                }

                // Approve
                if (master.IsApproved == true && existingPo.IsApproved != true)
                {
                    if (existingPo.IsVerified != true)
                        throw new Exception("Cannot approve before verification.");
                    existingPo.IsApproved = true;
                    existingPo.ApprovedBy = userName;
                    existingPo.ApprovedOn = DateTime.Now;
                }

                existingPo.ModifiedBy = userName;
                existingPo.ModifiedOn = DateTime.Now;
            }

            // --- CHILDREN UPSERT/DELETE ---
            var existingChildren = await dbContext.Tbl60402purchaseOrderChildren
                .Where(x => x.Pono == pono)
                .ToListAsync();

            var incomingChildren = children;
            var incomingIds = incomingChildren.Where(c => c.PochildNo > 0).Select(c => c.PochildNo).ToList();

            // Update existing children
            foreach (var child in incomingChildren.Where(c => c.PochildNo > 0))
            {
                var entity = existingChildren.FirstOrDefault(x => x.PochildNo == child.PochildNo);
                if (entity != null)
                {
                    dbContext.Entry(entity).CurrentValues.SetValues(child);
                }
            }

            // Insert new children
            var newChildren = incomingChildren.Where(c => c.PochildNo == 0).ToList();
            foreach (var child in newChildren)
            {
                child.Pono = pono;
                child.ItemDiscount = child.ItemDiscount * master.CurrencyRate;
                child.UnitPrice = child.UnitPrice * master.CurrencyRate;
                await dbContext.Tbl60402purchaseOrderChildren.AddAsync(child);
            }

            // Delete removed children
            var toDelete = existingChildren.Where(x => !incomingIds.Contains(x.PochildNo)).ToList();
            if (toDelete.Any())
                dbContext.Tbl60402purchaseOrderChildren.RemoveRange(toDelete);

            await dbContext.SaveChangesAsync();
            await _userActionLogger.LogAsync(
              module: "IMS > Save Purchase Order",
              actionDetail: $"Saved Purchase Order  {model.Master.Pono}",
              documentNo: $"{model.Master.Pono}"
            );
            await transaction.CommitAsync();
        });

        return Ok(new { success = true, message = "Purchase order saved successfully.", pono = model.Master.Pono });
    }
    catch (Exception ex)
    {
        return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
    }
}
        [HttpPost]
        public async Task<IActionResult> SaveItem([FromBody] List<Tbl60402purchaseOrderChild> items)
        {
            if (items == null || items.Count == 0)
                return BadRequest(new { success = false, message = "No items to save." });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                return Unauthorized(new { success = false, message = "Invalid tenant." });

            try
            {
                var pono = items[0].Pono;

                // Use direct SQL to delete all children for this PO
                dbContext.Database.ExecuteSqlRaw("DELETE FROM tbl604_02PurchaseOrderChild WHERE Pono = {0}", pono);

                // Insert all new/edited rows
                await dbContext.Tbl60402purchaseOrderChildren.AddRangeAsync(items);
                await dbContext.SaveChangesAsync();
                await _userActionLogger.LogAsync(
                  module: "IMS > Save Item",
                  actionDetail: $"Saved Item  {items[0].Pono}",
                  documentNo: $"{items[0].Pono}"
                );

                return Ok(new { success = true, message = "Items saved successfully." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
            }
        }

        [HttpPost("UpdateItem")]
        public async Task<IActionResult> UpdateItem([FromBody] Tbl60402purchaseOrderChild updatedItem)
        {
            try
            {
                if (!ModelState.IsValid)
                    return BadRequest(ModelState);

                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                {
                    var existingItem = await dbContext.Tbl60402purchaseOrderChildren
                        .FirstOrDefaultAsync(i => i.PochildNo == updatedItem.PochildNo);

                    if (existingItem == null)
                        return NotFound(new { success = false, message = "Item not found." });

                    // Update only the available properties
                    existingItem.Pono = updatedItem.Pono;
                    existingItem.Gscode = updatedItem.Gscode;
                    existingItem.AddlDescription = updatedItem.AddlDescription;
                    existingItem.QuotedQuantity = updatedItem.QuotedQuantity;
                    existingItem.UnitRateMethod = updatedItem.UnitRateMethod;
                    existingItem.UnitPrice = updatedItem.UnitPrice;
                    existingItem.ItemDiscount = updatedItem.ItemDiscount;
                    existingItem.PotaxSlab = updatedItem.PotaxSlab;
                    existingItem.PoitemRemarks = updatedItem.PoitemRemarks;
                    existingItem.LineOrderNo = updatedItem.LineOrderNo;
                    existingItem.PlanNo = updatedItem.PlanNo;
                    existingItem.DeliveryPeriod = updatedItem.DeliveryPeriod;
                    existingItem.MritemNo = updatedItem.MritemNo;
                    existingItem.Currency = updatedItem.Currency;
                    existingItem.ExchangeRate = updatedItem.ExchangeRate;
                    existingItem.UnitRateInOc = updatedItem.UnitRateInOc;
                    existingItem.DiscountInOc = updatedItem.DiscountInOc;

                    await dbContext.SaveChangesAsync();
                    await _userActionLogger.LogAsync(
                      module: "IMS > Save Item",
                      actionDetail: $"Saved Item  {updatedItem.PochildNo}",
                      documentNo: $"{updatedItem.PochildNo}"
                    );

                    return Ok(new { success = true, message = "Item updated successfully." });
                }

                return Unauthorized(new { success = false, message = "Invalid tenant." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = $"Server error: {ex.Message}" });
            }
        }
  
    [HttpGet]
public async Task<IActionResult> GetByPoNo(string poNo, byte? revisionId)
{
            if (string.IsNullOrWhiteSpace(poNo))
        return BadRequest(new { message = "PO No is required", success = false });

    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
        return Unauthorized(new { message = "Invalid tenant", success = false });

    try
    {
       var master = await dbContext.Tbl60401purchaseOrderMasters
                    .FirstOrDefaultAsync(x => x.Pono == poNo);

        if (master == null)
            return NotFound(new { message = "Purchase Order not found", success = false });

                var children = await dbContext.Qry60402purchaseOrderChildren
                    .Where(x => x.Pono == poNo)
            .ToListAsync();
                // Load descriptions into dictionaries
                //var gsDescriptions = await dbContext.Tbl20164GoodsAndServicesMasters
                //    .ToDictionaryAsync(x => x.Gscode, x => x.Gsdescrpition);

                //var unitDescriptions = await dbContext.Tbl40111PropertyUnitCodes
                //    .ToDictionaryAsync(x => x.UnitCode, x => x.UnitDesc);


                return Ok(new
        {
            success = true,

            // Master fields
            pono = master.Pono,
            podate = master.Podate,
            supplierCode = master.SupplierCode,
            supplierQuoteNo = master.SupplierQuoteNo,
            supplierQuoteDate = master.SupplierQuoteDate,
            supplierRefNo = master.SupplierRefNo,
            attention = master.Attention,
            supplierContactNo = master.SupplierContactNo,
            supplierContactEmail = master.SupplierContactEmail,
            subjectTitle = master.SubjectTitle,
            project = master.Project,
            projectMasterCode = master.ProjectMasterCode,
            projectSubUnitCode = master.ProjectSubUnitCode,
            podueDate = master.PodueDate,
            preparedBy = master.PreparedBy,
            PorevisionNo = master.PorevisionNo,
            preparedOn = master.PreparedOn,
            revisedBy = master.PorevisedBy,
            revisedOn = master.PorevisedOn,
            revisionNo = master.RevisionNo,
            isObseleteVersion = master.IsObseleteVersion,
            posignatory = master.Posignatory,
            poverifiedSign= master.PoverifiedSign,
             poapprovedSign =  master.PoapprovedSign,


            popaymentTerm = master.PopaymentTerm,
            podeliveryTerm = master.PodeliveryTerm,
            podeliveryPeriod = master.PodeliveryPeriod,
            podocRequired = master.PodocRequired,
            powarrantyPeriod = master.PowarrantyPeriod,
            poshipTo = master.PoshipTo,
            pobillTo = master.PobillTo,
            currency = master.Currency,
            exchangeRate = master.ExchangeRate,
            pothanksNote = master.PothanksNote,
            additionsText = master.AdditionsText,
            discountsText = master.DiscountsText,
            additionsAmount = master.AdditionsAmount,
            deductionsAmount = master.DeductionsAmount,
            inventoryMasterGroupId = master.InventoryMasterGroupId,
            pocategoryId = master.PocategoryId,
            rfqno = master.Rfqno,
            typeOfRequest = master.TypeOfRequest,
            pointroduction = master.Pointroduction,
            posummary = master.Posummary,
            companyBranch = master.CompanyBranch,
            salesPersonCode = master.SalesPersonCode,
            preparedBySign = master.PoverifiedSign,
            approvedBySign = master.PoapprovedSign,
            isSubmitted = master.IsSubmitted,
            submittedBy = master.SubmittedBy,
            submittedOn = master.SubmittedOn,
            isVerified = master.IsVerified,
            verifiedBy = master.VerifiedBy,
            verifiedOn = master.VerifiedOn,
            isApproved = master.IsApproved,
            approvedBy = master.ApprovedBy,
            approvedOn = master.ApprovedOn,
            CurrencyRate = master.CurrencyRate,
            BaseCurrencyId = master.BaseCurrencyId,
            CurrencyId = master.CurrencyId,

            // Children - PascalCase property names
            items = children.Select(x => new
            {
                PochildNo = x.PochildNo,
                Pono = x.Pono,
                Gscode = x.Gscode,
                //GSCode=x.Gscode,
                AddlDescription = x.AddlDescription,
        //    AddlDescription = !string.IsNullOrWhiteSpace(x.AddlDescription)
        //? x.AddlDescription
        //: (gsDescriptions.ContainsKey(x.Gscode) ? gsDescriptions[x.Gscode] : null),
                QuotedQuantity = x.QuotedQuantity,
                UnitRateMethod = x.UnitRateMethod,
    //            UnitRateMethod = x.UnitRateMethod.HasValue
    //? (unitDescriptions.ContainsKey(x.UnitRateMethod.Value) ? unitDescriptions[x.UnitRateMethod.Value] : null)
    //: null,

                UnitPrice = x.UnitPrice / master.CurrencyRate,
                ItemDiscount = x.ItemDiscount / master.CurrencyRate,
                PotaxSlab = x.PotaxSlab,
                PoitemRemarks = x.PoitemRemarks,
                LineOrderNo = x.LineOrderNo,
                PlanNo = x.PlanNo,
                DeliveryPeriod = x.DeliveryPeriod,
                MritemNo = x.MritemNo,
                Currency = x.Currency,
                ExchangeRate = x.ExchangeRate,
                LineTotalWithTax = x.LineTotalWithTax / master.CurrencyRate,
                LineTaxAmount = x.LineTaxAmount / master.CurrencyRate,
                UnitRateInOc = (x.UnitRateInOc ?? 0) / master.CurrencyRate,
                DiscountInOc = (x.DiscountInOc ?? 0) / master.CurrencyRate
            })
        });
    }
    catch (Exception ex)
    {
        return StatusCode(500, new
        {
            message = "Error loading purchase order",
            success = false,
            error = ex.Message
        });
    }
}
        [HttpGet]
        public async Task<IActionResult> GetByPoNoforVAT(string poNo, byte? revisionId)
        {
            if (string.IsNullOrWhiteSpace(poNo))
                return BadRequest(new { message = "PO No is required", success = false });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            try
            {
                var master = await dbContext.Tbl60401purchaseOrderMasters
                    .FirstOrDefaultAsync(x => x.Pono == poNo);

                if (master == null)
                    return NotFound(new { message = "Purchase Order not found", success = false });

                var children = await dbContext.Qry60402purchaseOrderChildren
                    .Where(x => x.Pono == poNo)
                    .ToListAsync();

                var enrichedChildren = new List<ExpandoObject>();
                foreach (var c in children)
                {
                    dynamic item = new ExpandoObject();
                    var dict = (IDictionary<string, object>)item;

                    // Copy existing properties
                    foreach (var prop in c.GetType().GetProperties())
                    {
                        dict[prop.Name] = prop.GetValue(c);
                    }

                    // Lookup descriptions
                    var taxRateInWord = dbContext.Tbl20168VatpurchaseTaxSlabs
                        .Where(t => t.PurchaseTaxSlabCode == c.PotaxSlab)
                        .Select(t => t.PurchaseTaxSlab)
                        .FirstOrDefault();

                    var unitRateDesc = dbContext.Tbl40111PropertyUnitCodes
                        .Where(u => u.UnitCode == c.UnitRateMethod)
                        .Select(u => u.UnitDesc)
                        .FirstOrDefault();

                    dict["VATPercentage"] = taxRateInWord;
                    dict["UnitRateMethodDesc"] = unitRateDesc;

                    // Currency normalization
                    dict["UnitPrice"] = c.UnitPrice / master.CurrencyRate;
                    dict["ItemDiscount"] = c.ItemDiscount / master.CurrencyRate;
                    dict["LineTotalWithTax"] = c.LineTotalWithTax / master.CurrencyRate;
                    dict["LineTaxAmount"] = c.LineTaxAmount / master.CurrencyRate;

                    enrichedChildren.Add(item);
                }

                return Ok(new
                {
                    success = true,
                    // Master fields
                    pono = master.Pono,
                    podate = master.Podate,
                    supplierCode = master.SupplierCode,
                    supplierQuoteNo = master.SupplierQuoteNo,
                    supplierQuoteDate = master.SupplierQuoteDate,
                    // … keep all your master fields …
                    approvedOn = master.ApprovedOn,
                    CurrencyRate = master.CurrencyRate,
                    BaseCurrencyId = master.BaseCurrencyId,
                    CurrencyId = master.CurrencyId,

                    // Children (ready for grid binding)
                    items = enrichedChildren
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new
                {
                    message = "Error loading purchase order",
                    success = false,
                    error = ex.Message
                });
            }
        }


        [HttpDelete]
        public async Task<IActionResult> DeletePurchaseOrder([FromQuery] string Pono)
        {
            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                return Unauthorized(new { success = false, message = "Invalid tenant context." });
            }

            if (string.IsNullOrEmpty(Pono))
            {
                return BadRequest(new { success = false, message = "PO number is required." });
            }

            try
            {
                // Retrieve the master record
                var masterRecord = await dbContext.Tbl60401purchaseOrderMasters
                    .FirstOrDefaultAsync(x => x.Pono == Pono);

                if (masterRecord == null)
                {
                    return NotFound(new { success = false, message = "Purchase Order not found." });
                }

                // Retrieve and remove child records
                var childRecords = dbContext.Tbl60402purchaseOrderChildren
                    .Where(x => x.Pono == Pono);

                dbContext.Tbl60402purchaseOrderChildren.RemoveRange(childRecords);

                // Remove the master record
                dbContext.Tbl60401purchaseOrderMasters.Remove(masterRecord);

                await dbContext.SaveChangesAsync();
                await _userActionLogger.LogAsync(
                  module: "IMS > Delete Purchase Order",
                  actionDetail: $"Deleted Purchase Order {Pono}",
                  documentNo: $"{Pono}"
                );

                return Ok(new { success = true, message = "Purchase Order and its details deleted successfully." });
            }
            catch (Exception ex)
            {
                _logger.LogError($"An error occurred while deleting the purchase order: {ex.Message}");
                return StatusCode(500, new { success = false, message = "An error occurred while deleting the purchase order.", error = ex.Message });
            }
        }

        [HttpPost]
        public async Task<IActionResult> DeletePoChild([FromBody] PurchaseOrderViewModel model)
        {
            if (model?.Children == null || !model.Children.Any())
                return BadRequest(new { success = false, message = "No line items specified." });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                return Unauthorized(new { success = false, message = "Invalid tenant." });

            try
            {
                foreach (var child in model.Children)
                {
                    await dbContext.Database.ExecuteSqlRawAsync(
                        "EXEC sp604_01DeletePurchaseOrderChild @POChildNo = {0}", child.PochildNo);
                }

                return Ok(new { success = true, message = "Line item(s) deleted successfully." });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = ex.Message });
            }
        }
        private async Task<int?> GetSignatoryIDfromUserID(int? userId)
        {
            if (userId == null) return null;

            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                return await dbContext.Tbl90104DocumentSignatories
                    .Where(x => x.UserId == userId)
                    .Select(x => x.SignatoryId)
                    .FirstOrDefaultAsync();
            }

            return null;
        }

        [HttpPost]
        public async Task<IActionResult> SubmitPurchaseOrder(string pono)
        {
            try
            {
                // Tenant validation
                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                    return Unauthorized(new { success = false, message = "Invalid tenant context." });

                // Validate PO number
                if (string.IsNullOrWhiteSpace(pono))
                    return BadRequest(new { success = false, message = "PO number is required." });

                // Find record
                var po = await dbContext.Tbl60401purchaseOrderMasters
                    .FirstOrDefaultAsync(x => x.Pono == pono);
                if (po == null)
                    return NotFound(new { success = false, message = "Purchase order not found." });

                // Session values
                var userName = HttpContext.Session.GetString("UserName");
                var userIdString = HttpContext.Session.GetString("UserId");

                if (!int.TryParse(userIdString, out int userId))
                    return Unauthorized(new { success = false, message = "Invalid or missing UserId in session." });

                // === Business rules ===
                if (po.IsSubmitted == true)
                    return Ok(new { success = false, message = "This purchase order is already submitted." });

                if (po.IsApproved == true)
                    return Ok(new { success = false, message = "This purchase order is already approved. You cannot submit again." });

                //if (po.IsCancelled == true)
                //    return Ok(new { success = false, message = "This purchase order has been cancelled. Submission not allowed." });

                // Update record
                po.IsSubmitted = true;
                po.SubmittedBy = userName ?? "System";
                po.SubmittedOn = DateTime.Now;
                po.ModifiedBy = userName;
                po.ModifiedOn = DateTime.Now;

                // Map to signatory (same logic as MPR)
                var signatoryId = await GetSignatoryIDfromUserID(userId);
                if (signatoryId.HasValue)
                {
                    po.Posignatory = (byte)signatoryId.Value;
                }
                else
                {
                    po.Posignatory = null;
                }

              

                // Save changes
                await dbContext.SaveChangesAsync();

                await _userActionLogger.LogAsync(
                    module: "IMS > Submit Purchase Order",
                    actionDetail: $"Submitted Purchase Order {pono}",
                    documentNo: $"{pono}"
                );

                return Ok(new
                {
                    success = true,
                    message = "Purchase order submitted successfully.",
                    VoucherApprovedBy = signatoryId
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
            }
        }



        [HttpPost]
        public async Task<IActionResult> VerifyPO(string poNo)
        {
            try
            {
                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                    return Unauthorized(new { message = "Invalid tenant context." });

                if (string.IsNullOrEmpty(poNo))
                    return BadRequest(new { message = "PO No is required." });

                var po = await dbContext.Tbl60401purchaseOrderMasters
                    .FirstOrDefaultAsync(v => v.Pono == poNo);

                if (po == null)
                    return NotFound(new { message = "Purchase Order not found." });

                var userName = HttpContext.Session.GetString("UserName");
                var userIdString = HttpContext.Session.GetString("UserId");
                if (!int.TryParse(userIdString, out int userId))
                    return Unauthorized(new { message = "Invalid or missing UserId in session." });

                // 1. Check Line Items
                var lineItemCount = await dbContext.Tbl60402purchaseOrderChildren
                    .CountAsync(c => c.Pono == poNo);
                if (lineItemCount == 0)
                    return BadRequest(new { message = "Purchase Order has no Line Items to verify." });

                // 2. Check Amount
                //var totalAmount = await dbContext
                //    .Sp60401GetPurchaseOrderChildTotal(poNo)
                //    .FirstOrDefaultAsync();
                //if (totalAmount == null || totalAmount.Total <= 0)
                //    return BadRequest(new { message = "Purchase Order has no amount to verify." });

                //// 3. Check Access Rights
                //if (!CheckIfItemIsEnabled(userId, "frm601_07PurchaseOrderEdit_btnVerify"))
                //    return BadRequest(new { message = "You have no rights to verify this PO." });

                // 4. Check Signatory
                var signatoryId = await GetSignatoryIDfromUserID(userId);
                if (!signatoryId.HasValue)
                    return BadRequest(new { message = "Verifying User is not assigned as Signatory." });

                // 5. Workflow Check
                var companySetting = await dbContext.Tbl901CompanyDetails02s.FirstOrDefaultAsync();
                bool isWorkflowEnabled = companySetting?.IsImplementPoworkflow == true;
                if (isWorkflowEnabled && po.IsSubmitted != true)
                    return BadRequest(new { message = "You must submit the PO before verification." });

                // ✅ Update PO
                po.IsVerified = true;
                po.VerifiedOn = DateTime.Now;
                po.VerifiedBy = userName;
                po.PoverifiedSign = (byte)signatoryId.Value;
               
                await dbContext.SaveChangesAsync();

                await _userActionLogger.LogAsync(
                    module: "PO > VerifyPO",
                    actionDetail: $"Verified PO: {poNo}",
                    documentNo: poNo
                );

                return Ok(new
                {
                    message = "Purchase Order has been Verified successfully.",
                    VoucherApprovedBy = signatoryId
                });
            }
            catch (Exception ex)
            {
                _logger.LogError($"Error in VerifyPO: {ex.Message}");
                return BadRequest(new { message = ex.Message });
            }
        }


        [HttpPost]
        public async Task<ActionResult> ApprovePO(string poNo)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                try
                {
                    var userName = HttpContext.Session.GetString("UserName");
                    var userIdString = HttpContext.Session.GetString("UserId");
                    if (!int.TryParse(userIdString, out int userId))
                    {
                        return Unauthorized(new { Message = "Invalid or missing UserId in session." });
                    }

                    if (string.IsNullOrEmpty(poNo))
                    {
                        return BadRequest(new { Message = "Purchase Order No is required." });
                    }

                    var purchaseOrder = dbContext.Tbl60401purchaseOrderMasters
                                                 .FirstOrDefault(po => po.Pono == poNo);

                    if (purchaseOrder == null)
                    {
                        return NotFound(new { Message = "Purchase Order No not found." });
                    }

                    // 🔍 Step 1: Check PO workflow setting
                    var companySetting = await dbContext.Tbl901CompanyDetails02s.FirstOrDefaultAsync();
                    bool isWorkflowEnabled = companySetting?.IsImplementPoworkflow == true;

                    if (isWorkflowEnabled)
                    {
                        if (purchaseOrder.IsSubmitted != true || purchaseOrder.IsVerified != true)
                        {
                            return BadRequest(new { Message = "Please verify and submit the Purchase Order before approval." });
                        }
                    }

                    // ✅ Step 2: Approve PO
                    purchaseOrder.IsApproved = true;
                    purchaseOrder.ApprovedOn = DateTime.Now;
                    purchaseOrder.ApprovedBy = userName;
               
                    var signatoryId = await GetSignatoryIDfromUserID(userId);
                    if (signatoryId.HasValue)
                    {
                        purchaseOrder.PoapprovedSign = (byte)signatoryId.Value;
                    }

                    await dbContext.SaveChangesAsync();

                    await _userActionLogger.LogAsync(
                        module: "IMS > Approve PO",
                        actionDetail: $"Approved PO: {poNo}",
                        documentNo: poNo
                    );

                    return Ok(new
                    {
                        Message = "Purchase Order has been Approved.",
                        POApprovedBy = signatoryId
                    });
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in ApprovePO: {ex.Message}");
                    return BadRequest(new { Message = ex.Message });
                }
            }

            return Unauthorized(new { Message = "Invalid tenant." });
        }


  [HttpPost]
public async Task<IActionResult> RevisePurchaseOrder1([FromBody] Tbl60401purchaseOrderMaster data)
{
    
    

    try
    {
        string oldPono = data?.Pono;
        if (string.IsNullOrWhiteSpace(oldPono))
            return BadRequest(new { success = false, message = "PO number is required." });

        if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
            return Unauthorized(new { success = false, message = "Invalid tenant." });

        // Get the latest revision
        var maxRevision = await dbContext.Tbl60401purchaseOrderMasters
            .Where(x => x.Pono == oldPono)
            .MaxAsync(x => (byte?)x.PorevisionId) ?? (byte)0;

        byte newRevisionId = (byte)(maxRevision + 1);
        string revisionNo = $"Rev-{newRevisionId:D2}";
        string addedBy = HttpContext.Session.GetString("UserName") ?? "System";

        // Call SP to create new revision
        await dbContext.Database.ExecuteSqlRawAsync(
            "EXEC sp600_28CreateNewRevisedPO @PONo = {0}, @NewPONo = {1}, @NewRevisionID = {2}, @AddedBy = {3}",
            oldPono, oldPono, newRevisionId, addedBy
        );

        // Update the new revision row
        var newPo = await dbContext.Tbl60401purchaseOrderMasters
            .FirstOrDefaultAsync(x => x.Pono == oldPono && x.PorevisionId == newRevisionId);
        if (newPo != null)
        {
            newPo.PorevisionNo = revisionNo;
            newPo.IsApproved = false;
            newPo.IsVerified = false;
            newPo.IsSubmitted = false;
            await dbContext.SaveChangesAsync();
                    await _userActionLogger.LogAsync(
                      module: "IMS > Revise Purchase Order1",
                      actionDetail: $":Revised Purchase Order1 {data.Pono}",
                      documentNo: $"{data.Pono}"
                    );
                }
        else
        {
            return StatusCode(500, new { success = false, message = "Revision row not created. Please check your stored procedure." });
        }

        return Ok(new
        {
            success = true,
            message = "Purchase Order revised successfully.",
            newPono = oldPono,
            revisionId = newRevisionId,
            revisionNo = revisionNo
        });
    }
    catch (Exception ex)
    {
        return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
    }
}


       [HttpPost]
public async Task<IActionResult> UnlockPurchaseOrder([FromBody] Tbl60401purchaseOrderMaster data)
{
    try
    {
        string pono = data?.Pono;
        if (string.IsNullOrWhiteSpace(pono))
            return BadRequest(new { success = false, message = "PO number is required." });

        if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
            return Unauthorized(new { success = false, message = "Invalid tenant." });

        var po = await dbContext.Tbl60401purchaseOrderMasters.FirstOrDefaultAsync(x => x.Pono == pono);
        if (po == null)
            return Ok(new { success = false, message = "Purchase Order not found." });

        // If any status is true, set all to false and save
        if (po.IsSubmitted == true || po.IsVerified == true || po.IsApproved == true)
        {
            po.IsSubmitted = false;
            po.IsVerified = false;
            po.IsApproved = false;
                    po.SubmittedBy = null;
                    po.VerifiedBy = null;
                    po.ApprovedBy = null;
                    po.SubmittedOn = null;
                    po.VerifiedOn = null;
                    po.ApprovedOn = null;
                   
                    await dbContext.SaveChangesAsync();
                    await _userActionLogger.LogAsync(
                      module: "IMS > Unlock Purchase Order",
                      actionDetail: $":Unlocked Purchase Order {data.Pono}",
                      documentNo: $"{data.Pono}"
                    );
                    return Ok(new { success = true, message = "Purchase Order has been unlocked" });
        }
        else
        {
            return Ok(new { success = true, message = "Already unlocked. All statuses are already false." });
        }
    }
    catch (Exception ex)
    {
        return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
    }
}

      [HttpPost]
public async Task<IActionResult> ReceiveItemPartially([FromBody] Tbl60401purchaseOrderMaster data)
{
    try
    {
        string pono = data?.Pono;
        if (string.IsNullOrWhiteSpace(pono))
            return BadRequest(new { success = false, message = "PO number is required." });

        if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
            return Unauthorized(new { success = false, message = "Invalid tenant." });

        // --- Generate receiptNoteNo using company settings and last number in Tbl60501materialReceiptMasters ---
        string tenantName = HttpContext.Session.GetString("TenantName");
        if (string.IsNullOrWhiteSpace(tenantName))
            return Unauthorized(new { message = "Tenant name not found in session.", success = false });

        var company = dbContext.Tbl901CompanyDetails
            .FirstOrDefault(c => c.CompanyNameShort == tenantName);

        if (company == null)
            return NotFound("Company not found.");

        string requestAbbrv = company.RequestAbbrv ?? "MRN";
        int yearInDigit = company.InvoiceYearDigits ?? 0;
        bool isResetByYear = company.IsResetInvoiceInYear ?? false;
        DateTime receiptDate = DateTime.Now;

        // Get the last receipt number for this year/company
        var receiptNumbers = dbContext.Tbl60501materialReceiptMasters
            .Where(d => d.ReceiptNo != null && d.ReceiptNo.Length >= 5 &&
                        (!isResetByYear || (d.ReceiptDate.HasValue && d.ReceiptDate.Value.Year == receiptDate.Year)))
            .Select(d => d.ReceiptNo)
            .ToList();

        int maxRunningNumber = receiptNumbers
            .Select(no => int.TryParse(no.Substring(no.Length - 5), out int num) ? num : 0)
            .DefaultIfEmpty(0)
            .Max();

        maxRunningNumber += 1;

        string strNewReceiptNoteNo = maxRunningNumber.ToString().PadLeft(5, '0');

        string strYear = receiptDate.Year.ToString();
        if (yearInDigit > 0)
        {
            strYear = strYear.Substring(strYear.Length - yearInDigit, yearInDigit);
        }
        else
        {
            strYear = "";
        }

        string receiptNoteNo = $"{requestAbbrv}{strYear}-{strNewReceiptNoteNo}";

        byte modeOfReceiptId = 1; // Set as needed
        string addedBy = HttpContext.Session.GetString("UserName") ?? "System";

        await dbContext.Database.ExecuteSqlRawAsync(
            "EXEC sp600_15InsertToReceiptNoteFromPurchaseOrder @ReceiptNoteNo = {0}, @ModeOfReceiptID = {1}, @PONo = {2}, @AddedBy = {3}",
            receiptNoteNo, modeOfReceiptId, pono, addedBy
        );

        return Ok(new { success = true, message = "Material Receipt created.", receiptNoteNo = receiptNoteNo, pono = pono });
    }
    catch (Exception ex)
    {
        return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
    }
}
      [HttpPost]
public async Task<IActionResult> ReceiveItemFully([FromBody] Tbl60401purchaseOrderMaster data)
{
    try
    {
        string pono = data?.Pono;
        if (string.IsNullOrWhiteSpace(pono))
            return BadRequest(new { success = false, message = "PO number is required." });

        if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
            return Unauthorized(new { success = false, message = "Invalid tenant." });

                // ✅ Get DefaultCompanyId from session
                string defaultCompanyString = HttpContext.Session.GetString("DefaultcompanyID") ?? "";
                byte defaultCompanyByte = 0;

                if (!string.IsNullOrEmpty(defaultCompanyString))
                {
                    byte.TryParse(defaultCompanyString, out defaultCompanyByte);
                }

                byte companyId = defaultCompanyByte;

                // ✅ Get company from Tbl901CompanyDetails
                var company = dbContext.Tbl901CompanyDetails
                    .FirstOrDefault(c => c.CompanyId == companyId);

                if (company == null)
                    return NotFound(new { success = false, message = "Company not found." });


                string requestAbbrv = company.RequestAbbrv ?? "MRN";
        int yearInDigit = company.InvoiceYearDigits ?? 0;
        bool isResetByYear = company.IsResetInvoiceInYear ?? false;
        DateTime receiptDate = DateTime.Now;

        // Get the last receipt number for this year/company
        var receiptNumbers = dbContext.Tbl60501materialReceiptMasters
            .Where(d => d.ReceiptNo != null && d.ReceiptNo.Length >= 5 &&
                        (!isResetByYear || (d.ReceiptDate.HasValue && d.ReceiptDate.Value.Year == receiptDate.Year)))
            .Select(d => d.ReceiptNo)
            .ToList();

        int maxRunningNumber = receiptNumbers
            .Select(no => int.TryParse(no.Substring(no.Length - 5), out int num) ? num : 0)
            .DefaultIfEmpty(0)
            .Max();

        maxRunningNumber += 1;

        string strNewReceiptNoteNo = maxRunningNumber.ToString().PadLeft(5, '0');

        string strYear = receiptDate.Year.ToString();
        if (yearInDigit > 0)
        {
            strYear = strYear.Substring(strYear.Length - yearInDigit, yearInDigit);
        }
        else
        {
            strYear = "";
        }

        string receiptNoteNo = $"{requestAbbrv}{strYear}-{strNewReceiptNoteNo}";

        byte modeOfReceiptId = 1; // Set as needed
        string addedBy = HttpContext.Session.GetString("UserName") ?? "System";

        await dbContext.Database.ExecuteSqlRawAsync(
            "EXEC sp600_16InsertToPartialReceiptFromPurchaseOrder @ReceiptNoteNo = {0}, @ModeOfReceiptID = {1}, @PONo = {2}, @AddedBy = {3}",
            receiptNoteNo, modeOfReceiptId, pono, addedBy
        );

        return Ok(new { success = true, message = "Material Receipt created.", receiptNoteNo = receiptNoteNo, pono = pono });
    }
    catch (Exception ex)
    {
        return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
    }
}
        [HttpGet]
        public IActionResult GetSupplierByPoNo(string poNo)
        {
            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                return Unauthorized(new { message = "Invalid tenant", success = false });

            var po = dbContext.Tbl60401purchaseOrderMasters.FirstOrDefault(x => x.Pono == poNo);
            if (po == null) return NotFound();

            // FIX: Use Tbl30199SupplierMasters instead of Suppliers
            var supplier = dbContext.Tbl30199SupplierMasters.FirstOrDefault(s => s.SupplierCode == po.SupplierCode);
            return Ok(new { supplierName = supplier?.SupplierName });
        }
        
        [HttpGet]
public IActionResult GetByPoNos(string poNo)
{
    try
    {
        if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            return Unauthorized(new { message = "Invalid tenant", success = false });

        var notes = dbContext.Qry60511materialReceiptNotesWithDetails
            .Where(x => x.OurPurchaseOrderNo == poNo)
            .Select(x => new {
                x.ReceiptNo,
                x.ReceiptDate,
                x.SupplierName,
                OurPurchaseOrderNo = x.OurPurchaseOrderNo,
                x.OrderStatus,
                x.BillStatus
            })
            .ToList();
        return Ok(notes);
    }
    catch (Exception ex)
    {
        return StatusCode(500, new { message = ex.Message, stack = ex.StackTrace });
    }
}
[HttpGet]
public IActionResult GetDeliveryNotes(string poNo, string supplierName)
{
    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
        return Unauthorized(new { message = "Invalid tenant", success = false });

    var query = dbContext.Qry60511materialReceiptNotesWithDetails.AsQueryable();

    if (!string.IsNullOrWhiteSpace(poNo))
        query = query.Where(x => x.OurPurchaseOrderNo.Trim().ToLower() == poNo.Trim().ToLower());

    if (!string.IsNullOrWhiteSpace(supplierName))
        query = query.Where(x => x.SupplierName.Trim().ToLower() == supplierName.Trim().ToLower());

    var notes = query.Select(x => new {
        x.ReceiptNo,
        x.ReceiptDate,
        x.SupplierName,
        OurPurchaseOrderNo = x.OurPurchaseOrderNo,
        x.OrderStatus,
        x.BillStatus
    }).ToList();

    return Ok(notes);
}
[HttpGet]
public IActionResult GetAllSuppliers()
{
    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
        return Unauthorized(new { message = "Invalid tenant", success = false });

    var suppliers = dbContext.Tbl30199SupplierMasters
        .Select(s => new { s.SupplierCode, s.SupplierName })
        .ToList();
    return Ok(suppliers);
}

[HttpGet]
public IActionResult GetAllPurchaseOrders()
{
    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
        return Unauthorized(new { message = "Invalid tenant", success = false });

    var pos = dbContext.Tbl60401purchaseOrderMasters
        .Select(po => new { po.Pono })
        .ToList();
    return Ok(pos);
}

        [HttpPost]
        public async Task<IActionResult> RevisePurchaseOrder([FromBody] Tbl60401purchaseOrderMaster data)
        {
            try
            {
                string oldPono = data?.Pono;
                if (string.IsNullOrWhiteSpace(oldPono))
                    return BadRequest(new { success = false, message = "PO number is required." });

                if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                    return Unauthorized(new { success = false, message = "Invalid tenant." });

                var oldPo = await dbContext.Tbl60401purchaseOrderMasters
                    .Where(x => x.Pono == oldPono)
                    .OrderByDescending(x => x.PorevisionId)
                    .FirstOrDefaultAsync();

                if (oldPo == null)
                    return Ok(new { success = false, message = "Purchase Order not found." });

 // --- NEW: Reset statuses if any is true ---
        if (oldPo.IsApproved == true || oldPo.IsVerified == true || oldPo.IsSubmitted == true)
        {
            oldPo.IsApproved = false;
            oldPo.IsVerified = false;
            oldPo.IsSubmitted = false;
            await dbContext.SaveChangesAsync();
                    await _userActionLogger.LogAsync(
                      module: "IMS > Revise Purchase Order",
                      actionDetail: $":Revised Purchase Order {data.Pono}",
                      documentNo: $"{data.Pono}"
                    );
                }
                // ✅ Generate new revision values
                int newRevisionId = (oldPo.PorevisionId ?? 0) + 1;
                string newRevisionNo = $"Rev-{newRevisionId:00}";
                string newPono = $"{oldPono}-R{newRevisionId}";
                string addedBy = HttpContext.Session.GetString("UserName") ?? "System";

                // ✅ Only execute stored procedure, no DB insert
                await dbContext.Database.ExecuteSqlRawAsync(
                    "EXEC sp600_28CreateNewRevisedPO @PONo = {0}, @NewPONo = {1}, @NewRevisionID = {2}, @AddedBy = {3}",
                    oldPono, newPono, newRevisionId, addedBy
                );

                return Ok(new
                {
                    success = true,
                    message = "Purchase Order revised successfully.",
                    newPono,
                    newRevisionId,
                    newRevisionNo // ✅ Format: "Rev-03"
                });
            }
            catch (Exception ex)
            {
                return StatusCode(500, new { success = false, message = "Server error: " + ex.Message });
            }
        }
        [HttpGet]
        public async Task<IActionResult> GetInvoiceCurrency()
        {
            try
            {
                if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
                {
                    var result = await dbContext.Tbl20169CurrencyExchanges
                    .Select(g => new
                    {
                        g.CurrencyExchangeId,
                        g.CurrencyName,
                        g.CurrencyNameAr,
                        g.ExchangeRate,
                        g.CurrencyCode,
                        g.CurrencyCodeAr

                    })
                    .ToListAsync();

                    return Ok(result);
                }
            }
            catch (Exception ex) { throw ex; }
            return Unauthorized(new { message = "Invalid tenant.", success = false });

        }
        [HttpGet]
        public async Task<IActionResult> GetRevisions(string pono)
        {
            if (string.IsNullOrWhiteSpace(pono))
                return BadRequest(new { success = false, message = "PO number is required." });

            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
                return Unauthorized(new { success = false, message = "Invalid tenant." });

            // Fetch all revisions that start with original PO (e.g., "PIT-PO-2025-0012")
            var revisions = await dbContext.Tbl60401purchaseOrderMasters
                .Where(x => x.Pono.StartsWith(pono)) // match base PO or base-RX
                .OrderBy(x => x.PorevisionId)
                .Select(x => new
                {
                    x.PorevisionId,
                    PorevisionNo = $"Rev-{(x.PorevisionId ?? 0):00}"
                })
                .ToListAsync();

            if (!revisions.Any())
                return Ok(new { success = true, revisions = new List<object>(), currentRevisionId = 0 });

            int currentRevisionId = revisions.Max(x => x.PorevisionId ?? 0);

            return Ok(new
            {
                success = true,
                revisions,
                currentRevisionId
            });
        }

       [HttpGet]
public async Task<IActionResult> GetGroupedPurchaseOrders(DateTime? fromDate, DateTime? toDate)
{
    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
        return Unauthorized();

    // Default to current month if not provided
    if (!fromDate.HasValue)
        fromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
    if (!toDate.HasValue)
        toDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month));

    var rawList = await dbContext.Qry60404purchaseOrderViewMasters
        .AsNoTracking()
        .Where(x => x.Podate >= fromDate && x.Podate <= toDate)
        .ToListAsync();

    var groupedList = rawList
        .GroupBy(po => System.Text.RegularExpressions.Regex.Replace(po.Pono, "-R\\d+$", ""))
        .Select(g =>
        {
            var latest = g.OrderByDescending(x => x.PorevisionId).First();

            return new
            {
                Pono = g.Key,
                LatestRevisionId = latest.PorevisionId,
                LatestRevisionNo = $"Rev-{latest.PorevisionId:00}",
                LastPODate = latest.Podate,
                SupplierName = latest.SupplierName,
                Status = latest.IsApproved ? "Approved" : "Pending",
                IsSubmitted = latest.IsSubmitted,
                IsVerified = latest.IsVerified,
                PorevisionNo = latest.PorevisionNo,
                IsApproved = latest.IsApproved,
                NoOfItems = latest.NoOfItems,
                OrderStatus = latest.OrderStatus,
                BillStatus = latest.BillStatus,
                TotalBeforeTax = latest.TotalBeforeTax,
                TotalDiscount = latest.TotalDiscount,
                TotalAfterDiscount = latest.TotalAfterDiscount,
                TotalTaxAmount = latest.TotalTaxAmount,
                TotalWithTax = latest.TotalWithTax,
                AdditionsAmount = latest.AdditionsAmount,
                DeductionsAmount = latest.DeductionsAmount,
                GrandTotal = latest.GrandTotal
            };
        })
        .OrderByDescending(x => x.LastPODate)
        .ToList();

    return Ok(groupedList);
}

[HttpGet]
public async Task<IActionResult> GetOrderStatus(string pono)
{
    if (string.IsNullOrWhiteSpace(pono))
        return Ok(new { success = false, message = "PO number is required." });

    if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out var tenant, out var dbContext))
        return Unauthorized(new { success = false, message = "Invalid tenant." });

    var po = await dbContext.Qry60404purchaseOrderViewMasters
        .AsNoTracking()
        .FirstOrDefaultAsync(x => x.Pono == pono);

    if (po == null)
        return Ok(new { success = false, message = "Purchase Order not found." });

    return Ok(new { success = true, orderStatus = po.OrderStatus });
}

        [HttpPost]
        public IActionResult SaveReportAttribute([FromBody] ReportAttributeUpdateModel model)
        {
            if (model == null || string.IsNullOrEmpty(model.ReportNo) || string.IsNullOrEmpty(model.Field))
            {
                return BadRequest(new { message = "Invalid input data" });
            }

            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var record = dbContext.Tbl90112ReportAttributes
                    .FirstOrDefault(r => r.ReportNo == model.ReportNo);

                if (record == null)
                    return NotFound(new { message = "Report not found." });

                // Update only the requested field
                switch (model.Field)
                {
                    case "ReportSubject":
                        record.ReportSubject = model.Value;
                        break;
                    case "ReportSummary":
                        record.ReportSummary = model.Value;
                        break;
                    case "ReportIntroduction":
                        record.ReportIntroduction = model.Value;
                        break;
                    case "ReportThanksNote":
                        record.ReportThanksNote = model.Value;
                        break;
                    default:
                        return BadRequest(new { message = "Invalid field name." });
                }

                dbContext.SaveChanges();
                _userActionLogger.LogAsync(module: "IMS > Save Report Attribute View ",
                  actionDetail: $"Saved Report Attribute {model.ReportNo}",
                    documentNo: $"{model.ReportNo}"
                );
                return Ok(new { message = "Field updated successfully." });
            }

            return Unauthorized();
        }
        [HttpGet]
        public IActionResult GetReportAttributes(string reportNo)
        {
            if (string.IsNullOrEmpty(reportNo))
                return BadRequest(new { message = "Report number is required." });

            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                var result = dbContext.Tbl90112ReportAttributes
                    .Where(r => r.ReportNo == reportNo)
                    .Select(r => new
                    {
                        r.ReportSubject,
                        r.ReportSummary,
                        r.ReportIntroduction,
                        r.ReportThanksNote
                    })
                    .FirstOrDefault();

                if (result == null)
                    return NotFound(new { message = "No report found" });

                return Json(result);
            }

            return Unauthorized();
        }

        [HttpGet]
        public async Task<IActionResult> GetDetaildescriptiondata(long poChildNo)
        {
            if (_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                if (poChildNo == 0)
                    return BadRequest("poChildNo is required.");


                try
                {

                    var client = await dbContext.Tbl60402purchaseOrderChildren
                        .Where(c => c.PochildNo == poChildNo)
                        .FirstOrDefaultAsync();

                    if (client == null)
                        return NotFound("Client not found.");

                    return Ok(client);
                }
                catch (Exception ex)
                {
                    _logger.LogError($"Error in GetProject: {ex.Message}");
                    return StatusCode(500, $"Internal server error: {ex.Message}");
                }
            }

            return Unauthorized(new { message = "Invalid tenant.", success = false });
        }
        public class ReportAttributeUpdateModel
        {
            public string ReportNo { get; set; }       // Always "IMS-QTN-01"
            public string Field { get; set; }          // e.g., "ReportSubject"
            public string Value { get; set; }          // The new value
        }
        [HttpGet]
        public IActionResult CheckIfApproved(string pono)
        {
            // Step 1: Get tenant and DB context
            if (!_tenantDbContextHelper.TryGetTenantAndDbContext(out Tenant tenant, out ERPMasterWtDataContext dbContext))
            {
                return Unauthorized(new { message = "Invalid tenant", success = false });
            }

            // Step 2: Validate input
            if (string.IsNullOrWhiteSpace(pono))
            {
                return BadRequest(new { message = "Invalid PO number.", success = false });
            }

            // Step 3: Fetch PO and check IsApproved
            var po = dbContext.Tbl60401purchaseOrderMasters
                .Where(p => p.Pono == pono)
                .Select(p => new { p.IsApproved })
                .FirstOrDefault();

            if (po == null)
            {
                return NotFound(new { message = "Purchase Order not found.", success = false });
            }

            return Ok(new
            {
                success = true,
                isApproved = po.IsApproved
            });
        }


    }
    public class PurchaseOrderViewModel
{
        public decimal? CurrencyRate { get; set; }
        public int? BaseCurrencyId { get; set; }
        public int? CurrencyId { get; set; }

        public Tbl60401purchaseOrderMaster Master { get; set; }
    public List<Tbl60402purchaseOrderChild> Children { get; set; }
}



}
